# Generated by Django 5.0.5 on 2024-05-07 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название валюты')),
                ('words_code', models.CharField(max_length=30, verbose_name='Букв. код')),
                ('code', models.SmallIntegerField(verbose_name='Цифр. код')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Единица измерения поставщика')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=40, verbose_name='фаил в системе')),
                ('link', models.CharField(max_length=40, verbose_name='ссылка у поставщика')),
                ('hide', models.BinaryField(verbose_name='скрыть')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=40, verbose_name='фаил в системе')),
                ('link', models.CharField(max_length=40, verbose_name='ссылка у поставщика')),
                ('hide', models.BinaryField(verbose_name='скрыть')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название')),
                ('value', models.CharField(max_length=40, verbose_name='значение')),
                ('unit_measure', models.CharField(max_length=40, verbose_name='значение')),
                ('hide', models.BinaryField(verbose_name='скрыть')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_supplier', models.PositiveIntegerField(verbose_name='Остаток на складе поставщика в единицах поставщика')),
                ('lot_complect', models.PositiveIntegerField(verbose_name='Содержание набора (комплекта) в штуках')),
                ('stock_supplier_unit', models.PositiveIntegerField(verbose_name='Остаток на складе поставщика в штуках')),
                ('stock_motrum', models.PositiveIntegerField(verbose_name='Остаток на складе Motrum в штуках')),
            ],
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(verbose_name='процент ндс')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('rate', models.PositiveIntegerField(verbose_name='курс ЦБ')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.currency')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название группы')),
                ('article_name', models.CharField(max_length=25, verbose_name='Артикул группы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Группа товара',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_supplier', models.PositiveIntegerField(verbose_name='Цена в каталоге поставщика в валюте каталога')),
                ('rub_price_supplier', models.PositiveIntegerField(verbose_name='Цена в каталоге поставщика в рублях')),
                ('price_motrum', models.PositiveIntegerField(verbose_name='Цена поставщика для Motrum в рублях')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveIntegerField(verbose_name='Артикул мотрум')),
                ('article_supplier', models.CharField(max_length=50, verbose_name='Артикул поставщика')),
                ('additional_article_supplier', models.CharField(max_length=50, verbose_name='Дополнительный артикул поставщика')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('check_image_upgrade', models.BinaryField(verbose_name='было изменено вручную')),
                ('check_document_upgrade', models.BinaryField(verbose_name='было изменено вручную')),
                ('check_property_upgrade', models.BinaryField(verbose_name='было изменено вручную')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct', verbose_name='Поставщик')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.groupproduct')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.price')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
