# Generated by Django 5.0.5 on 2024-05-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='supplier.supplier', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.lot'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.stock'),
        ),
        migrations.AddField(
            model_name='price',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.vat'),
        ),
    ]
