# Generated by Django 5.0.5 on 2024-05-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_vat_delete_testmodel'),
        ('product', '0003_alter_currency_options'),
        ('supplier', '0003_alter_vendor_currency_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vat'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Vat',
        ),
    ]
