# Generated by Django 5.0.6 on 2024-05-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_currencyrate_currency_alter_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupproduct',
            options={'verbose_name': 'Группа товара', 'verbose_name_plural': 'Группы товаров'},
        ),
    ]
