# Generated by Django 5.0.6 on 2024-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_groupproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название группы'),
        ),
    ]
