# Generated by Django 5.0.6 on 2024-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_categoryproduct_name_alter_groupproduct_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'verbose_name': 'Единица измерения поставщика', 'verbose_name_plural': 'Единицы измерения поставщика'},
        ),
        migrations.AddField(
            model_name='lot',
            name='name_shorts',
            field=models.CharField(max_length=6, null=True, verbose_name='Короткое название'),
        ),
        migrations.AddField(
            model_name='lot',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Полное название'),
        ),
    ]
