# Generated by Django 5.0.6 on 2024-05-14 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_lot_options_product_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(null=True, upload_to='core.utils.get_image_path', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_article_supplier',
            field=models.CharField(max_length=50, null=True, verbose_name='Дополнительный артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='check_document_upgrade',
            field=models.BinaryField(null=True, verbose_name='было изменено вручную'),
        ),
        migrations.AlterField(
            model_name='product',
            name='check_image_upgrade',
            field=models.BinaryField(null=True, verbose_name='было изменено вручную'),
        ),
        migrations.AlterField(
            model_name='product',
            name='check_property_upgrade',
            field=models.BinaryField(null=True, verbose_name='было изменено вручную'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.groupproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.stock'),
        ),
    ]
