# Generated by Django 5.0.6 on 2024-05-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productimage_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='check_document_upgrade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='check_image_upgrade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='check_property_upgrade',
        ),
        migrations.RemoveField(
            model_name='productdocument',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='hide',
        ),
    ]
