# Generated by Django 5.0.6 on 2024-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_check_document_upgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='check_document_upgrade',
            field=models.BooleanField(default=False, verbose_name='было изменено вручную'),
        ),
        migrations.AddField(
            model_name='product',
            name='check_image_upgrade',
            field=models.BooleanField(default=False, verbose_name='было изменено вручную'),
        ),
        migrations.AddField(
            model_name='product',
            name='check_property_upgrade',
            field=models.BooleanField(default=False, verbose_name='было изменено вручную'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(null=True, upload_to='core.utils.get_image_path', verbose_name='Изображение'),
        ),
    ]
