# Generated by Django 5.0.6 on 2024-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_check_document_upgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='скрыть'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.CharField(max_length=40, null=True, verbose_name='фаил в системе'),
        ),
    ]
