# Generated by Django 5.0.6 on 2024-05-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='unit_measure',
            field=models.CharField(max_length=40, null=True, verbose_name='значение'),
        ),
    ]
