# Generated by Django 5.0.6 on 2024-05-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productproperty_unit_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='скрыть'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='скрыть'),
        ),
    ]
