# Generated by Django 5.0.6 on 2024-05-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productdocument_hide_productproperty_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='document',
            field=models.FileField(null=True, upload_to='core.utils.get_file_path', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.CharField(max_length=40, null=True, verbose_name='фаил в системе'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(null=True, upload_to='core.utils.get_file_path', verbose_name='Изображение'),
        ),
    ]
