# Generated by Django 5.0.6 on 2024-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productdocument_document_alter_productdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.CharField(max_length=100, null=True, verbose_name='фаил в системе'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='link',
            field=models.CharField(max_length=100, verbose_name='ссылка у поставщика'),
        ),
    ]
