# Generated by Django 5.0.6 on 2024-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productimage_file_alter_productimage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.CharField(max_length=100, null=True, verbose_name='фаил в системе'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='link',
            field=models.CharField(max_length=100, verbose_name='ссылка у поставщика'),
        ),
    ]
