# Generated by Django 5.0.6 on 2024-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=550, null=True, verbose_name='Описание товара'),
        ),
    ]
