# Generated by Django 5.0.6 on 2024-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_motrum',
            field=models.FloatField(verbose_name='Цена поставщика для Motrum в рублях'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_supplier',
            field=models.FloatField(verbose_name='Цена в каталоге поставщика в валюте каталога'),
        ),
        migrations.AlterField(
            model_name='price',
            name='rub_price_supplier',
            field=models.FloatField(verbose_name='Цена в каталоге поставщика в рублях'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание товара'),
        ),
    ]
