# Generated by Django 5.0.6 on 2024-05-16 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_price_prod_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='prod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_price', to='product.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_stock', to='product.product'),
        ),
    ]
