# Generated by Django 5.0.6 on 2024-05-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_price_prod_alter_stock_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
