# Generated by Django 5.0.6 on 2024-05-16 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_product_price_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_article_supplier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дополнительный артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.groupproduct', verbose_name='Группа'),
        ),
    ]
