# Generated by Django 5.0.6 on 2024-05-17 07:21

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_additional_article_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='file',
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='document',
            field=models.FileField(null=True, upload_to=apps.core.utils.get_file_path_add, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lot_complect',
            field=models.PositiveIntegerField(default=1, verbose_name='Содержание набора (комплекта) в штуках'),
        ),
    ]
