# Generated by Django 5.0.6 on 2024-05-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_productimage_file_and_more'),
        ('supplier', '0020_discount_category_supplier_discount_group_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.discount', verbose_name='Примененная скидка'),
        ),
    ]
