# Generated by Django 5.0.6 on 2024-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_price_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='vat_include',
            field=models.BooleanField(default=True, verbose_name='Включен ли налог в цену'),
        ),
    ]
