# Generated by Django 5.0.6 on 2024-05-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_price_vat_include'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='rub_price_supplier',
            field=models.FloatField(verbose_name='Цена в каталоге поставщика в рублях + НДС'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название товара'),
        ),
    ]
