# Generated by Django 5.0.6 on 2024-05-20 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_price_rub_price_supplier_alter_product_name'),
        ('supplier', '0021_remove_discount_category_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_supplier_all',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercategoryproductall', verbose_name='Приходящая категории товара от поставщиков'),
        ),
    ]
