# Generated by Django 5.0.6 on 2024-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_product_category_supplier_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='type_doc',
            field=models.CharField(max_length=150, null=True, verbose_name='Тип документации'),
        ),
    ]
