# Generated by Django 5.0.6 on 2024-05-22 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vat_options_rename_code_vat_name'),
        ('product', '0033_productdocument_type_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyrate',
            name='rate',
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Единиц'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='курс ЦБ'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='vunit_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='курс ЦБ за еденицу'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
    ]
