# Generated by Django 5.0.6 on 2024-05-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_remove_currencyrate_rate_currencyrate_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='unit_measure',
            field=models.CharField(max_length=100, null=True, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='value',
            field=models.CharField(max_length=100, verbose_name='значение'),
        ),
    ]
