# Generated by Django 5.0.6 on 2024-05-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vat_options_rename_code_vat_name'),
        ('product', '0036_alter_product_description_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_motrum',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена поставщика для Motrum в рублях'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_supplier',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в каталоге поставщика в валюте каталога'),
        ),
        migrations.AlterField(
            model_name='price',
            name='rub_price_supplier',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в каталоге поставщика в рублях + НДС'),
        ),
        migrations.AlterField(
            model_name='price',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vat', verbose_name='НДС'),
        ),
    ]
