# Generated by Django 5.0.6 on 2024-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_price_price_motrum_alter_price_price_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=350, verbose_name='Название товара'),
        ),
    ]
