# Generated by Django 5.0.6 on 2024-05-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdocument',
            name='file',
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='type_doc',
            field=models.CharField(choices=[('InstallationProduct', 'Руководство по монтажу и эксплуатации'), ('DimensionDrawing', 'Габаритные чертежи'), ('Passport', 'Паспорт'), ('WiringDiagram', 'Схема подключения'), ('Models3d', '3D модели'), ('Brochure', 'Брошюра'), ('Other', 'Другое')], default='Other', max_length=40),
        ),
    ]
