# Generated by Django 5.0.6 on 2024-06-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_groupproduct_article_name'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='groupproduct',
        #     name='article_name',
        # ),
    ]
