# Generated by Django 5.0.6 on 2024-06-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_remove_groupproduct_article_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='category_supplier_all',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='historicalstock',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstock',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='historicalstock',
            name='prod',
        ),
        # migrations.RemoveField(
        #     model_name='groupproduct',
        #     name='article_name',
        # ),
        migrations.DeleteModel(
            name='HistoricalPrice',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalStock',
        ),
    ]
