# Generated by Django 5.0.6 on 2024-06-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_remove_groupproduct_article_name'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='groupproduct',
        #     name='article_name',
        #     field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул группы'),
        # ),
    ]
