# Generated by Django 5.0.6 on 2024-06-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_historicalprice_historicalproduct_historicalstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
