# Generated by Django 5.0.6 on 2024-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_historicalprice_history_change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
