# Generated by Django 5.0.6 on 2024-06-10 07:10

import django.db.models.deletion
import simple_history.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_historicaltesthistoricparticipantohistoricorganization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testhistoricparticipantohistoricorganization',
            name='organization',
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='product',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.DeleteModel(
            name='HistoricalTestHistoricParticipanToHistoricOrganization',
        ),
        migrations.DeleteModel(
            name='TestHistoricParticipanToHistoricOrganization',
        ),
    ]
