# Generated by Django 5.0.6 on 2024-06-10 07:34

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_remove_testhistoricparticipantohistoricorganization_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricForeignKeyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
