# Generated by Django 5.0.6 on 2024-06-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_delete_historicforeignkeytest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPrice',
        ),
    ]
