# Generated by Django 5.0.6 on 2024-06-10 09:07

import django.db.models.deletion
import simple_history.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_delete_historicalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='prod',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_stock', to='product.product'),
        ),
    ]
