# Generated by Django 5.0.6 on 2024-06-10 09:55

import django.db.models.deletion
import simple_history.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_historicalproduct_historicalstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='prod',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.product'),
        ),
    ]
