# Generated by Django 5.0.6 on 2024-06-10 11:16

import django.db.models.deletion
import simple_history.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_price_prod_alter_stock_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historic_stock', to='product.product'),
        ),
    ]
