# Generated by Django 5.0.6 on 2024-06-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_alter_stock_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstock',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstock',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='historicalstock',
            name='prod',
        ),
        migrations.AlterField(
            model_name='price',
            name='prod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_property', to='product.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historic_stock', to='product.product'),
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalStock',
        ),
    ]
