# Generated by Django 5.0.6 on 2024-06-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_historicalproductproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProductProperty',
        ),
    ]
