# Generated by Django 5.0.6 on 2024-06-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_alter_productproperty_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historic_property', to='product.product'),
        ),
        migrations.DeleteModel(
            name='HistoricalProductProperty',
        ),
    ]
