# Generated by Django 5.0.6 on 2024-06-13 09:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_alter_productproperty_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('document', models.TextField(max_length=100, null=True, verbose_name='Документ')),
                ('type_doc', models.CharField(choices=[('InstallationProduct', 'Руководство по монтажу и эксплуатации'), ('DimensionDrawing', 'Габаритные чертежи'), ('Passport', 'Паспорт'), ('WiringDiagram', 'Схема подключения'), ('Models3d', '3D модели'), ('Brochure', 'Брошюра'), ('Certificates', 'Сертификат'), ('Other', 'Другое')], default='Other', max_length=40, verbose_name='Тип документации')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='ссылка у поставщика')),
                ('hide', models.BooleanField(default=False, verbose_name='скрыть')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
            ],
            options={
                'verbose_name': 'historical Документация',
                'verbose_name_plural': 'historical Документации',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('photo', models.TextField(max_length=100, null=True, verbose_name='Изображение')),
                ('link', models.CharField(max_length=100, verbose_name='ссылка у поставщика')),
                ('hide', models.BooleanField(default=False, verbose_name='скрыть')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
            ],
            options={
                'verbose_name': 'historical Изображение',
                'verbose_name_plural': 'historical Изображения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
