# Generated by Django 5.0.6 on 2024-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_alter_historicalprice_history_change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductproperty',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
    ]
