# Generated by Django 5.0.6 on 2024-06-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_alter_historicalproductproperty_hide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='extra_price',
            field=models.BooleanField(default=False, verbose_name='Цена по запросу'),
        ),
        migrations.AddField(
            model_name='price',
            name='extra_price',
            field=models.BooleanField(default=False, verbose_name='Цена по запросу'),
        ),
    ]
