# Generated by Django 5.0.6 on 2024-06-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_historicalprice_extra_price_price_extra_price'),
        ('supplier', '0024_delete_supplierpastcategoryproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='category_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.suppliercategoryproduct', verbose_name='Категории товара от поставщиков'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='group_supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.suppliergroupproduct', verbose_name='Группа товара от поставщиков'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercategoryproduct', verbose_name='Категории товара от поставщиков'),
        ),
        migrations.AddField(
            model_name='product',
            name='group_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliergroupproduct', verbose_name='Группа товара от поставщиков'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='category_supplier_all',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.suppliercategoryproductall', verbose_name='Подгруппа категории товара от поставщиков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_supplier_all',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercategoryproductall', verbose_name='Подгруппа категории товара от поставщиков'),
        ),
    ]
