# Generated by Django 5.0.6 on 2024-06-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_historicalproduct_category_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='article',
            field=models.IntegerField(verbose_name='Артикул мотрум'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.IntegerField(verbose_name='Артикул мотрум'),
        ),
    ]
