# Generated by Django 5.0.6 on 2024-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_alter_historicalproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductdocument',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='type_doc',
            field=models.CharField(choices=[('InstallationProduct', 'Руководство по монтажу и эксплуатации'), ('DimensionDrawing', 'Габаритные чертежи'), ('Passport', 'Паспорт'), ('WiringDiagram', 'Схема подключения'), ('Models3d', '3D модели'), ('Brochure', 'Брошюра'), ('Certificates', 'Сертификат'), ('Other', 'Другое'), ('Soft', 'Программы')], default='Other', max_length=40, verbose_name='Тип документации'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='type_doc',
            field=models.CharField(choices=[('InstallationProduct', 'Руководство по монтажу и эксплуатации'), ('DimensionDrawing', 'Габаритные чертежи'), ('Passport', 'Паспорт'), ('WiringDiagram', 'Схема подключения'), ('Models3d', '3D модели'), ('Brochure', 'Брошюра'), ('Certificates', 'Сертификат'), ('Other', 'Другое'), ('Soft', 'Программы')], default='Other', max_length=40, verbose_name='Тип документации'),
        ),
    ]
