# Generated by Django 5.0.6 on 2024-06-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_historicalproductdocument_name_productdocument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='type_doc',
            field=models.CharField(choices=[('InstallationProduct', 'Руководство по монтажу и эксплуатации'), ('DimensionDrawing', 'Габаритные чертежи'), ('Passport', 'Паспорт'), ('WiringDiagram', 'Схема подключения'), ('Models3d', '3D модели'), ('Brochure', 'Брошюра'), ('Certificates', 'Сертификат'), ('Other', 'Другое'), ('Soft', 'Программы'), ('Doc', 'Руководства и Спецификации'), ('Text', 'Тексты')], default='Other', max_length=40, verbose_name='Тип документации'),
        ),
        migrations.AlterField(
            model_name='historicalproductimage',
            name='link',
            field=models.CharField(max_length=150, verbose_name='ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='type_doc',
            field=models.CharField(choices=[('InstallationProduct', 'Руководство по монтажу и эксплуатации'), ('DimensionDrawing', 'Габаритные чертежи'), ('Passport', 'Паспорт'), ('WiringDiagram', 'Схема подключения'), ('Models3d', '3D модели'), ('Brochure', 'Брошюра'), ('Certificates', 'Сертификат'), ('Other', 'Другое'), ('Soft', 'Программы'), ('Doc', 'Руководства и Спецификации'), ('Text', 'Тексты')], default='Other', max_length=40, verbose_name='Тип документации'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='link',
            field=models.CharField(max_length=150, verbose_name='ссылка у поставщика'),
        ),
    ]
