# Generated by Django 5.0.6 on 2024-06-19 11:58

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_alter_historicalproductproperty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='document',
            field=models.TextField(max_length=1000, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='link',
            field=models.CharField(max_length=1000, null=True, verbose_name='ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='type_doc',
            field=models.CharField(choices=[('InstallationProduct', 'Руководство по монтажу и эксплуатации'), ('DimensionDrawing', 'Габаритные чертежи'), ('Passport', 'Паспорт'), ('WiringDiagram', 'Схема подключения'), ('Models3d', '3D модели'), ('Brochure', 'Брошюра'), ('Certificates', 'Сертификат'), ('Other', 'Другое'), ('Soft', 'Программы'), ('Doc', 'Руководства и Спецификации'), ('Text', 'Тексты')], default='Other', max_length=100, verbose_name='Тип документации'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='document',
            field=models.FileField(max_length=1000, null=True, upload_to=apps.core.utils.get_file_path_add, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='link',
            field=models.CharField(max_length=1000, null=True, verbose_name='ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='type_doc',
            field=models.CharField(choices=[('InstallationProduct', 'Руководство по монтажу и эксплуатации'), ('DimensionDrawing', 'Габаритные чертежи'), ('Passport', 'Паспорт'), ('WiringDiagram', 'Схема подключения'), ('Models3d', '3D модели'), ('Brochure', 'Брошюра'), ('Certificates', 'Сертификат'), ('Other', 'Другое'), ('Soft', 'Программы'), ('Doc', 'Руководства и Спецификации'), ('Text', 'Тексты')], default='Other', max_length=100, verbose_name='Тип документации'),
        ),
    ]
