# Generated by Django 5.0.6 on 2024-07-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_alter_historicalproductdocument_document_and_more'),
        ('supplier', '0025_suppliercategoryproductall_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.discount', verbose_name='Примененная скидка'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
