# Generated by Django 5.0.6 on 2024-07-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_alter_price_sale_alter_productproperty_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='autosave_tag',
            field=models.BooleanField(default=True, verbose_name='автоматическая загрузка'),
        ),
        migrations.AddField(
            model_name='product',
            name='autosave_tag',
            field=models.BooleanField(default=True, verbose_name='автоматическая загрузка'),
        ),
    ]
