# Generated by Django 5.0.6 on 2024-07-04 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_currencypercent_percent'),
        ('product', '0083_historicalproduct_autosave_tag_product_autosave_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='to_order',
            field=models.BooleanField(default=False, verbose_name='Товар под заказ'),
        ),
        migrations.AddField(
            model_name='stock',
            name='to_order',
            field=models.BooleanField(default=False, verbose_name='Товар под заказ'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='price_supplier',
            field=models.FloatField(null=True, verbose_name='Цена в каталоге поставщика в валюте каталога'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_supplier',
            field=models.FloatField(null=True, verbose_name='Цена в каталоге поставщика в валюте каталога'),
        ),
        migrations.AlterField(
            model_name='price',
            name='vat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vat', verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание товара'),
        ),
    ]
