# Generated by Django 5.0.6 on 2024-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_historicalstock_to_order_stock_to_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(max_length=600, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=600, verbose_name='Название товара'),
        ),
    ]
