# Generated by Django 5.0.6 on 2024-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0085_alter_historicalproduct_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Описание товара'),
        ),
    ]
