# Generated by Django 5.0.6 on 2024-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_alter_historicalproduct_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupproduct',
            name='article_name',
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
