# Generated by Django 5.0.6 on 2024-07-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0087_remove_groupproduct_article_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='article_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул категории'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='article_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул категории'),
        ),
    ]
