# Generated by Django 5.0.6 on 2024-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0088_categoryproduct_article_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductproperty',
            name='name',
            field=models.CharField(max_length=400, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='historicalproductproperty',
            name='unit_measure',
            field=models.CharField(max_length=400, null=True, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='historicalproductproperty',
            name='value',
            field=models.CharField(max_length=400, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='name',
            field=models.CharField(max_length=400, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='unit_measure',
            field=models.CharField(max_length=400, null=True, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='value',
            field=models.CharField(max_length=400, verbose_name='значение'),
        ),
    ]
