# Generated by Django 5.0.7 on 2024-07-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0090_alter_historicalproductproperty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductproperty',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
