# Generated by Django 5.0.7 on 2024-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_alter_historicalproductproperty_history_change_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductproperty',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
