# Generated by Django 5.0.7 on 2024-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0092_alter_historicalproductproperty_history_change_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
    ]
