# Generated by Django 5.0.7 on 2024-07-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_alter_categoryproduct_name_alter_groupproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='additional_article_supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительный артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='article',
            field=models.CharField(max_length=100, verbose_name='Артикул мотрум'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='article_supplier',
            field=models.CharField(max_length=100, verbose_name='Артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_article_supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительный артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, verbose_name='Артикул мотрум'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_supplier',
            field=models.CharField(max_length=100, verbose_name='Артикул поставщика'),
        ),
    ]
