# Generated by Django 5.0.7 on 2024-07-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0094_alter_historicalproduct_additional_article_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
