# Generated by Django 5.0.7 on 2024-07-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_historicalproduct_check_to_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='data_transit',
            field=models.DateField(blank=True, null=True, verbose_name='Ближайшая поставка дата'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='transit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ближайшая поставка количество'),
        ),
        migrations.AddField(
            model_name='stock',
            name='data_transit',
            field=models.DateField(blank=True, null=True, verbose_name='Ближайшая поставка дата'),
        ),
        migrations.AddField(
            model_name='stock',
            name='transit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ближайшая поставка количество'),
        ),
    ]
