# Generated by Django 5.0.7 on 2024-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0098_historicalstock_data_transit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='is_one_sale',
            field=models.BooleanField(default=True, verbose_name='Разрешение продавать поштучно'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='order_multiplicity',
            field=models.PositiveIntegerField(default=1, verbose_name='Коэффициент кратности заказа'),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_one_sale',
            field=models.BooleanField(default=True, verbose_name='Разрешение продавать поштучно'),
        ),
        migrations.AddField(
            model_name='stock',
            name='order_multiplicity',
            field=models.PositiveIntegerField(default=1, verbose_name='Коэффициент кратности заказа'),
        ),
    ]
