# Generated by Django 5.0.7 on 2024-07-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0099_historicalstock_is_one_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='check_document_upgrade',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='check_image_upgrade',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='check_property_upgrade',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='data_update',
        ),
        migrations.RemoveField(
            model_name='product',
            name='check_document_upgrade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='check_image_upgrade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='check_property_upgrade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='data_update',
        ),
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
