# Generated by Django 5.0.7 on 2024-07-24 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0100_remove_historicalproduct_check_document_upgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='data_update',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='data_update',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
