# Generated by Django 5.0.7 on 2024-07-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0102_alter_historicalproductproperty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='data_update',
            field=models.DateField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='data_update',
            field=models.DateField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='data_update',
            field=models.DateField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='price',
            name='data_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='data_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
