# Generated by Django 5.0.7 on 2024-07-29 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0103_alter_historicalprice_data_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_supplier',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток на складе поставщика в единицах поставщика'),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_supplier_unit',
            field=models.PositiveIntegerField(null=True, verbose_name='Остаток на складе поставщика в штуках'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_supplier',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток на складе поставщика в единицах поставщика'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_supplier_unit',
            field=models.PositiveIntegerField(null=True, verbose_name='Остаток на складе поставщика в штуках'),
        ),
    ]
