# Generated by Django 5.0.7 on 2024-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0104_alter_historicalstock_stock_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='data_update',
            field=models.DateField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='data_update',
            field=models.DateField(verbose_name='Дата обновления'),
        ),
    ]
