# Generated by Django 5.0.7 on 2024-08-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0106_alter_historicalstock_data_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
