# Generated by Django 5.0.7 on 2024-08-06 12:42

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0107_categoryproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='website/catalog/group', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.core.utils_web.get_file_path_catalog_web, verbose_name='Изображение категории'),
        ),
    ]
