# Generated by Django 5.1 on 2024-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0109_categoryproduct_is_view_home_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='article_home_web',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность вывода на главную'),
        ),
    ]
