# Generated by Django 5.1 on 2024-08-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0112_cart_productcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='save_cart',
            new_name='is_active',
        ),
    ]
