# Generated by Django 5.1 on 2024-09-09 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0113_rename_save_cart_cart_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукты'),
        ),
    ]
