# Generated by Django 5.1 on 2024-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0114_alter_productcart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='product_new',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Название товара нового без добавления в бд'),
        ),
    ]
