# Generated by Django 5.1 on 2024-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0115_productcart_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='product_new_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Цена товара нового без добавления в бд'),
        ),
    ]
