# Generated by Django 5.1.1 on 2024-09-18 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_order_act_file_alter_order_bill_sum_paid'),
        ('product', '0116_productcart_product_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Клиент'),
        ),
    ]
