# Generated by Django 5.1.1 on 2024-09-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0117_alter_cart_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='stock_motrum',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе Motrum в штуках'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_motrum',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе Motrum в штуках'),
        ),
    ]
