# Generated by Django 5.1.1 on 2024-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0120_alter_productcart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='data_update',
            field=models.DateField(blank=True, editable=False, verbose_name='Дата обновления поставщика'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='data_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления поставщика'),
        ),
    ]
