# Generated by Django 5.1.2 on 2024-10-28 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0122_productcart_product_new_article_and_more'),
        ('user', '0010_adminuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_admin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.adminuser', verbose_name='Администратор'),
        ),
    ]
