# Generated by Django 5.1.2 on 2024-10-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0124_alter_cart_cart_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
    ]
