# Generated by Django 5.1.2 on 2024-11-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0125_productcart_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='stock_motrum_reserve',
            field=models.PositiveIntegerField(default=0, verbose_name='Резерв на складе Motrum в штуках'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_motrum_reserve',
            field=models.PositiveIntegerField(default=0, verbose_name='Резерв на складе Motrum в штуках'),
        ),
    ]
