# Generated by Django 5.1.2 on 2024-11-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0126_historicalstock_stock_motrum_reserve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='add_in_nomenclature',
            field=models.BooleanField(default=False, verbose_name='Загрузка из номенклатуры'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='in_view_website',
            field=models.BooleanField(default=True, verbose_name='Видимость на сайте'),
        ),
        migrations.AddField(
            model_name='product',
            name='add_in_nomenclature',
            field=models.BooleanField(default=False, verbose_name='Загрузка из номенклатуры'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_view_website',
            field=models.BooleanField(default=True, verbose_name='Видимость на сайте'),
        ),
    ]
