# Generated by Django 5.1.2 on 2024-11-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0128_historicalprice_in_auto_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='in_auto_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_auto_sale',
        ),
    ]
