# Generated by Django 5.1.2 on 2024-11-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0130_productcart_product_new_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcart',
            old_name='product_new_vendor',
            new_name='vendor',
        ),
    ]
