# Generated by Django 5.1.2 on 2024-11-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_rename_product_new_vendor_productcart_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='product_new_sale_motrum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Скидка мотрум товара нового без добавления в бд'),
        ),
    ]
