# Generated by Django 5.1.2 on 2024-11-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0133_alter_productcart_product_new_sale_motrum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='price_supplier',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена в каталоге поставщика в валюте каталога'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_supplier',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена в каталоге поставщика в валюте каталога'),
        ),
    ]
