# Generated by Django 5.1.2 on 2024-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0134_alter_historicalprice_price_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='add_in_nomenclature',
            field=models.BooleanField(default=False, verbose_name='Загружен из номенклатуры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_in_nomenclature',
            field=models.BooleanField(default=False, verbose_name='Загружен из номенклатуры'),
        ),
    ]
