# Generated by Django 5.1.2 on 2024-11-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0135_alter_historicalproduct_add_in_nomenclature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['pk'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
