# Generated by Django 5.1.2 on 2024-12-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0136_alter_productimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='product_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Цена товара'),
        ),
    ]
