# Generated by Django 5.1.2 on 2024-12-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0137_productcart_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='product_sale_motrum',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Скидка мотрум товара '),
        ),
    ]
