# Generated by Django 5.1.5 on 2025-01-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0139_productcart_sale_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='tag_auto_document',
            field=models.CharField(choices=[('ONE', 'Один вариант'), ('MULTI', 'Несколько вариантов'), ('NONE', 'Нет варинтов'), ('-', 'Не из документа')], default='-', max_length=100),
        ),
    ]
