# Generated by Django 5.1.5 on 2025-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0141_productcart_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductimage',
            name='link',
            field=models.CharField(max_length=250, verbose_name='Ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='link',
            field=models.CharField(max_length=250, verbose_name='Ссылка у поставщика'),
        ),
    ]
