# Generated by Django 5.1.5 on 2025-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0143_historicalstock_data_update_motrum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='is_send_email',
            field=models.BooleanField(default=False, verbose_name='Отображение в емаил рассылке'),
        ),
    ]
