# Generated by Django 5.1.5 on 2025-03-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0144_categoryproduct_is_send_email'),
        ('supplier', '0044_suppliercategoryproductall_is_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.categoryproduct', verbose_name='Категория Мотрум'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliercategoryproduct', verbose_name='Категории товара от поставщиков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_supplier_all',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliercategoryproductall', verbose_name='Подгруппа категории товара от поставщиков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.groupproduct', verbose_name='Группа Мотрум'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliergroupproduct', verbose_name='Группа товара от поставщиков'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
    ]
