# Generated by Django 5.1.5 on 2025-03-21 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0145_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='prod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
