# Generated by Django 5.1.5 on 2025-03-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0146_alter_stock_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='additional_article_supplier',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='article',
            field=models.CharField(max_length=500, verbose_name='Артикул мотрум'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='article_supplier',
            field=models.CharField(max_length=500, verbose_name='Артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_article_supplier',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительный артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=500, verbose_name='Артикул мотрум'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_supplier',
            field=models.CharField(max_length=500, verbose_name='Артикул поставщика'),
        ),
    ]
