# Generated by Django 5.1.5 on 2025-03-24 08:34

import apps.core.utils
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0147_alter_cart_session_key_alter_categoryproduct_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to=apps.core.utils.get_file_path_add, verbose_name='Изображение'),
        ),
    ]
