# Generated by Django 5.1.5 on 2025-03-24 08:45

import apps.core.utils
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0148_alter_productimage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductimage',
            name='photo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[500, 850], upload_to=apps.core.utils.get_file_path_add),
        ),
    ]
