# Generated by Django 5.1.5 on 2025-03-24 09:10

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0149_alter_historicalproductimage_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductimage',
            name='photo',
            field=models.TextField(max_length=100, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add, verbose_name='Изображение'),
        ),
    ]
