# Generated by Django 5.1.5 on 2025-04-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0150_alter_historicalproductimage_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='date_delivery',
            field=models.DateField(null=True, verbose_name='Дата поставки товара'),
        ),
    ]
