# Generated by Django 5.1.5 on 2025-04-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_productcart_date_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='product_price_motrum',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Цена товара'),
        ),
    ]
