# Generated by Django 5.1.5 on 2025-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_alter_historicalproductimage_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ссылка у поставщика'),
        ),
    ]
