# Generated by Django 5.1.5 on 2025-06-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_alter_historicalproductimage_photo_and_more'),
        ('supplier', '0045_supplierpromogroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='promo_groupe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.supplierpromogroupe', verbose_name='Промо группа'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplierpromogroupe', verbose_name='Промо группа'),
        ),
    ]
