# Generated by Django 5.1.5 on 2025-06-30 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0152_historicalproduct_promo_groupe_product_promo_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertyMotrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Характеристика товара мотрум',
                'verbose_name_plural': 'Характеристики товаров мотрум',
            },
        ),
        migrations.CreateModel(
            name='ProductPropertyValueMotrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=600, verbose_name='Значение')),
                ('property_motrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productpropertymotrum')),
            ],
            options={
                'verbose_name': 'Значение характеристики товара мотрум',
                'verbose_name_plural': 'Значение характеристик товаров мотрум',
            },
        ),
    ]
