# Generated by Django 5.1.5 on 2025-04-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_alter_historicalproductimage_photo_and_more'),
        ('product', '0152_productcart_product_price_motrum'),
    ]

    operations = [
    ]
