# Generated by Django 5.1.5 on 2025-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0152_historicalproduct_promo_groupe_product_promo_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='price_motrum',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена поставщика для Motrum в рублях с НДС'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='price_supplier',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена в каталоге поставщика в валюте каталога с НДС'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='rub_price_supplier',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в каталоге поставщика в рублях с НДС'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_motrum',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена поставщика для Motrum в рублях с НДС'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_supplier',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена в каталоге поставщика в валюте каталога с НДС'),
        ),
        migrations.AlterField(
            model_name='price',
            name='rub_price_supplier',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в каталоге поставщика в рублях с НДС'),
        ),
    ]
