# Generated by Django 5.1.5 on 2025-06-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_merge_20250422_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='sale_marja',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Маржа'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='sale_client',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Скидка клиента'),
        ),
    ]
