# Generated by Django 5.1.5 on 2025-06-30 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_productpropertymotrum_productpropertyvaluemotrum'),
        ('supplier', '0050_alter_supplierpromogroupe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPropertyAndMotrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_vendor_name', models.CharField(max_length=600, verbose_name='Название')),
                ('property_vendor_value', models.CharField(max_length=600, verbose_name='Значение')),
                ('property_motrum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productpropertymotrum')),
                ('property_value_motrum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productpropertyvaluemotrum')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Производитель')),
            ],
        ),
        migrations.AddField(
            model_name='historicalproductproperty',
            name='vendor_property_motrum',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.vendorpropertyandmotrum'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='vendor_property_motrum',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.vendorpropertyandmotrum'),
        ),
    ]
