# Generated by Django 5.1.5 on 2025-06-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0154_vendorpropertyandmotrum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpropertyandmotrum',
            options={'verbose_name': 'Значение характеристики товара мотрум для характеристики поставщика', 'verbose_name_plural': 'Значение характеристик товаров мотрум для характеристики поставщика'},
        ),
        migrations.AddField(
            model_name='historicalproductproperty',
            name='property_motrum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.productpropertymotrum'),
        ),
        migrations.AddField(
            model_name='historicalproductproperty',
            name='property_value_motrum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.productpropertyvaluemotrum'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='property_motrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productpropertymotrum'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='property_value_motrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productpropertyvaluemotrum'),
        ),
    ]
