# Generated by Django 5.1.5 on 2025-06-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0154_productcart_sale_marja_alter_productcart_sale_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.lot', verbose_name='Единица измерения'),
        ),
    ]
