# Generated by Django 5.1.5 on 2025-06-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0152_historicalproduct_promo_groupe_product_promo_groupe'),
        ('product', '0155_productcart_lot'),
    ]

    operations = [
    ]
