# Generated by Django 5.1.5 on 2025-07-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0155_alter_vendorpropertyandmotrum_options_and_more'),
        ('supplier', '0050_alter_supplierpromogroupe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpropertyandmotrum',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
