# Generated by Django 5.1.5 on 2025-07-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0152_alter_productdocument_link'),
        ('product', '0156_merge_20250619_1744'),
    ]

    operations = [
    ]
