# Generated by Django 5.1.5 on 2025-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0156_vendorpropertyandmotrum_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertyvaluemotrum',
            name='is_diapason',
            field=models.BooleanField(default=False, verbose_name='Диапазонное значение'),
        ),
        migrations.AddField(
            model_name='vendorpropertyandmotrum',
            name='is_diapason',
            field=models.BooleanField(default=False, verbose_name='Диапазонное значение'),
        ),
        migrations.AlterField(
            model_name='productpropertyvaluemotrum',
            name='value',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='vendorpropertyandmotrum',
            name='property_vendor_name',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vendorpropertyandmotrum',
            name='property_vendor_value',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Значение'),
        ),
    ]
