# Generated by Django 5.1.5 on 2025-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0157_productpropertyvaluemotrum_is_diapason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductproperty',
            name='is_diapason',
            field=models.BooleanField(default=False, verbose_name='Диапазонное значение'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='is_diapason',
            field=models.BooleanField(default=False, verbose_name='Диапазонное значение'),
        ),
    ]
