# Generated by Django 5.1.5 on 2025-07-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0158_historicalproductproperty_is_diapason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertymotrum',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
    ]
