# Generated by Django 5.1.5 on 2025-07-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0159_productpropertymotrum_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpropertyandmotrum',
            name='is_property_motrum',
            field=models.BooleanField(default=False, verbose_name='Есть ли хор ка мотрум '),
        ),
    ]
