# Generated by Django 5.1.5 on 2025-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0160_vendorpropertyandmotrum_is_property_motrum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpropertyandmotrum',
            name='is_property_motrum',
        ),
        migrations.AddField(
            model_name='historicalproductproperty',
            name='is_property_motrum',
            field=models.BooleanField(default=False, verbose_name='Есть ли хор ка мотрум '),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='is_property_motrum',
            field=models.BooleanField(default=False, verbose_name='Есть ли хор ка мотрум '),
        ),
    ]
