# Generated by Django 5.1.5 on 2025-07-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0161_remove_vendorpropertyandmotrum_is_property_motrum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyItemAndMotrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_props', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productproperty')),
                ('vendor_property_motrum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.vendorpropertyandmotrum')),
            ],
        ),
    ]
