# Generated by Django 5.1.5 on 2025-07-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0162_propertyitemandmotrum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductproperty',
            name='is_diapason',
        ),
        migrations.RemoveField(
            model_name='historicalproductproperty',
            name='is_property_motrum',
        ),
        migrations.RemoveField(
            model_name='historicalproductproperty',
            name='property_motrum',
        ),
        migrations.RemoveField(
            model_name='historicalproductproperty',
            name='property_value_motrum',
        ),
        migrations.RemoveField(
            model_name='historicalproductproperty',
            name='vendor_property_motrum',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='is_diapason',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='is_property_motrum',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='property_motrum',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='property_value_motrum',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='vendor_property_motrum',
        ),
        migrations.AddField(
            model_name='productpropertymotrum',
            name='is_diapason',
            field=models.BooleanField(default=False, verbose_name='Диапазонное значение'),
        ),
        migrations.CreateModel(
            name='ProductPropertyMotrumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_diapason', models.BooleanField(default=False, verbose_name='Диапазонное значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('property_motrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productpropertymotrum')),
                ('property_value_motrum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productpropertyvaluemotrum')),
            ],
        ),
    ]
