# Generated by Django 5.1.5 on 2025-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0163_remove_historicalproductproperty_is_diapason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertymotrumitem',
            name='property_value_motrum_to_diapason',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Значение для диапазона'),
        ),
    ]
