# Generated by Django 5.1.5 on 2025-07-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0164_productpropertymotrumitem_property_value_motrum_to_diapason'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertymotrumitem',
            name='is_have_vendor_props',
            field=models.BooleanField(default=False, verbose_name='Есть ли такая хорка в хорках поставщика'),
        ),
    ]
