# Generated by Django 5.1.5 on 2025-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0165_productpropertymotrumitem_is_have_vendor_props'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproductproperty',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Характеристика поставщика', 'verbose_name_plural': 'historical Характеристики поставщиков'},
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name': 'Характеристика поставщика', 'verbose_name_plural': 'Характеристики поставщиков'},
        ),
        migrations.AlterModelOptions(
            name='productpropertymotrumitem',
            options={'verbose_name': 'Характеристика мотрум', 'verbose_name_plural': 'Характеристики мотрум'},
        ),
        migrations.AddField(
            model_name='vendorpropertyandmotrum',
            name='property_value_motrum_to_diapason',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Значение для диапазона'),
        ),
    ]
