# Generated by Django 5.1.5 on 2025-07-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0166_alter_historicalproductproperty_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyItemAndMotrum',
        ),
    ]
