# Generated by Django 5.1.5 on 2025-07-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0167_delete_propertyitemandmotrum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpropertyandmotrum',
            name='property_value_motrum_to_diapason',
        ),
    ]
