# Generated by Django 5.1.5 on 2025-07-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0157_merge_20250701_1024'),
        ('product', '0168_remove_vendorpropertyandmotrum_property_value_motrum_to_diapason'),
    ]

    operations = [
    ]
