# Generated by Django 5.1.5 on 2025-07-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0168_remove_vendorpropertyandmotrum_property_value_motrum_to_diapason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpropertyandmotrum',
            name='is_category',
            field=models.BooleanField(default=False, verbose_name='Категория поставщика'),
        ),
    ]
