# Generated by Django 5.1.5 on 2025-07-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0169_vendorpropertyandmotrum_is_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertymotrum',
            name='name_to_slug',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название для слага'),
        ),
        migrations.AddField(
            model_name='productpropertymotrum',
            name='slug',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Название для слага'),
        ),
    ]
