# Generated by Django 5.1.5 on 2025-07-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0169_merge_20250708_1636'),
        ('product', '0170_productpropertymotrum_name_to_slug_and_more'),
    ]

    operations = [
    ]
