# Generated by Django 5.1.5 on 2025-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0170_productpropertymotrum_name_to_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='price_supplier',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена в каталоге поставщика в валюте каталога с НДС'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_supplier',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена в каталоге поставщика в валюте каталога с НДС'),
        ),
    ]
