# Generated by Django 5.1.5 on 2025-07-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0171_alter_historicalprice_price_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertyMotrumArticleCateg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.categoryproduct', verbose_name='Категория Мотрум')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.groupproduct', verbose_name='Группа Мотрум')),
                ('property_motrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productpropertymotrum')),
            ],
            options={
                'verbose_name': 'Очередность в группе Характеристика товара мотрум',
                'verbose_name_plural': 'Очередность в группе Характеристики товаров мотрум',
            },
        ),
    ]
