# Generated by Django 5.1.5 on 2025-07-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0171_alter_historicalprice_price_supplier_and_more'),
        ('product', '0171_merge_20250715_1340'),
    ]

    operations = [
    ]
