# Generated by Django 5.1.5 on 2025-07-23 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0172_productpropertymotrumarticlecateg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertymotrumarticlecateg',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproduct', verbose_name='Категория Мотрум'),
        ),
        migrations.AlterField(
            model_name='productpropertymotrumarticlecateg',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.groupproduct', verbose_name='Группа Мотрум'),
        ),
    ]
