# Generated by Django 5.1.5 on 2025-07-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_alter_historicalprice_price_motrum_and_more'),
        ('product', '0173_alter_productpropertymotrumarticlecateg_category_and_more'),
    ]

    operations = [
    ]
