# Generated by Django 5.1.5 on 2025-07-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0172_merge_20250715_1419'),
        ('product', '0174_merge_20250723_1413'),
    ]

    operations = [
    ]
