# Generated by Django 5.1.5 on 2025-07-25 06:28

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0174_merge_20250723_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='document',
            field=models.TextField(max_length=1000, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='document',
            field=models.FileField(max_length=1000, null=True, upload_to=apps.core.utils.get_file_path_add, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='Название документа'),
        ),
    ]
