# Generated by Django 5.1.5 on 2025-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0176_historicalcart_historicalproductcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductcart',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
    ]
