# Generated by Django 5.1.5 on 2025-07-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0175_alter_historicalproductdocument_document_and_more'),
        ('product', '0177_historicalproductcart_order_productcart_order'),
    ]

    operations = [
    ]
