# Generated by Django 5.1.5 on 2025-07-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0178_merge_20250730_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductdocument',
            name='link',
            field=models.CharField(max_length=2000, null=True, verbose_name='Ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='historicalproductimage',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='link',
            field=models.CharField(max_length=2000, null=True, verbose_name='Ссылка у поставщика'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Ссылка у поставщика'),
        ),
    ]
