# Generated by Django 5.1.5 on 2025-08-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0179_alter_historicalproductdocument_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertymotrumarticlecateg',
            name='is_view_in_category',
            field=models.BooleanField(default=True, verbose_name='Видимость в категории'),
        ),
    ]
