# Generated by Django 5.1.5 on 2025-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0179_alter_historicalproductdocument_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='id_lot_1c',
            field=models.CharField(max_length=100, null=True, verbose_name='ID 1C'),
        ),
    ]
