{
    "value": "ИП Зиладинова Лилия Ринатовна",
    "unrestricted_value": "ИП Зиладинова Лилия Ринатовна",
    "data": {
        "citizenship": null,
        "fio": {
            "surname": "Зиладинова",
            "name": "Лилия",
            "patronymic": "Ринатовна",
            "gender": null,
            "source": null,
            "qc": null,
        },
        "source": null,
        "qc": null,
        "hid": "26da0338ebdbe99a7013da679dd8f46b747039dc50ad89d4a6dcf4bd5f7e1d20",
        "type": "INDIVIDUAL",
        "state": {
            "status": "ACTIVE",
            "code": null,
            "actuality_date": 1739232000000,
            "registration_date": 1461542400000,
            "liquidation_date": null,
        },
        "opf": {
            "type": "2014",
            "code": "50102",
            "full": "Индивидуальный предприниматель",
            "short": "ИП",
        },
        "name": {
            "full_with_opf": "Индивидуальный предприниматель Зиладинова Лилия Ринатовна",
            "short_with_opf": "ИП Зиладинова Лилия Ринатовна",
            "latin": null,
            "full": "Зиладинова Лилия Ринатовна",
            "short": null,
        },
        "inn": "631625733376",
        "ogrn": "316631300101665",
        "okpo": "0102390282",
        "okato": "36401364000",
        "oktmo": "36701305000",
        "okogu": "4210015",
        "okfs": "16",
        "okved": "63.11.1",
        "okveds": null,
        "authorities": null,
        "documents": null,
        "licenses": null,
        "finance": null,
        "address": {
            "value": "г Самара",
            "unrestricted_value": "443000, Самарская обл, г Самара",
            "invalidity": null,
            "data": {
                "postal_code": "443000",
                "country": "Россия",
                "country_iso_code": "RU",
                "federal_district": "Приволжский",
                "region_fias_id": "df3d7359-afa9-4aaa-8ff9-197e73906b1c",
                "region_kladr_id": "6300000000000",
                "region_iso_code": "RU-SAM",
                "region_with_type": "Самарская обл",
                "region_type": "обл",
                "region_type_full": "область",
                "region": "Самарская",
                "area_fias_id": null,
                "area_kladr_id": null,
                "area_with_type": null,
                "area_type": null,
                "area_type_full": null,
                "area": null,
                "city_fias_id": "bb035cc3-1dc2-4627-9d25-a1bf2d4b936b",
                "city_kladr_id": "6300000100000",
                "city_with_type": "г Самара",
                "city_type": "г",
                "city_type_full": "город",
                "city": "Самара",
                "city_area": null,
                "city_district_fias_id": null,
                "city_district_kladr_id": null,
                "city_district_with_type": null,
                "city_district_type": null,
                "city_district_type_full": null,
                "city_district": null,
                "settlement_fias_id": null,
                "settlement_kladr_id": null,
                "settlement_with_type": null,
                "settlement_type": null,
                "settlement_type_full": null,
                "settlement": null,
                "street_fias_id": null,
                "street_kladr_id": null,
                "street_with_type": null,
                "street_type": null,
                "street_type_full": null,
                "street": null,
                "stead_fias_id": null,
                "stead_cadnum": null,
                "stead_type": null,
                "stead_type_full": null,
                "stead": null,
                "house_fias_id": null,
                "house_kladr_id": null,
                "house_cadnum": null,
                "house_flat_count": null,
                "house_type": null,
                "house_type_full": null,
                "house": null,
                "block_type": null,
                "block_type_full": null,
                "block": null,
                "entrance": null,
                "floor": null,
                "flat_fias_id": null,
                "flat_cadnum": null,
                "flat_type": null,
                "flat_type_full": null,
                "flat": null,
                "flat_area": null,
                "square_meter_price": null,
                "flat_price": null,
                "room_fias_id": null,
                "room_cadnum": null,
                "room_type": null,
                "room_type_full": null,
                "room": null,
                "postal_box": null,
                "fias_id": "bb035cc3-1dc2-4627-9d25-a1bf2d4b936b",
                "fias_code": "63000001000000000000000",
                "fias_level": "4",
                "fias_actuality_state": "0",
                "kladr_id": "6300000100000",
                "geoname_id": "499099",
                "capital_marker": "2",
                "okato": "36401000000",
                "oktmo": "36701000",
                "tax_office": "6300",
                "tax_office_legal": "6300",
                "timezone": "UTC+4",
                "geo_lat": "53.1950306",
                "geo_lon": "50.1069518",
                "beltway_hit": null,
                "beltway_distance": null,
                "metro": null,
                "divisions": null,
                "qc_geo": "4",
                "qc_complete": null,
                "qc_house": null,
                "history_values": null,
                "unparsed_parts": null,
                "source": "ОБЛАСТЬ САМАРСКАЯ, ГОРОД САМАРА",
                "qc": "0",
            },
        },
        "phones": null,
        "emails": null,
        "ogrn_date": 1461542400000,
        "okved_type": "2014",
        "employee_count": null,
    },
}
