# Generated by Django 5.1 on 2024-08-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0002_rename_requirements_vacancy_requirementsvacancy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirementsvacancy',
            options={'verbose_name': 'Требование к кандидату', 'verbose_name_plural': 'Требования к кандидату'},
        ),
        migrations.AlterModelOptions(
            name='responsibilities',
            options={'verbose_name': 'Обязанность кандидата', 'verbose_name_plural': 'Обязанности к кандидату'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='workingconditions',
            options={'verbose_name': 'Условия работы', 'verbose_name_plural': 'Условия работы'},
        ),
    ]
