# Generated by Django 5.1.5 on 2025-02-25 05:29

import apps.core.utils_web
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0003_alter_requirementsvacancy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEducationInfoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_company_web, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Фото блок обучение',
                'verbose_name_plural': 'Фото блок обучение',
            },
        ),
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('is_view', models.BooleanField(default=True, verbose_name='Видимость на сайте')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='text',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Мы предлагаем'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(max_length=200, null=True, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirement',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Что мы приветствуем'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibiliti',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Что нужно'),
        ),
        migrations.CreateModel(
            name='VacancyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_price', models.CharField(choices=[(1, 'от'), (2, 'до'), (3, 'без приставки')], default=3, max_length=100)),
                ('first', models.FloatField(blank=True, null=True, verbose_name='от')),
                ('last', models.FloatField(blank=True, null=True, verbose_name='до')),
                ('fixed', models.FloatField(blank=True, null=True, verbose_name='фиксированная сумма')),
                ('type_payments', models.CharField(max_length=500, verbose_name='Условия выплат')),
                ('Vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy_web.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
