# Generated by Django 5.1.5 on 2025-02-25 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0004_photoeducationinfoweb_vacancycategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyprice',
            name='Vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacancy_web.vacancy', verbose_name='Вакансия'),
        ),
    ]
