# Generated by Django 5.1.5 on 2025-02-25 06:35

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0006_alter_vacancycategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Общее описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='varsacancy_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy_web.vacancycategory', verbose_name='Сфера'),
        ),
    ]
