# Generated by Django 5.1.5 on 2025-02-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0007_vacancy_text_vacancy_varsacancy_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyprice',
            name='type_price',
        ),
    ]
