# Generated by Django 5.1.5 on 2025-02-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0009_vacancy_first_vacancy_fixed_vacancy_last_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='varsacancy_category',
            new_name='vacancy_category',
        ),
    ]
