# Generated by Django 5.1.5 on 2025-03-25 10:59

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0010_rename_varsacancy_category_vacancy_vacancy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSportsRecreationInfoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_company_web, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Фото блок спорт и отдых',
                'verbose_name_plural': 'Фото блок спорт и отдых',
            },
        ),
    ]
