# Generated by Django 5.1.5 on 2025-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0011_photosportsrecreationinfoweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoeducationinfoweb',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
        migrations.AddField(
            model_name='photosportsrecreationinfoweb',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
    ]
