# Generated by Django 5.1.5 on 2025-04-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_web', '0012_photoeducationinfoweb_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='type_payments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Условия выплат'),
        ),
    ]
