# Generated by Django 5.0.6 on 2024-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_text1_historicaltext1_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='text2',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='имя клиента'),
        ),
    ]
