# Generated by Django 5.0.6 on 2024-06-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_historicaltext1_history_change_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text2',
            name='testtest',
        ),
        migrations.DeleteModel(
            name='HistoricalText1',
        ),
        migrations.DeleteModel(
            name='Text1',
        ),
        migrations.DeleteModel(
            name='Text2',
        ),
    ]
