# Generated by Django 5.0.7 on 2024-08-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
