# Generated by Django 5.0.7 on 2024-08-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity', models.CharField(max_length=150, verbose_name='Юридическое лицо')),
                ('inn', models.PositiveIntegerField(verbose_name='ИНН')),
                ('kpp', models.PositiveIntegerField(verbose_name='КПП')),
                ('ogrn', models.PositiveIntegerField(verbose_name='ОГРН')),
                ('legal_post_code', models.PositiveIntegerField(verbose_name='Юридический адрес :индекс')),
                ('legal_city', models.CharField(max_length=50, verbose_name='Юридический адрес : город')),
                ('legal_address', models.CharField(max_length=200, verbose_name='Юридический адрес : адрес')),
                ('postal_post_code', models.PositiveIntegerField(verbose_name='Почтовый адрес :индекс')),
                ('postal_city', models.CharField(max_length=50, verbose_name='Почтовый адрес : город')),
                ('postal_address', models.CharField(max_length=200, verbose_name='Почтовый адрес : адрес')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='ClientDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(verbose_name='Процент скидки')),
                ('requisites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.requisites')),
            ],
        ),
        migrations.CreateModel(
            name='AccountRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_requisites', models.PositiveIntegerField(verbose_name='Расчётный счёт')),
                ('bank', models.CharField(max_length=200, verbose_name='Банк')),
                ('kpp', models.PositiveIntegerField(verbose_name='КПП')),
                ('bic', models.PositiveIntegerField(verbose_name='БИК')),
                ('requisites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.requisites')),
            ],
            options={
                'verbose_name': 'Расчётный счёт',
                'verbose_name_plural': 'Расчётные счёта',
            },
        ),
    ]
