# Generated by Django 5.0.7 on 2024-08-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_requisites_clientdiscount_accountrequisites'),
        ('specification', '0045_historicalspecification_date_update_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdiscount',
            options={'verbose_name': 'Скидка юрлица', 'verbose_name_plural': 'Скидки юрлиц'},
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='accountrequisites',
            name='requisites',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.requisites', verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clientdiscount',
            name='requisites',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.requisites', verbose_name='Юр.лицо'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(verbose_name='номер заказа')),
                ('status', models.CharField(choices=[('BASE', 'В обработке'), ('PRODUCT', 'Счёт на оплату'), ('CATALOG', 'Заказ у поставщика'), ('ALL', 'На доставке '), ('ALL', 'Готов к отгрузке самовывозом'), ('ALL', 'Отменен'), ('ALL', 'Заказ завершен')], default='ALL', max_length=100)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Клиент')),
                ('specification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='specification.specification', verbose_name='Спецификация')),
            ],
        ),
    ]
