# Generated by Django 5.1 on 2024-08-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_clientdiscount_options_client_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequisites',
            name='requisites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.requisites', verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=40, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент'),
        ),
    ]
