# Generated by Django 5.1 on 2024-08-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_accountrequisites_requisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='contract',
            field=models.CharField(max_length=50, null=True, verbose_name='Договор'),
        ),
    ]
