# Generated by Django 5.1 on 2024-08-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_accountrequisites_bic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequisites',
            name='account_requisites',
            field=models.CharField(max_length=30, verbose_name='Расчётный счёт'),
        ),
    ]
