# Generated by Django 5.1 on 2024-08-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_client_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент скидки'),
        ),
        migrations.DeleteModel(
            name='ClientDiscount',
        ),
    ]
