# Generated by Django 5.1 on 2024-08-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_client_percent_delete_clientdiscount'),
        ('product', '0111_historicalproduct_promote_product_promote'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_cart', models.BooleanField(default=False, verbose_name='корзина сохранена')),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Клиент')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='количество товара')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Корзина продукт',
                'verbose_name_plural': 'Корзина Продукты',
            },
        ),
    ]
