# Generated by Django 5.1 on 2024-08-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_cart_productcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session',
            new_name='session_client',
        ),
    ]
