# Generated by Django 5.1 on 2024-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_remove_productcart_cart_remove_productcart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке '), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='PROCESSING', max_length=100),
        ),
    ]
