# Generated by Django 5.1 on 2024-08-22 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_alter_order_status'),
        ('specification', '0047_remove_historicalspecification_currency_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.accountrequisites', verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='order',
            name='requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.requisites', verbose_name='Реквизиты заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='specification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='specification.specification', verbose_name='Спецификация'),
        ),
    ]
