# Generated by Django 5.1 on 2024-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_order_account_requisites_order_requisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequisites',
            name='kpp',
            field=models.CharField(max_length=20, verbose_name='Корреспондентский счет (к/с)'),
        ),
    ]
