# Generated by Django 5.1 on 2024-08-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_alter_accountrequisites_kpp'),
        ('product', '0113_rename_save_cart_cart_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account_requisites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.accountrequisites', verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requisites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.requisites', verbose_name='Реквизиты заказа'),
        ),
    ]
