# Generated by Django 5.1 on 2024-08-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_order_cart_alter_order_account_requisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.accountrequisites', verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.requisites', verbose_name='Реквизиты заказа'),
        ),
    ]
