# Generated by Django 5.1 on 2024-09-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_alter_order_account_requisites_alter_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Клиент'),
        ),
    ]
