# Generated by Django 5.1 on 2024-09-12 08:53

import apps.specification.utils
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_alter_order_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='bill_date_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания счета'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_date_stop',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания счета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='bill_file',
            field=models.FileField(default=None, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил счета'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_sum',
            field=models.FloatField(default=None, null=True, verbose_name='Сумма счета'),
        ),
    ]
