# Generated by Django 5.1 on 2024-09-12 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_alter_order_options_order_bill_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_date_start',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата создания счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_date_stop',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма счета'),
        ),
    ]
