# Generated by Django 5.1.1 on 2024-09-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_order_date_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_sum_paid',
            field=models.FloatField(blank=True, null=True, verbose_name='Оплаченная сумма'),
        ),
    ]
