# Generated by Django 5.1.1 on 2024-09-16 11:42

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0035_order_bill_sum_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='act_file',
            field=models.FileField(default=None, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил акта поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_sum_paid',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Оплаченная сумма'),
        ),
    ]
