# Generated by Django 5.1.1 on 2024-09-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания счета'),
        ),
    ]
