# Generated by Django 5.1.1 on 2024-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_alter_order_bill_date_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsCallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=40, verbose_name='Номер телефона')),
            ],
        ),
    ]
