# Generated by Django 5.1.1 on 2024-10-09 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_emailscallback'),
        ('product', '0120_alter_productcart_cart'),
        ('specification', '0059_alter_productspecification_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='specification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specification.specification', verbose_name='Спецификация'),
        ),
    ]
