# Generated by Django 5.1.1 on 2024-10-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_alter_requisites_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='postpay_persent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент постоплаты'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='prepay_persent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент предоплаты'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='type_delivery',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='type_payment',
            field=models.CharField(choices=[('100% prepay', '100% предоплата'), ('payment in installments', 'Оплата частями'), ('100% postpay', '100% постоплата')], default='100% prepay', max_length=100, verbose_name='Тип оплаты'),
        ),
    ]
