# Generated by Django 5.1.1 on 2024-10-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0042_requisites_discount_requisites_postpay_persent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
    ]
