# Generated by Django 5.1.1 on 2024-10-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0043_alter_requisites_client_alter_requisites_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_name',
            field=models.CharField(default=3042, max_length=1000),
        ),
    ]
