# Generated by Django 5.1.1 on 2024-10-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0044_order_bill_name'),
        ('core', '0019_alter_baseinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='motrum_requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.baseinfoaccountrequisites', verbose_name='Реквизиты мотрум для сделки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=8724, max_length=1000, null=True),
        ),
    ]
