# Generated by Django 5.1.1 on 2024-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_order_motrum_requisites_alter_order_bill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=4319, max_length=1000, null=True),
        ),
    ]
