# Generated by Django 5.1.1 on 2024-10-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0046_alter_order_bill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_bitrix',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер сделки битрикс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=864, max_length=1000, null=True),
        ),
    ]
