# Generated by Django 5.1.1 on 2024-10-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0050_alter_order_bill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='tel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=8749, max_length=1000, null=True),
        ),
    ]
