# Generated by Django 5.1.1 on 2024-10-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0052_order_postpay_persent_order_prepay_persent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=4576, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
