# Generated by Django 5.1.1 on 2024-10-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0053_order_date_update_alter_order_bill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='phone',
            field=models.CharField(max_length=40, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=6756, max_length=1000, null=True),
        ),
    ]
