# Generated by Django 5.1.1 on 2024-10-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0058_alter_order_bill_name_historicalorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=8975, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
    ]
