# Generated by Django 5.1.2 on 2024-10-25 10:10

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0064_remove_requisites_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_file',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_name',
            field=models.CharField(blank=True, default=8319, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=8319, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='postpay_persent',
            field=models.FloatField(blank=True, default='0', null=True, verbose_name='Процент постоплаты'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='prepay_persent',
            field=models.FloatField(blank=True, default='100', null=True, verbose_name='Процент предоплаты'),
        ),
    ]
