# Generated by Django 5.1.2 on 2024-10-28 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0067_alter_historicalorder_bill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='date_completed',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_completed',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_name',
            field=models.CharField(blank=True, default=9653, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=9653, max_length=1000, null=True),
        ),
    ]
