# Generated by Django 5.1.2 on 2024-10-28 07:51

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0069_alter_historicalorder_bill_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_completed',
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_name',
            field=models.CharField(blank=True, default=621, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('', '----'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке '), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='PROCESSING', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=621, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('', '----'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке '), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='PROCESSING', max_length=100),
        ),
    ]
