# Generated by Django 5.1.2 on 2024-10-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0070_remove_historicalorder_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='date_completed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_completed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_name',
            field=models.CharField(blank=True, default=4728, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=4728, max_length=1000, null=True),
        ),
    ]
