# Generated by Django 5.1.2 on 2024-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0072_alter_historicalorder_bill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_name',
            field=models.CharField(blank=True, default=6428, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=6428, max_length=1000, null=True),
        ),
    ]
