# Generated by Django 5.1.2 on 2024-10-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0090_alter_historicalorder_bill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='type_delivery',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_delivery',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_name',
            field=models.CharField(blank=True, default=651, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name',
            field=models.CharField(blank=True, default=651, max_length=1000, null=True),
        ),
    ]
