# Generated by Django 5.1.2 on 2024-11-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0097_alter_historicalorder_bill_name_and_more'),
    ]

    operations = [

    ]
