# Generated by Django 5.1.2 on 2024-11-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0098_alter_historicalorder_bill_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='bill_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_name',
        ),
    ]
