# Generated by Django 5.1.2 on 2024-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0099_remove_historicalorder_bill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='bill_name',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Номер сделки битрикс'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_name',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Номер сделки битрикс'),
        ),
    ]
