# Generated by Django 5.1.2 on 2024-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0101_alter_historicalorder_bill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='tag_stop',
            field=models.BooleanField(default=True, verbose_name='Действительно'),
        ),
        migrations.AddField(
            model_name='order',
            name='tag_stop',
            field=models.BooleanField(default=True, verbose_name='Действительно'),
        ),
    ]
