# Generated by Django 5.1.2 on 2024-11-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0102_historicalorder_tag_stop_order_tag_stop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='tag_stop',
            new_name='bill_tag_stop',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tag_stop',
            new_name='bill_tag_stop',
        ),
    ]
