# Generated by Django 5.1.2 on 2024-11-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0103_rename_tag_stop_historicalorder_bill_tag_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='id_bitrix',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер клиента битрикс'),
        ),
    ]
