# Generated by Django 5.1.2 on 2024-11-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0104_requisites_id_bitrix'),
        ('user', '0011_adminuser_bitrix_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.adminuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.adminuser'),
        ),
        migrations.CreateModel(
            name='RequisitesOtherKpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpp', models.CharField(max_length=10, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('legal_post_code', models.PositiveIntegerField(verbose_name='Юридический адрес :индекс')),
                ('legal_city', models.CharField(max_length=50, verbose_name='Юридический адрес : город')),
                ('legal_address', models.CharField(max_length=200, verbose_name='Юридический адрес : адрес')),
                ('postal_post_code', models.CharField(max_length=10, verbose_name='Почтовый адрес :индекс')),
                ('postal_city', models.CharField(max_length=50, verbose_name='Почтовый адрес : город')),
                ('postal_address', models.CharField(max_length=200, verbose_name='Почтовый адрес : адрес')),
                ('tel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('requisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.requisites', verbose_name='Реквизиты')),
            ],
        ),
    ]
