# Generated by Django 5.1.2 on 2024-11-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0105_historicalorder_manager_order_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='number_spec',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер спецификации клиента'),
        ),
    ]
