# Generated by Django 5.1.2 on 2024-11-25 12:17

import apps.specification.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0107_requisites_contract_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocumentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('bill_name', models.PositiveIntegerField(default=None, null=True, verbose_name='Номер счета')),
                ('bill_file', models.FileField(blank=True, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил счета')),
                ('bill_date_start', models.DateField(blank=True, null=True, verbose_name='Дата создания счета')),
                ('bill_date_stop', models.DateField(blank=True, null=True, verbose_name='Дата окончания счета')),
                ('bill_sum', models.FloatField(blank=True, null=True, verbose_name='Сумма счета')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.order', verbose_name='Заказ')),
            ],
        ),
    ]
