# Generated by Django 5.1.2 on 2024-11-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0109_historicalorder_bill_file_no_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocumentbill',
            name='bill_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='orderdocumentbill',
            name='bill_file_no_signature',
            field=models.FileField(null=True, upload_to='', verbose_name='Фаил счета без печатей'),
        ),
    ]
