# Generated by Django 5.1.2 on 2024-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0110_alter_orderdocumentbill_bill_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdocumentbill',
            name='version',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Версия в одну дату'),
        ),
    ]
