# Generated by Django 5.1.2 on 2024-12-02 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0112_alter_orderdocumentbill_bill_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisites',
            options={'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),
        migrations.RemoveField(
            model_name='accountrequisites',
            name='requisites',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='legal_city',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='legal_post_code',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='ogrn',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='postal_city',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='postal_post_code',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='type_delivery',
        ),
        migrations.AddField(
            model_name='accountrequisites',
            name='requisitesKpp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.requisitesotherkpp', verbose_name='Реквизиты'),
            preserve_default=False,
        ),
    ]
