# Generated by Django 5.1.2 on 2024-12-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0113_alter_requisites_options_and_more'),
        ('core', '0027_alter_typedelivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='type_delivery_motrum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.typedelivery', verbose_name='Тип доставки '),
        ),
        migrations.AddField(
            model_name='order',
            name='type_delivery_motrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.typedelivery', verbose_name='Тип доставки '),
        ),
    ]
