# Generated by Django 5.1.2 on 2024-12-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0114_historicalorder_type_delivery_motrum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='type_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_delivery',
        ),
    ]
