# Generated by Django 5.1.2 on 2024-12-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0115_remove_historicalorder_type_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='type_delivery_motrum',
            new_name='type_delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='type_delivery_motrum',
            new_name='type_delivery',
        ),
    ]
