# Generated by Django 5.1.2 on 2024-12-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0116_rename_type_delivery_motrum_historicalorder_type_delivery_and_more'),
        ('core', '0027_alter_typedelivery_options_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalorder',
        #     name='motrum_requisites',
        # ),
        # migrations.RemoveField(
        #     model_name='order',
        #     name='motrum_requisites',
        # ),
        migrations.AddField(
            model_name='historicalorder',
            name='motrum_requisites1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.baseinfoaccountrequisites', verbose_name='Реквизиты мотрум для сделки'),
        ),
        migrations.AddField(
            model_name='order',
            name='motrum_requisites1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.baseinfoaccountrequisites', verbose_name='Реквизиты мотрум для сделки'),
        ),
    ]
