# Generated by Django 5.1.2 on 2024-12-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0120_remove_historicalorder_motrum_requisites_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalorder',
        #     name='motrum_requisites',
        # ),
        # migrations.RemoveField(
        #     model_name='order',
        #     name='motrum_requisites',
        # ),
    ]
