# Generated by Django 5.1.2 on 2024-12-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0123_historicalorder_motrum_requisites123_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='motrum_requisites123',
            new_name='motrum_requisites12',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='motrum_requisites123',
            new_name='motrum_requisites12',
        ),
        # migrations.RemoveField(
        #     model_name='historicalorder',
        #     name='motrum_requisites',
        # ),
        # migrations.RemoveField(
        #     model_name='order',
        #     name='motrum_requisites',
        # ),
    ]
