# Generated by Django 5.1.2 on 2024-12-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0127_alter_historicalorder_motrum_requisites_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
    ]
