# Generated by Django 5.1.4 on 2024-12-12 12:12

import apps.specification.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0131_alter_requisites_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил счета')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.order', verbose_name='Заказ')),
            ],
        ),
    ]
