# Generated by Django 5.1.4 on 2024-12-13 12:34

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0132_documentshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentshipment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.specification.utils.get_shipment_doc_path, verbose_name='Фаил счета'),
        ),
    ]
