# Generated by Django 5.1.4 on 2024-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0134_historicalorder_bill_id_bx_order_bill_id_bx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsAllWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=40, verbose_name='Номер телефона')),
            ],
        ),
    ]
