# Generated by Django 5.1.4 on 2024-12-25 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0135_emailsallweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitesAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.PositiveIntegerField(verbose_name='Страна')),
                ('post_code', models.PositiveIntegerField(verbose_name='Индекс')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('province', models.CharField(max_length=50, verbose_name='Область')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address1', models.CharField(max_length=200, verbose_name='Адрес')),
                ('address2', models.CharField(max_length=200, verbose_name='Дом')),
                ('requisitesKpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.requisitesotherkpp', verbose_name='Реквизиты')),
            ],
        ),
    ]
