# Generated by Django 5.1.4 on 2025-01-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0138_historicaldocumentshipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymenttransaction',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpaymenttransaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='HistoricalDocumentShipment',
        ),
        migrations.DeleteModel(
            name='HistoricalPaymentTransaction',
        ),
    ]
