# Generated by Django 5.1.4 on 2025-01-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0139_remove_historicalpaymenttransaction_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitesaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Регион'),
        ),
    ]
