# Generated by Django 5.1.4 on 2025-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0140_alter_requisitesaddress_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='text_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
