# Generated by Django 5.1.4 on 2025-01-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0141_historicalorder_text_name_order_text_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitesotherkpp',
            name='kpp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='КПП'),
        ),
    ]
