# Generated by Django 5.1.4 on 2025-01-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0142_alter_requisitesotherkpp_kpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='type_client',
            field=models.CharField(choices=[('1', 'Юридическое лицо'), ('2', 'ИП')], default='1', max_length=100, verbose_name='Тип клиента'),
        ),
    ]
