# Generated by Django 5.1.4 on 2025-01-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0143_requisites_type_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='type_client',
            field=models.CharField(choices=[('1', 'Юридическое лицо'), ('2', 'ИП'), ('3', 'Физ. лицо')], default='1', max_length=100, verbose_name='Тип клиента'),
        ),
    ]
