# Generated by Django 5.1.4 on 2025-01-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0144_alter_requisites_type_client'),
        ('user', '0012_alter_adminuser_bitrix_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.adminuser'),
        ),
    ]
