# Generated by Django 5.1.4 on 2025-01-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0145_requisites_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdocumentbill',
            name='from_index',
            field=models.CharField(choices=[('-', 'Неизвестно'), ('Б', 'битрикс')], default='-', max_length=100),
        ),
    ]
