# Generated by Django 5.1.4 on 2025-01-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0146_orderdocumentbill_from_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdocumentbill',
            name='text_name_bill',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Текстовое название'),
        ),
        migrations.AddField(
            model_name='orderdocumentbill',
            name='text_name_bill_no_sign',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Текстовое название без подписи'),
        ),
    ]
