# Generated by Django 5.1.5 on 2025-01-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0147_orderdocumentbill_text_name_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='contract',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='requisitesotherkpp',
            name='legal_city',
            field=models.CharField(max_length=200, verbose_name='Юридический адрес : город'),
        ),
        migrations.AlterField(
            model_name='requisitesotherkpp',
            name='postal_city',
            field=models.CharField(max_length=200, verbose_name='Почтовый адрес : город'),
        ),
        migrations.AlterField(
            model_name='requisitesotherkpp',
            name='postal_post_code',
            field=models.CharField(max_length=150, verbose_name='Почтовый адрес :индекс'),
        ),
    ]
