# Generated by Django 5.1.5 on 2025-02-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0148_alter_requisites_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент сайта', 'verbose_name_plural': 'Клиенты на сайте'},
        ),
    ]
