# Generated by Django 5.1.5 on 2025-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0149_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='client',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='type_client',
            field=models.CharField(choices=[('1', 'Юридическое лицо'), ('2', 'ИП'), ('3', 'Физ. лицо'), ('4', 'Организация (доп.)')], default='1', max_length=100, verbose_name='Тип клиента'),
        ),
    ]
