# Generated by Django 5.1.5 on 2025-02-13 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0150_client_middle_name_client_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40, verbose_name='Номер телефона')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент')),
            ],
        ),
    ]
