# Generated by Django 5.1.5 on 2025-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0152_clientrequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitesaddress',
            name='type_address_bx',
            field=models.CharField(choices=[(1, 'Фактический адрес'), (4, 'Адрес регистрации'), (6, 'Юридический адрес'), (9, 'Адрес бенефициара'), ('web-lk-adress', 'Юридический адрес сайт')], default=6, max_length=100),
        ),
    ]
