# Generated by Django 5.1.5 on 2025-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0153_alter_requisitesaddress_type_address_bx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='id_bitrix',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='Номер сделки битрикс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_bitrix',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Номер сделки битрикс'),
        ),
    ]
