# Generated by Django 5.1.5 on 2025-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0154_alter_historicalorder_id_bitrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='id_bitrix',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер сделки битрикс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_bitrix',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер сделки битрикс'),
        ),
    ]
