# Generated by Django 5.1.5 on 2025-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0157_alter_historicalorder_id_bitrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='name',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='номер заказа'),
        ),
    ]
