# Generated by Django 5.1.5 on 2025-02-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0158_alter_historicalorder_name_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя ИП'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия ИП'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество ИП'),
        ),
    ]
