# Generated by Django 5.1.5 on 2025-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0159_requisites_first_name_requisites_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitesotherkpp',
            name='id_bitrix',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер клиента битрикс'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='type_client',
            field=models.CharField(choices=[('1', 'Юридическое лицо'), ('3', 'ИП'), ('5', 'Физ. лицо')], default='1', max_length=100, verbose_name='Тип клиента'),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='type_address_bx',
            field=models.CharField(choices=[(1, 'Фактический адрес'), (4, 'Адрес регистрации'), (6, 'Юридический адрес'), (8, 'Адрес для корреспонденции'), (9, 'Адрес бенефициара'), (11, 'Адрес доставки'), ('web-lk-adress', 'Юридический адрес сайт')], default=6, max_length=100),
        ),
    ]
