# Generated by Django 5.1.5 on 2025-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0160_requisitesotherkpp_id_bitrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitesaddress',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Область'),
        ),
    ]
