# Generated by Django 5.1.5 on 2025-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0161_alter_requisitesaddress_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='id_bitrix',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id реквизита в битрикс'),
        ),
    ]
