# Generated by Django 5.1.5 on 2025-02-27 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0162_alter_requisites_id_bitrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='adress_document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.requisitesaddress', verbose_name='Адрес для документов'),
        ),
        migrations.AddField(
            model_name='order',
            name='adress_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.requisitesaddress', verbose_name='Адрес для документов'),
        ),
    ]
