# Generated by Django 5.1.5 on 2025-03-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0163_historicalorder_adress_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentshipment',
            name='name',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='номер'),
        ),
    ]
