# Generated by Django 5.1.5 on 2025-03-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0164_documentshipment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitesaddress',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
    ]
