# Generated by Django 5.1.5 on 2025-03-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0165_requisitesaddress_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitesaddress',
            name='email',
        ),
        migrations.AddField(
            model_name='requisitesotherkpp',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
    ]
