# Generated by Django 5.1.5 on 2025-03-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0166_remove_requisitesaddress_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bitrix_id_client',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер  битрикс'),
        ),
    ]
