# Generated by Django 5.1.5 on 2025-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0167_client_bitrix_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentshipment',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='номер'),
        ),
    ]
