# Generated by Django 5.1.5 on 2025-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0168_alter_documentshipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='contract',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='id_bitrix',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Id реквизита в битрикс'),
        ),
    ]
