# Generated by Django 5.1.5 on 2025-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0169_alter_requisites_contract_alter_requisites_id_bitrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('', '----'), ('PRE-PROCESSING', 'В обработке'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке'), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='PRE-PROCESSING', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('', '----'), ('PRE-PROCESSING', 'В обработке'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке'), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='PRE-PROCESSING', max_length=100),
        ),
    ]
