# Generated by Django 5.1.5 on 2025-03-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0171_alter_accountrequisites_requisiteskpp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocumentbill',
            name='from_index',
            field=models.CharField(choices=[('-', 'Неизвестно'), ('Б', 'битрикс')], default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='requisitesaddress',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Страна'),
        ),
    ]
