# Generated by Django 5.1.5 on 2025-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0172_alter_orderdocumentbill_from_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitesotherkpp',
            name='legal_address',
            field=models.CharField(max_length=1000, verbose_name='Юридический адрес : адрес'),
        ),
        migrations.AlterField(
            model_name='requisitesotherkpp',
            name='legal_city',
            field=models.CharField(max_length=1000, verbose_name='Юридический адрес : город'),
        ),
        migrations.AlterField(
            model_name='requisitesotherkpp',
            name='postal_address',
            field=models.CharField(max_length=1000, verbose_name='Почтовый адрес : адрес'),
        ),
        migrations.AlterField(
            model_name='requisitesotherkpp',
            name='postal_city',
            field=models.CharField(max_length=1000, verbose_name='Почтовый адрес : город'),
        ),
    ]
