# Generated by Django 5.1.5 on 2025-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0173_alter_requisitesotherkpp_legal_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='marginality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Маржинальность заказа в %'),
        ),
        migrations.AddField(
            model_name='order',
            name='marginality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Маржинальность заказа в %'),
        ),
    ]
