# Generated by Django 5.1.5 on 2025-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0174_historicalorder_marginality_order_marginality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='marginality',
            field=models.FloatField(blank=True, null=True, verbose_name='Маржинальность заказа в %'),
        ),
        migrations.AlterField(
            model_name='order',
            name='marginality',
            field=models.FloatField(blank=True, null=True, verbose_name='Маржинальность заказа в %'),
        ),
    ]
