# Generated by Django 5.1.5 on 2025-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0175_alter_historicalorder_marginality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='bill_name_prefix',
            field=models.CharField(choices=[('', '----'), ('PRE-PROCESSING', 'В обработке'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке'), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='ОКТ', max_length=100, verbose_name='Префикс номера счета'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_name_prefix',
            field=models.CharField(choices=[('', '----'), ('PRE-PROCESSING', 'В обработке'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке'), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='ОКТ', max_length=100, verbose_name='Префикс номера счета'),
        ),
        migrations.AddField(
            model_name='orderdocumentbill',
            name='bill_name_prefix',
            field=models.CharField(choices=[('', '----'), ('PRE-PROCESSING', 'В обработке'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке'), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='ОКТ', max_length=100, verbose_name='Префикс номера счета'),
        ),
    ]
