# Generated by Django 5.1.5 on 2025-07-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0175_alter_historicalorder_marginality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitesotherkpp',
            options={'verbose_name': 'Реквизиты и данные', 'verbose_name_plural': 'Реквизиты и данные'},
        ),
    ]
