# Generated by Django 5.1.5 on 2025-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0175_alter_historicalorder_marginality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='postpay_persent_text',
            field=models.CharField(blank=True, default='в течении 5 дней с момента отгрузки со склада Поставщика', max_length=1000, null=True, verbose_name='Текст после процента постоплаты'),
        ),
    ]
