# Generated by Django 5.1.5 on 2025-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0176_alter_requisitesotherkpp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='marginality_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Маржинальность заказа в рублях'),
        ),
        migrations.AddField(
            model_name='order',
            name='marginality_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Маржинальность заказа в рублях'),
        ),
    ]
