# Generated by Django 5.1.5 on 2025-07-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0176_historicalorder_bill_name_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('ИМ', 'ИМ'), ('ОКТ', 'ОКТ')], default='PRE-PROCESSING', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ИМ', 'ИМ'), ('ОКТ', 'ОКТ')], default='PRE-PROCESSING', max_length=100),
        ),
    ]
