# Generated by Django 5.1.5 on 2025-08-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0177_historicalorder_marginality_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='postpay_persent_2',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Процент постоплаты 2'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='postpay_persent_3',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Процент постоплаты 3'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='prepay_persent_text',
            field=models.CharField(blank=True, default='в течение 5 дней с момента отгрузки со склада Поставщика.', max_length=200, null=True, verbose_name='Процент постоплаты текст'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='prepay_persent_text_2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Процент предоплаты текст 2'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='prepay_persent_text_3',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Процент предоплаты текст 3'),
        ),
    ]
