# Generated by Django 5.1.5 on 2025-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0177_alter_historicalorder_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_name_prefix',
            field=models.CharField(choices=[('ИМ', 'ИМ'), ('ОКТ', 'ОКТ')], default='ОКТ', max_length=100, verbose_name='Префикс номера счета'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('', '----'), ('PRE-PROCESSING', 'В обработке'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке'), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='PRE-PROCESSING', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name_prefix',
            field=models.CharField(choices=[('ИМ', 'ИМ'), ('ОКТ', 'ОКТ')], default='ОКТ', max_length=100, verbose_name='Префикс номера счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('', '----'), ('PRE-PROCESSING', 'В обработке'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке'), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='PRE-PROCESSING', max_length=100),
        ),
    ]
