# Generated by Django 5.1.5 on 2025-08-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0178_requisites_postpay_persent_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisites',
            old_name='prepay_persent_text',
            new_name='postpay_persent_text',
        ),
        migrations.RenameField(
            model_name='requisites',
            old_name='prepay_persent_text_2',
            new_name='postpay_persent_text_2',
        ),
        migrations.RenameField(
            model_name='requisites',
            old_name='prepay_persent_text_3',
            new_name='postpay_persent_text_3',
        ),
    ]
