# Generated by Django 5.1.5 on 2025-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0178_alter_historicalorder_bill_name_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_name_prefix',
            field=models.CharField(blank=True, choices=[('ИМ', 'ИМ'), ('ОКТ', 'ОКТ')], default='ОКТ', max_length=100, null=True, verbose_name='Префикс номера счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_name_prefix',
            field=models.CharField(blank=True, choices=[('ИМ', 'ИМ'), ('ОКТ', 'ОКТ')], default='ОКТ', max_length=100, null=True, verbose_name='Префикс номера счета'),
        ),
        migrations.AlterField(
            model_name='orderdocumentbill',
            name='bill_name_prefix',
            field=models.CharField(blank=True, choices=[('', '----'), ('PRE-PROCESSING', 'В обработке'), ('PROCESSING', 'В обработке'), ('PAYMENT', 'Счёт на оплату'), ('IN_MOTRUM', 'Заказ у поставщика'), ('SHIPMENT_AUTO', 'На доставке'), ('SHIPMENT_PICKUP', 'Готов к отгрузке самовывозом'), ('CANCELED', 'Отменен'), ('COMPLETED', 'Заказ завершен')], default='ОКТ', max_length=100, null=True, verbose_name='Префикс номера счета'),
        ),
    ]
