# Generated by Django 5.1.5 on 2025-07-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0176_alter_requisitesotherkpp_options'),
        ('client', '0179_alter_historicalorder_bill_name_prefix_and_more'),
    ]

    operations = [
    ]
