# Generated by Django 5.1.5 on 2025-08-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0177_historicalorder_marginality_sum_and_more'),
        ('client', '0180_merge_20250730_0902'),
    ]

    operations = [
    ]
