# Generated by Django 5.1.5 on 2025-08-19 10:13

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0181_merge_20250814_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentshipment',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=apps.specification.utils.get_shipment_doc_path, verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='act_file',
            field=models.TextField(default=None, max_length=1000, null=True, verbose_name='Фаил акта поставки'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_file',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='bill_file_no_signature',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Фаил счета без печатей'),
        ),
        migrations.AlterField(
            model_name='order',
            name='act_file',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил акта поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_file_no_signature',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=apps.specification.utils.get_document_bill_path, verbose_name='Фаил счета без печатей'),
        ),
        migrations.AlterField(
            model_name='orderdocumentbill',
            name='bill_file',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='', verbose_name='Фаил счета'),
        ),
        migrations.AlterField(
            model_name='orderdocumentbill',
            name='bill_file_no_signature',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='', verbose_name='Фаил счета без печатей'),
        ),
    ]
