# Generated by Django 5.1.5 on 2025-08-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0179_rename_prepay_persent_text_requisites_postpay_persent_text_and_more'),
        ('client', '0181_merge_20250814_0946'),
    ]

    operations = [
    ]
