# Generated by Django 5.1.5 on 2025-08-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0182_alter_documentshipment_file_and_more'),
        ('client', '0182_merge_20250819_1007'),
    ]

    operations = [
    ]
