# Generated by Django 5.1.5 on 2025-08-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0183_merge_20250825_1254'),
        ('client', '0183_merge_20250825_1452'),
    ]

    operations = [
    ]
