# Generated by Django 5.1.5 on 2025-08-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0183_merge_20250825_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitesotherkpp',
            name='physical_address',
            field=models.CharField(max_length=1000, null=True, verbose_name='Физический адрес : адрес'),
        ),
        migrations.AddField(
            model_name='requisitesotherkpp',
            name='physical_city',
            field=models.CharField(max_length=1000, null=True, verbose_name='Физический адрес : город'),
        ),
        migrations.AddField(
            model_name='requisitesotherkpp',
            name='physical_post_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Физический адрес :индекс'),
        ),
    ]
