from django.test import TestCase

# Create your tests here.
{
    "ID": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "ID",
    },
    "OWNER_ID": {
        "type": "integer",
        "isRequired": True,
        "isReadOnly": False,
        "isImmutable": True,
        "isMultiple": False,
        "isDynamic": False,
        "title": "ID владельца",
    },
    "OWNER_TYPE": {
        "type": "string",
        "isRequired": True,
        "isReadOnly": False,
        "isImmutable": True,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Тип владельца",
    },
    "PRODUCT_ID": {
        "type": "integer",
        "isRequired": True,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Товар",
    },
    "PRODUCT_NAME": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Название товара",
    },
    "PRICE": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Цена",
    },
    "PRICE_EXCLUSIVE": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Цена без налога со скидкой",
    },
    "PRICE_NETTO": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "PRICE_NETTO",
    },
    "PRICE_BRUTTO": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "PRICE_BRUTTO",
    },
    "QUANTITY": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Количество",
    },
    "DISCOUNT_TYPE_ID": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Тип скидки",
    },
    "DISCOUNT_RATE": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Величина скидки",
    },
    "DISCOUNT_SUM": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Сумма скидки",
    },
    "TAX_RATE": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Налог",
    },
    "TAX_INCLUDED": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Налог включен в цену",
    },
    "CUSTOMIZED": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Изменен",
    },
    "MEASURE_CODE": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Код единицы измерения",
    },
    "MEASURE_NAME": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Единица измерения",
    },
    "SORT": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Сортировка",
    },
    "TYPE": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "TYPE",
    },
}
