# Generated by Django 5.0.6 on 2024-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_adminuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='admin_type',
            field=models.CharField(choices=[('BASE', 'Базовый доступ'), ('PRODUCT', 'Доступ администрирования товаров'), ('CATALOG', 'Доступ для загрузки каталогов поставщиков'), ('ALL', 'Полный доступ')], default='BASE', max_length=100),
        ),
    ]
