# Generated by Django 5.0.6 on 2024-06-05 05:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0003_adminuser_admin_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
            ],
            options={
                'verbose_name': 'Roles',
                'verbose_name_plural': 'Roles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
