# Generated by Django 5.0.6 on 2024-06-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='middle_name',
        ),
    ]
