# Generated by Django 5.0.6 on 2024-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_roles_options_remove_adminuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='admin_type',
            field=models.CharField(choices=[('BASE', 'Базовый доступ'), ('PRODUCT', 'Доступ администрирования товаров'), ('CATALOG', 'Доступ для загрузки каталогов поставщиков'), ('ALL', 'Полный доступ')], default='ALL', max_length=100),
        ),
    ]
