# Generated by Django 5.0.7 on 2024-08-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
