# Generated by Django 5.1.1 on 2024-10-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
    ]
