# Generated by Django 5.1.2 on 2024-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_adminuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='bitrix_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер менеджера битрикс'),
        ),
    ]
