# Generated by Django 5.1.4 on 2025-01-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_adminuser_bitrix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='admin_type',
            field=models.CharField(choices=[('BASE', 'Базовый доступ'), ('PRODUCT', 'Доступ администрирования товаров'), ('CATALOG', 'Доступ для загрузки каталогов поставщиков'), ('ALL', 'Полный доступ')], default='ALL', max_length=100, verbose_name='Уровень доступа'),
        ),
    ]
