# Generated by Django 5.1.5 on 2025-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_adminuser_admin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
