# Generated by Django 5.1.5 on 2025-02-28 05:36

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_adminuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_company_web, verbose_name='Картинка'),
        ),
    ]
