# Generated by Django 5.1.5 on 2025-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_adminuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='bitrix_id_client',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер менеджера битрикс'),
        ),
    ]
