# Generated by Django 5.1.5 on 2025-03-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_adminuser_bitrix_id_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='bitrix_id_client',
        ),
    ]
