# Generated by Django 5.1.5 on 2025-03-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_adminuser_bitrix_id_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(max_length=40, null=True, verbose_name='Номер телефона'),
        ),
    ]
