# Generated by Django 5.1.5 on 2025-03-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_adminuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер телефона в формате 79277777777 - без плюса и доп знаков'),
        ),
    ]
