# Generated by Django 5.0.5 on 2024-05-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название валюты')),
                ('words_code', models.CharField(max_length=30, verbose_name='Букв. код')),
                ('code', models.SmallIntegerField(verbose_name='Цифр. код')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(verbose_name='процент ндс')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
