# Generated by Django 5.0.6 on 2024-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currencypercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypercent',
            name='percent',
            field=models.FloatField(verbose_name='Процент умножения валютных цен'),
        ),
    ]
