# Generated by Django 5.0.7 on 2024-07-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_currencypercent_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30, verbose_name='Год')),
                ('json_date', models.JSONField()),
            ],
            options={
                'verbose_name': 'Даты выходных и праздников',
            },
        ),
    ]
