# Generated by Django 5.0.7 on 2024-07-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_calendarholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarholiday',
            name='json_date',
            field=models.JSONField(verbose_name='список выходных из консультанта'),
        ),
    ]
