# Generated by Django 5.0.7 on 2024-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_calendarholiday_json_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarholiday',
            name='json_date',
            field=models.JSONField(verbose_name='Список выходных из консультанта'),
        ),
        migrations.AlterField(
            model_name='vat',
            name='name',
            field=models.SmallIntegerField(verbose_name='Процент ндс'),
        ),
    ]
