# Generated by Django 5.1 on 2024-08-13 11:18

import apps.core.utils_web
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_calendarholiday_json_date_alter_vat_name'),
        ('product', '0111_historicalproduct_promote_product_promote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок слайда')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание слайда')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Изображение')),
                ('type_slider', models.CharField(choices=[('MAIN', 'Только изображение'), ('VIDEO', 'Видео'), ('PHOTO', 'Фото право'), ('PHOTO_2', 'Фото лево'), ('PHOTO_2', 'Фото лево'), ('PROMOTE', 'Продвижение товара')], default='MAIN', max_length=7)),
                ('product_promote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продвигаемый товар')),
            ],
            options={
                'verbose_name': 'Слайдер на главной',
            },
        ),
    ]
