# Generated by Django 5.1 on 2024-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_slidermain_options_slidermain_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
