# Generated by Django 5.1 on 2024-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_slidermain_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка для перехода'),
        ),
        migrations.AddField(
            model_name='slidermain',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок слайда'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название слайда для админки'),
        ),
    ]
