# Generated by Django 5.1 on 2024-08-13 12:53

import apps.core.utils_web
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_slidermain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название слайда для админки'),
        ),
    ]
