# Generated by Django 5.1 on 2024-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_slidermain_slug_alter_slidermain_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vat',
            name='nameid',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Процент ндс'),
        ),
    ]
