# Generated by Django 5.1 on 2024-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vat_nameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vat',
            name='nameids',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Процент ндс'),
        ),
    ]
