# Generated by Django 5.1 on 2024-08-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_vat_nameids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vat',
            name='nameid',
        ),
        migrations.RemoveField(
            model_name='vat',
            name='nameids',
        ),
    ]
