# Generated by Django 5.1.1 on 2024-10-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_vat_nameid_remove_vat_nameids'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_legal_entity', models.CharField(max_length=300, verbose_name='Название компании полностью')),
                ('Short_name_legal_entity', models.CharField(max_length=300, verbose_name='Название компании кратко')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=10, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('legal_post_code', models.PositiveIntegerField(verbose_name='Юридический адрес :индекс')),
                ('legal_city', models.CharField(max_length=50, verbose_name='Юридический адрес : город')),
                ('legal_address', models.CharField(max_length=200, verbose_name='Юридический адрес : адрес')),
                ('postal_post_code', models.CharField(max_length=10, verbose_name='Почтовый адрес :индекс')),
                ('postal_city', models.CharField(max_length=50, verbose_name='Почтовый адрес : город')),
                ('postal_address', models.CharField(max_length=200, verbose_name='Почтовый адрес : адрес')),
                ('tel', models.CharField(max_length=200, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='BaseInfoAccountRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('account_requisites', models.CharField(max_length=30, verbose_name='Расчётный счёт')),
                ('bank', models.CharField(max_length=200, verbose_name='Банк')),
                ('kpp', models.CharField(max_length=20, verbose_name='Корреспондентский счет (к/с)')),
                ('bic', models.CharField(max_length=10, verbose_name='БИК')),
                ('requisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baseinfo', verbose_name='Реквизиты')),
            ],
        ),
    ]
