# Generated by Django 5.1.1 on 2024-10-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_baseinfo_baseinfoaccountrequisites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),
        migrations.AlterModelOptions(
            name='baseinfoaccountrequisites',
            options={'verbose_name': 'Расчётный счёт', 'verbose_name_plural': 'Расчётные счёта'},
        ),
        migrations.RenameField(
            model_name='baseinfo',
            old_name='Short_name_legal_entity',
            new_name='short_name_legal_entity',
        ),
    ]
