# Generated by Django 5.1.1 on 2024-10-21 08:54

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_baseinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add_motrum_base, verbose_name='Печать')),
                ('vendors', models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add_motrum_base, verbose_name='Печать')),
            ],
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='signature',
            field=models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add_motrum_base, verbose_name='Подпись в документах'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='stamp',
            field=models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add_motrum_base, verbose_name='Печать'),
        ),
    ]
