# Generated by Django 5.1.1 on 2024-10-21 11:05

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_baseimage_baseinfo_signature_baseinfo_stamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseimage',
            options={'verbose_name': 'Базовые изображения для документов ', 'verbose_name_plural': 'Базовые изображения для документов'},
        ),
        migrations.AlterField(
            model_name='baseimage',
            name='logo',
            field=models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add_motrum_base, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='baseimage',
            name='vendors',
            field=models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add_motrum_base, verbose_name='Поставщики'),
        ),
    ]
