# Generated by Django 5.1.2 on 2024-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_baseimage_options_alter_baseimage_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='counter_bill',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер счета клиента'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='counter_bill_offer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер счета клиента'),
        ),
    ]
