# Generated by Django 5.1.2 on 2024-11-29 05:21

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_baseinfo_counter_bill_baseinfo_counter_bill_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='icon3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Изображение вторая строка текста'),
        ),
        migrations.AddField(
            model_name='slidermain',
            name='image_right',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Изображение левое'),
        ),
        migrations.AddField(
            model_name='slidermain',
            name='text1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст 1 строка'),
        ),
        migrations.AddField(
            model_name='slidermain',
            name='text2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст в обводке'),
        ),
        migrations.AddField(
            model_name='slidermain',
            name='text4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст 2 строка'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Изображение левое'),
        ),
    ]
