# Generated by Django 5.1.2 on 2024-11-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_slidermain_icon3_slidermain_image_right_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidermain',
            name='text',
        ),
        migrations.RemoveField(
            model_name='slidermain',
            name='title',
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='type_slider',
            field=models.CharField(choices=[('MAIN', 'Лево-изображение. Право-видео или изображение + текст 2 строки'), ('PROMOTE', 'Продвижение товара')], default='MAIN', max_length=7),
        ),
    ]
