# Generated by Django 5.1.2 on 2024-11-29 06:09

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_slidermain_text_remove_slidermain_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermain',
            name='image_right',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Изображение правое'),
        ),
    ]
