# Generated by Django 5.1.2 on 2024-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_slidermain_image_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Способ доставки ')),
                ('text_long', models.CharField(max_length=1500, verbose_name='Способ доставки с описанием для документов')),
                ('company_delivery', models.CharField(max_length=1500, verbose_name='Компания осуществляющая доставку')),
            ],
        ),
    ]
