# Generated by Django 5.1.2 on 2024-11-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_typedelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedelivery',
            options={'verbose_name': 'Типы доставки', 'verbose_name_plural': 'Типы доставок'},
        ),
        migrations.AlterField(
            model_name='typedelivery',
            name='company_delivery',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Компания осуществляющая доставку'),
        ),
    ]
