# Generated by Django 5.1.3 on 2024-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_typedelivery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermain',
            name='video',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
