# Generated by Django 5.1.2 on 2024-12-04 08:30

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_slidermain_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Видео фаилом '),
        ),
    ]
