# Generated by Django 5.1.4 on 2024-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_slidermain_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexInfoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_project', models.SmallIntegerField(verbose_name='реализованных проектов технического зрения')),
                ('modernization', models.SmallIntegerField(verbose_name='модернизировано установок')),
                ('shkaf_upravleniya', models.SmallIntegerField(verbose_name='изготовлено шкафов         управления')),
                ('installation', models.SmallIntegerField(verbose_name='запущенных установок')),
            ],
            options={
                'verbose_name': 'Типы доставки',
                'verbose_name_plural': 'Типы доставок',
            },
        ),
    ]
