# Generated by Django 5.1.4 on 2024-12-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_indexinfoweb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexinfoweb',
            options={'verbose_name': 'Инфа для главной страницы', 'verbose_name_plural': 'Инфа для главной страницы'},
        ),
    ]
