# Generated by Django 5.1.4 on 2024-12-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_indexinfoweb_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermain',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
    ]
