# Generated by Django 5.1.4 on 2024-12-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_slidermain_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageDealBx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.SmallIntegerField(verbose_name='ID bitrix')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='NAME -Имя')),
                ('entity_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='ENTITY_ID - название воронки ')),
                ('category_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='CATEGORY_ID - id воронки ')),
                ('status_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='STATUS_ID - название статуса техническое- пишется в статусе сделки ')),
                ('nam_web', models.CharField(blank=True, max_length=250, null=True, verbose_name='NAME -Имя')),
            ],
        ),
    ]
