# Generated by Django 5.1.4 on 2024-12-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_stagedealbx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedealbx',
            name='nam_web',
        ),
        migrations.AddField(
            model_name='stagedealbx',
            name='name_web',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя на сайте'),
        ),
        migrations.AddField(
            model_name='stagedealbx',
            name='name_web_eng',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя техническое сат англ'),
        ),
    ]
