# Generated by Django 5.1.4 on 2025-01-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_stagedealbx_nam_web_stagedealbx_name_web_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoTextSolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_page', models.CharField(blank=True, max_length=250, null=True, verbose_name='название страницы  страницы')),
                ('text', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Текст')),
            ],
        ),
    ]
