# Generated by Django 5.1.5 on 2025-01-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_seotextsolutions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seotextsolutions',
            options={'verbose_name': 'Сео для страниц решений', 'verbose_name_plural': 'Сео дял страниц решений'},
        ),
    ]
