# Generated by Django 5.1.5 on 2025-02-20 08:25

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_seotextsolutions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name=' лет на рынке год основания – 2012')),
                ('emploee_high', models.SmallIntegerField(verbose_name='высококвалифицированных сотрудника')),
                ('profit', models.SmallIntegerField(verbose_name='оборот группы компаний')),
                ('emploee_engineer', models.SmallIntegerField(verbose_name=' инженерский состав')),
            ],
            options={
                'verbose_name': 'Инфа МОТРУМ В ЦИФРАХ страница о компании',
                'verbose_name_plural': 'Инфа МОТРУМ В ЦИФРАХ страница о компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyPrijectAutoInfoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_project', models.SmallIntegerField(verbose_name='установок с техническим зрением')),
                ('shkaf_upravleniya', models.SmallIntegerField(verbose_name='собрано шкафов управления')),
                ('honest_sign', models.SmallIntegerField(verbose_name='линий маркировки «Честный знак»')),
                ('project_all', models.SmallIntegerField(verbose_name='более ___ реализованных проектов по всей России и СН')),
            ],
            options={
                'verbose_name': 'Инфа МОТРУМ В ЦИФРАХ страница о компании',
                'verbose_name_plural': 'Инфа МОТРУМ В ЦИФРАХ страница о компании',
            },
        ),
        migrations.CreateModel(
            name='reviewsAutoInfoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст')),
                ('Legal_entity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст')),
                ('text', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Текст')),
                ('image_right', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Картинка')),
            ],
        ),
    ]
