# Generated by Django 5.1.5 on 2025-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_companyinfoweb_companyprijectautoinfoweb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprijectautoinfoweb',
            options={'verbose_name': 'Инфа ПРОЕКТЫ КОМПЛЕКСНОЙ АВТОМАТИЗАЦИИ страница о компании', 'verbose_name_plural': 'Инфа ПРОЕКТЫ КОМПЛЕКСНОЙ АВТОМАТИЗАЦИИ страница о компании'},
        ),
        migrations.AlterModelOptions(
            name='reviewsautoinfoweb',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='reviewsautoinfoweb',
            name='Legal_entity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='reviewsautoinfoweb',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='reviewsautoinfoweb',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст'),
        ),
    ]
