# Generated by Django 5.1.5 on 2025-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_companyprijectautoinfoweb_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsautoinfoweb',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
