# Generated by Django 5.1.5 on 2025-02-20 08:39

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_reviewsautoinfoweb_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsautoinfoweb',
            name='image_right',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_reviews_web, verbose_name='Картинка'),
        ),
    ]
