# Generated by Django 5.1.5 on 2025-02-20 09:43

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_reviewsautoinfoweb_image_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoClientInfoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_company_web, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Фото блок клиенты',
                'verbose_name_plural': 'Фото блок клиенты',
            },
        ),
        migrations.CreateModel(
            name='PhotoEmoloeeInfoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_company_web, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Фото блок сотрудники',
                'verbose_name_plural': 'Фото блок сотрудники',
            },
        ),
        migrations.RenameField(
            model_name='reviewsautoinfoweb',
            old_name='image_right',
            new_name='image',
        ),
    ]
