# Generated by Django 5.1.5 on 2025-03-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_photoclientinfoweb_photoemoloeeinfoweb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedCompanyBX24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_bx_id', models.IntegerField(verbose_name='company_bx_id')),
            ],
        ),
    ]
