# Generated by Django 5.1.5 on 2025-03-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_updatedcompanybx24'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexinfoweb',
            options={'verbose_name': 'Мотрум в цифрах главной страницы', 'verbose_name_plural': 'Мотрум в цифрах для главной страницы'},
        ),
        migrations.AddField(
            model_name='typedelivery',
            name='actual',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='type_slider',
            field=models.CharField(choices=[('MAIN', 'Лево-изображение. Право-видео или изображение + текст 2 строки')], default='MAIN', max_length=7, verbose_name='Тип слайдера'),
        ),
    ]
