# Generated by Django 5.1.5 on 2025-03-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_indexinfoweb_options_typedelivery_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='counter_bill_offer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер Счет-оферта клиента'),
        ),
    ]
