# Generated by Django 5.1.5 on 2025-03-27 05:48

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_slidermain_text_after_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermain',
            name='icon3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Изображение вторая строка текста'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Изображение левое'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='image_right',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Изображение правое'),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка для перехода'),
        ),
    ]
