# Generated by Django 5.1.5 on 2025-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_slidermain_icon3_alter_slidermain_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoclientinfoweb',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
        migrations.AddField(
            model_name='photoemoloeeinfoweb',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
    ]
