# Generated by Django 5.1.5 on 2025-04-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_photoclientinfoweb_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexinfoweb',
            name='installation',
            field=models.SmallIntegerField(verbose_name='запущенных систем  маркировки «Честный знак»'),
        ),
    ]
