# Generated by Django 5.1.5 on 2025-05-27 10:22

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_indexinfoweb_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsautoinfoweb',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=apps.core.utils_web.get_file_path_reviews_web, verbose_name='Картинка'),
        ),
    ]
