# Generated by Django 5.1.5 on 2025-07-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_indexinfoweb_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=700, null=True, verbose_name='Страница')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='title')),
                ('h1', models.CharField(blank=True, max_length=500, null=True, verbose_name='h1')),
            ],
            options={
                'verbose_name': 'SEO тег',
                'verbose_name_plural': 'SEO теги',
            },
        ),
    ]
