# Generated by Django 5.1.5 on 2025-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_seometatags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometatags',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='description'),
        ),
    ]
