# Generated by Django 5.1.5 on 2025-07-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_reviewsautoinfoweb_image'),
        ('core', '0050_alter_seometatags_description'),
    ]

    operations = [
    ]
