# Generated by Django 5.1.5 on 2025-08-19 10:13

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20250721_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermain',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.utils_web.get_file_path_slider_web, verbose_name='Видео фаилом '),
        ),
    ]
