# Generated by Django 5.0.5 on 2024-05-08 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_initial'),
        ('supplier', '0001_initial'),
        ('user', '0002_alter_adminuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bitrix', models.PositiveIntegerField(verbose_name='номер сделки битрикс')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('date_stop', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания')),
                ('currency_product', models.BinaryField(verbose_name='валютные товары в спецификации')),
                ('tag_stop', models.BinaryField(verbose_name='недействительно')),
                ('total_amount', models.IntegerField(verbose_name='процент скидки')),
                ('file', models.CharField(max_length=40, verbose_name='фаил в системе')),
                ('admin_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.adminuser')),
                ('wholesale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.discount', verbose_name='Скидка оптовая')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество товара')),
                ('price_one', models.IntegerField(verbose_name='цена одного на момент формирования')),
                ('price_all', models.IntegerField(verbose_name='цена всего товара на момент формирования')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specification.specification')),
            ],
        ),
    ]
