# Generated by Django 5.0.6 on 2024-05-29 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 29, 10, 4, 16, 774945), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default=datetime.datetime(2024, 5, 29, 10, 4, 16, 774962), verbose_name='Дата окончания'),
        ),
    ]
