# Generated by Django 5.0.6 on 2024-05-29 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0002_alter_specification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата окончания'),
        ),
    ]
