# Generated by Django 5.0.6 on 2024-05-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0004_alter_productspecification_options_and_more'),
        ('supplier', '0024_delete_supplierpastcategoryproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='currency_product',
            field=models.BinaryField(default=False, verbose_name='валютные товары в спецификации'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='wholesale',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.discount', verbose_name='Скидка оптовая'),
        ),
    ]
