# Generated by Django 5.0.6 on 2024-05-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0006_alter_specification_admin_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='currency_product',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='tag_stop',
        ),
    ]
