# Generated by Django 5.0.6 on 2024-05-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0007_remove_specification_currency_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='currency_product',
            field=models.BooleanField(default=False, verbose_name='валютные товары в спецификации'),
        ),
        migrations.AddField(
            model_name='specification',
            name='tag_stop',
            field=models.BooleanField(default=False, verbose_name='недействительно'),
        ),
    ]
