# Generated by Django 5.0.6 on 2024-06-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('product', '0041_alter_product_vendor'),
        ('specification', '0008_specification_currency_product_and_more'),
        ('user', '0002_alter_adminuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='price_all',
            field=models.FloatField(verbose_name='цена всего товара на момент формирования'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='price_one',
            field=models.FloatField(verbose_name='цена одного на момент формирования'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specification.specification', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='admin_creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.adminuser', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default='2024-05-31', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='total_amount',
            field=models.FloatField(default=None, null=True, verbose_name='Сумма спецификации'),
        ),
    ]
