# Generated by Django 5.0.6 on 2024-06-04 07:10

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0009_alter_productspecification_price_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default='2024-06-07', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=apps.specification.utils.get_document_path, verbose_name='фаил в системе'),
        ),
    ]
