# Generated by Django 5.0.6 on 2024-06-04 09:13

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0010_alter_specification_date_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=apps.specification.utils.get_document_path, verbose_name='фаил'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='tag_stop',
            field=models.BooleanField(default=True, verbose_name='Действительно'),
        ),
    ]
