# Generated by Django 5.0.6 on 2024-06-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0011_alter_specification_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default='2024-06-08', verbose_name='Дата окончания'),
        ),
    ]
