# Generated by Django 5.0.6 on 2024-06-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0015_alter_specification_date_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default='2024-06-14', verbose_name='Дата окончания'),
        ),
    ]
