# Generated by Django 5.0.6 on 2024-06-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0021_alter_specification_date_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='specification.specification', verbose_name='Товар'),
        ),
    ]
