# Generated by Django 5.0.6 on 2024-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0022_alter_productspecification_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='price_all',
            field=models.FloatField(blank=True, null=True, verbose_name='цена всего товара на момент формирования'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество товара'),
        ),
    ]
