# Generated by Django 5.0.6 on 2024-06-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0023_alter_productspecification_price_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='price_exclusive',
            field=models.BooleanField(default=False, verbose_name='Цена по запросу'),
        ),
    ]
