# Generated by Django 5.0.6 on 2024-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0024_productspecification_price_exclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default='2024-07-05', verbose_name='Дата окончания'),
        ),
    ]
