# Generated by Django 5.0.6 on 2024-07-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0026_alter_specification_date_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default='2024-07-07', verbose_name='Дата окончания'),
        ),
    ]
