# Generated by Django 5.0.6 on 2024-07-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0028_productspecification_product_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='tag_currency',
        ),
    ]
