# Generated by Django 5.0.6 on 2024-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0029_remove_specification_tag_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default='2024-07-11', verbose_name='Дата окончания'),
        ),
    ]
