# Generated by Django 5.0.6 on 2024-07-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0030_alter_specification_date_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='date_stop',
            field=models.DateField(default='2024-07-12', verbose_name='Дата окончания'),
        ),
    ]
