# Generated by Django 5.0.7 on 2024-07-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0040_alter_specification_date_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='extra_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент дополнительной скидки'),
        ),
        migrations.AddField(
            model_name='historicalproductspecification',
            name='price_all_motrum',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена Motrum в рублях'),
        ),
        migrations.AddField(
            model_name='historicalproductspecification',
            name='price_one_motrum',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена мотрум  в рублях'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='extra_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент дополнительной скидки'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='price_all_motrum',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена Motrum в рублях'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='price_one_motrum',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена мотрум  в рублях'),
        ),
    ]
