# Generated by Django 5.0.7 on 2024-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0041_historicalproductspecification_extra_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalspecification',
            name='wholesale',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='wholesale',
        ),
        migrations.AddField(
            model_name='historicalspecification',
            name='is_prepay',
            field=models.BooleanField(default=False, verbose_name='Предоплата'),
        ),
        migrations.AddField(
            model_name='specification',
            name='is_prepay',
            field=models.BooleanField(default=False, verbose_name='Предоплата'),
        ),
    ]
