# Generated by Django 5.0.7 on 2024-07-31 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0043_alter_historicalproductspecification_price_all_and_more'),
        ('user', '0006_alter_adminuser_admin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspecification',
            name='admin_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.adminuser', verbose_name='Администратор'),
        ),
    ]
