# Generated by Django 5.1 on 2024-08-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0113_rename_save_cart_cart_is_active'),
        ('specification', '0045_historicalspecification_date_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecification',
            name='cart',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.cart', verbose_name='корзина'),
        ),
        migrations.AddField(
            model_name='specification',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.cart', verbose_name='корзина'),
        ),
    ]
