# Generated by Django 5.1 on 2024-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0046_historicalspecification_cart_specification_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalspecification',
            name='currency_product',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='currency_product',
        ),
        migrations.AlterField(
            model_name='historicalspecification',
            name='id_bitrix',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер сделки битрикс'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='id_bitrix',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер сделки битрикс'),
        ),
    ]
