# Generated by Django 5.1 on 2024-08-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0047_remove_historicalspecification_currency_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSpecification',
        ),
    ]
