# Generated by Django 5.1 on 2024-08-22 12:46

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0113_rename_save_cart_cart_is_active'),
        ('specification', '0048_delete_historicalspecification'),
        ('user', '0009_delete_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSpecification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('id_bitrix', models.PositiveIntegerField(null=True, verbose_name='Номер сделки битрикс')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата добавления')),
                ('date_update', models.DateField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('date_stop', models.DateField(verbose_name='Дата окончания')),
                ('tag_stop', models.BooleanField(default=True, verbose_name='Действительно')),
                ('total_amount', models.FloatField(default=None, null=True, verbose_name='Сумма спецификации')),
                ('file', models.TextField(default=None, max_length=100, null=True, verbose_name='Фаил')),
                ('is_prepay', models.BooleanField(default=False, verbose_name='Предоплата')),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admin_creator', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.adminuser', verbose_name='Администратор')),
                ('cart', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.cart', verbose_name='корзина')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Спецификация',
                'verbose_name_plural': 'historical Спецификации',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
