# Generated by Django 5.1 on 2024-08-22 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0049_historicalspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspecification',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата добавления'),
        ),
    ]
