# Generated by Django 5.1 on 2024-08-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0050_alter_historicalspecification_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProductSpecification',
        ),
    ]
