# Generated by Django 5.1 on 2024-08-22 13:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_vat_nameid_remove_vat_nameids'),
        ('product', '0113_rename_save_cart_cart_is_active'),
        ('specification', '0051_delete_historicalproductspecification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductSpecification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='количество товара')),
                ('price_one', models.FloatField(verbose_name='Цена одного на момент формирования')),
                ('price_all', models.FloatField(blank=True, null=True, verbose_name='Цена всего товара на момент формирования')),
                ('price_one_motrum', models.FloatField(blank=True, null=True, verbose_name='Цена мотрум  в рублях')),
                ('price_all_motrum', models.FloatField(blank=True, null=True, verbose_name='Цена Motrum в рублях')),
                ('price_exclusive', models.BooleanField(default=False, verbose_name='Цена по запросу')),
                ('extra_discount', models.FloatField(blank=True, null=True, verbose_name='Процент дополнительной скидки')),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Продукты')),
                ('product_currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.currency', verbose_name='Валюта')),
                ('specification', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specification.specification', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'historical Спецификация продукт',
                'verbose_name_plural': 'historical Спецификации Продукты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
