# Generated by Django 5.1 on 2024-09-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0116_productcart_product_new_price'),
        ('specification', '0052_historicalproductspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукты'),
        ),
    ]
