# Generated by Django 5.1 on 2024-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0053_alter_productspecification_product'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='historicalproductspecification',
    #         name='date_delivery',
    #         field=models.DateField(default=None, verbose_name='Дата поставки товара'),
    #     ),
    #     migrations.AddField(
    #         model_name='productspecification',
    #         name='date_delivery',
    #         field=models.DateField(default=None, verbose_name='Дата поставки товара'),
    #     ),
    # ]
