# Generated by Django 5.1 on 2024-09-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0054_historicalproductspecification_date_delivery_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='historicalproductspecification',
    #         name='date_delivery',
    #     ),
    #     migrations.RemoveField(
    #         model_name='productspecification',
    #         name='date_delivery',
    #     ),
    # ]
