# Generated by Django 5.1 on 2024-09-11 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0055_remove_historicalproductspecification_date_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='date_delivery',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата поставки товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecification',
            name='date_delivery',
            field=models.DateField(auto_now=True, verbose_name='Дата поставки товара'),
        ),
    ]
