# Generated by Django 5.1 on 2024-09-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0056_historicalproductspecification_date_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='product_new',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Название товара нового без добавления в бд'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product_new',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Название товара нового без добавления в бд'),
        ),
        migrations.AlterField(
            model_name='historicalproductspecification',
            name='date_delivery',
            field=models.DateField(verbose_name='Дата поставки товара'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='date_delivery',
            field=models.DateField(verbose_name='Дата поставки товара'),
        ),
    ]
