# Generated by Django 5.1.1 on 2024-10-09 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0058_alter_historicalproductspecification_date_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specification.specification', verbose_name='Товар'),
        ),
    ]
