# Generated by Django 5.1.1 on 2024-10-10 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0121_alter_historicalstock_data_update_and_more'),
        ('specification', '0059_alter_productspecification_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.cart', verbose_name='корзина'),
        ),
    ]
