# Generated by Django 5.1.1 on 2024-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0060_alter_specification_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='product_new_article',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Артикул товара нового без добавления в бд'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product_new_article',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Артикул товара нового без добавления в бд'),
        ),
        migrations.AlterField(
            model_name='historicalproductspecification',
            name='product_new',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Название товара нового без добавления в бд'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product_new',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Название товара нового без добавления в бд'),
        ),
    ]
