# Generated by Django 5.1.1 on 2024-10-17 09:42

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0062_historicalproductspecification_comment_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='historicalspecification',
        #     name='number',
        #     field=models.CharField(default=builtins.id, max_length=1000, verbose_name='Номер'),
        # ),
        # migrations.AddField(
        #     model_name='specification',
        #     name='number',
        #     field=models.CharField(default=builtins.id, max_length=1000, verbose_name='Номер'),
        # ),
    ]
