# Generated by Django 5.1.1 on 2024-10-17 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0063_historicalspecification_number_specification_number'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='historicalspecification',
        #     name='number',
        #     field=models.CharField(default=uuid.uuid4, max_length=1000, verbose_name='Номер спецификации'),
        # ),
        # migrations.AlterField(
        #     model_name='specification',
        #     name='number',
        #     field=models.CharField(default=uuid.uuid4, max_length=1000, verbose_name='Номер спецификации'),
        # ),
    ]
