# Generated by Django 5.1.1 on 2024-10-17 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0065_alter_historicalspecification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecification',
            name='number',
            field=models.CharField(default=uuid.uuid4, max_length=1000, null=True, verbose_name='Номер спецификации'),
        ),
        migrations.AddField(
            model_name='specification',
            name='number',
            field=models.CharField(default=uuid.uuid4, max_length=1000, null=True, verbose_name='Номер спецификации'),
        ),
    ]
