# Generated by Django 5.1.1 on 2024-10-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0122_productcart_product_new_article_and_more'),
        ('specification', '0066_historicalspecification_number_specification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspecification',
            name='cart',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.cart', verbose_name='Корзина'),
        ),
    ]
