# Generated by Django 5.1.2 on 2024-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0068_historicalspecification_date_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='sale_motrum',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Скидка мотрум'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='sale_motrum',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Скидка мотрум'),
        ),
    ]
