# Generated by Django 5.1.2 on 2024-11-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0070_alter_historicalspecification_number_and_more'),
    ]

    operations = [

    ]
