# Generated by Django 5.1.2 on 2024-11-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0071_remove_historicalproductspecification_product_new_article_and_more'),
    ]

    operations = [

    ]
