# Generated by Django 5.1.2 on 2024-11-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0072_historicalproductspecification_product_new_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalspecification',
            name='number',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='number',
        ),
    ]
