# Generated by Django 5.1.2 on 2024-11-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0073_remove_historicalspecification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecification',
            name='number',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Номер спецификации'),
        ),
        migrations.AddField(
            model_name='specification',
            name='number',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Номер спецификации'),
        ),
    ]
