# Generated by Django 5.1.2 on 2024-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0074_historicalspecification_number_specification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='price_one_original_new',
            field=models.FloatField(default=0, verbose_name='Цена одного для нового товара без скидки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecification',
            name='price_one_original_new',
            field=models.FloatField(default=0.0, verbose_name='Цена одного для нового товара без скидки'),
            preserve_default=False,
        ),
    ]
