# Generated by Django 5.1.2 on 2024-11-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0075_historicalproductspecification_price_one_original_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductspecification',
            name='price_one_original_new',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена одного для нового товара без скидки'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='price_one_original_new',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена одного для нового товара без скидки'),
        ),
    ]
