# Generated by Django 5.1.2 on 2024-11-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0077_historicalproductspecification_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecification',
            name='date_create_pdf',
            field=models.DateField(default=None, null=True, verbose_name='Дата создания пдф'),
        ),
        migrations.AddField(
            model_name='specification',
            name='date_create_pdf',
            field=models.DateField(default=None, null=True, verbose_name='Дата создания пдф'),
        ),
    ]
