# Generated by Django 5.1.2 on 2024-11-15 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0135_alter_historicalproduct_add_in_nomenclature_and_more'),
        ('specification', '0078_historicalspecification_date_create_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='id_cart',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.productcart', verbose_name='Товар корзины'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='id_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcart', verbose_name='Товар корзины'),
        ),
    ]
