# Generated by Django 5.1.2 on 2024-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0079_historicalproductspecification_id_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='date_delivery_bill',
            field=models.DateField(null=True, verbose_name='Дата поставки товара в счете'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='date_delivery_bill',
            field=models.DateField(null=True, verbose_name='Дата поставки товара в счете'),
        ),
    ]
