# Generated by Django 5.1.2 on 2024-12-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0080_historicalproductspecification_date_delivery_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='client_shipment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отгружено клиенту'),
        ),
        migrations.AddField(
            model_name='historicalproductspecification',
            name='date_shipment',
            field=models.DateField(null=True, verbose_name='Дата поставки товара'),
        ),
        migrations.AddField(
            model_name='historicalproductspecification',
            name='reserve',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарезервировано на складе мотрум'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='client_shipment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отгружено клиенту'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='date_shipment',
            field=models.DateField(null=True, verbose_name='Дата поставки товара'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='reserve',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарезервировано на складе мотрум'),
        ),
    ]
