# Generated by Django 5.1.4 on 2024-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0082_historicalproductspecification_product_price_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='id_bitrix',
            field=models.IntegerField(blank=True, null=True, verbose_name='товар в сделке битрикс'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='id_bitrix',
            field=models.IntegerField(blank=True, null=True, verbose_name='товар в сделке битрикс'),
        ),
    ]
