# Generated by Django 5.1.5 on 2025-02-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0083_historicalproductspecification_id_bitrix_and_more'),
        ('supplier', '0044_suppliercategoryproductall_is_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductspecification',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
