# Generated by Django 5.1.5 on 2025-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0087_alter_historicalspecification_id_bitrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecification',
            name='marginality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Маржинальность заказа в %'),
        ),
        migrations.AddField(
            model_name='specification',
            name='marginality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Маржинальность заказа в %'),
        ),
    ]
