# Generated by Django 5.1.5 on 2025-06-03 06:40

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0087_alter_historicalspecification_id_bitrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecification',
            name='file_no_signature',
            field=models.TextField(default=None, max_length=100, null=True, verbose_name='Фаил без печатей'),
        ),
        migrations.AddField(
            model_name='specification',
            name='file_no_signature',
            field=models.FileField(default=None, null=True, upload_to=apps.specification.utils.get_document_path, verbose_name='Фаил без печатей'),
        ),
    ]
