# Generated by Django 5.1.5 on 2025-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0088_historicalspecification_marginality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspecification',
            name='marginality',
            field=models.FloatField(blank=True, null=True, verbose_name='Маржинальность заказа в %'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='marginality',
            field=models.FloatField(blank=True, null=True, verbose_name='Маржинальность заказа в %'),
        ),
    ]
