# Generated by Django 5.1.5 on 2025-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0089_alter_historicalspecification_marginality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecification',
            name='marginality_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Маржинальность заказа в рублях'),
        ),
        migrations.AddField(
            model_name='specification',
            name='marginality_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Маржинальность заказа в рублях'),
        ),
    ]
