# Generated by Django 5.1.5 on 2025-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0089_alter_historicalspecification_marginality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecification',
            name='name_prefix',
            field=models.CharField(blank=True, choices=[('Д', 'Д')], default='Д', max_length=100, null=True, verbose_name='Префикс номера'),
        ),
        migrations.AddField(
            model_name='specification',
            name='name_prefix',
            field=models.CharField(blank=True, choices=[('Д', 'Д')], default='Д', max_length=100, null=True, verbose_name='Префикс номера'),
        ),
    ]
