# Generated by Django 5.1.5 on 2025-08-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0090_historicalspecification_marginality_sum_and_more'),
        ('specification', '0090_historicalspecification_name_prefix_and_more'),
    ]

    operations = [
    ]
