# Generated by Django 5.1.5 on 2025-08-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0088_historicalspecification_file_no_signature_and_more'),
        ('specification', '0091_merge_20250814_0947'),
    ]

    operations = [
    ]
