# Generated by Django 5.1.5 on 2025-08-19 10:13

import apps.specification.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0092_merge_20250818_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspecification',
            name='file',
            field=models.TextField(default=None, max_length=1000, null=True, verbose_name='Фаил'),
        ),
        migrations.AlterField(
            model_name='historicalspecification',
            name='file_no_signature',
            field=models.TextField(default=None, max_length=1000, null=True, verbose_name='Фаил без печатей'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='file',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to=apps.specification.utils.get_document_path, verbose_name='Фаил'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='file_no_signature',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to=apps.specification.utils.get_document_path, verbose_name='Фаил без печатей'),
        ),
    ]
