# Generated by Django 5.0.5 on 2024-05-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='SupplierCategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('article_name', models.CharField(max_length=25, verbose_name='Артикул категории')),
                ('category_catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct')),
            ],
            options={
                'verbose_name': 'Категория товара у поставщика',
                'verbose_name_plural': 'Категории товаров у поставщика',
            },
        ),
        migrations.CreateModel(
            name='SupplierGroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название группы')),
                ('article_name', models.CharField(max_length=25, verbose_name='Артикул группы')),
                ('category_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliercategoryproduct')),
                ('group_catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct')),
            ],
            options={
                'verbose_name': 'Группа товара у поставщика',
                'verbose_name_plural': 'Группы товаров у поставщика',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название производителя')),
                ('currency_catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.currency', verbose_name='Производитель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.SmallIntegerField(verbose_name='процент скидки')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик')),
                ('category_catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliercategoryproduct')),
                ('group_catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliergroupproduct')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Производитель')),
            ],
        ),
    ]
