# Generated by Django 5.0.5 on 2024-05-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_currency_options'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='currency_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.currency', verbose_name='Валюта каталога'),
        ),
    ]
