# Generated by Django 5.0.5 on 2024-05-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_vat_delete_testmodel'),
        ('supplier', '0002_alter_vendor_currency_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='currency_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта каталога'),
        ),
    ]
