# Generated by Django 5.0.5 on 2024-05-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_vendor_currency_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
