# Generated by Django 5.0.6 on 2024-05-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_vendor_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategoryProductTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('article_name', models.CharField(max_length=25, verbose_name='Артикул категории')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Категория товара у поставщика',
                'verbose_name_plural': 'Категории товаров у поставщика',
            },
        ),
    ]
