# Generated by Django 5.0.6 on 2024-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_suppliercategoryproducttest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercategoryproducttest',
            options={},
        ),
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
