# Generated by Django 5.0.6 on 2024-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_alter_suppliercategoryproducttest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
