# Generated by Django 5.0.6 on 2024-05-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название поставщика'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название производителя'),
        ),
    ]
