# Generated by Django 5.0.6 on 2024-05-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_alter_supplier_name_alter_vendor_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierCategoryProductTest',
            new_name='SupplierCategoryProductAll',
        ),
    ]
