# Generated by Django 5.0.6 on 2024-05-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_rename_suppliercategoryproducttest_suppliercategoryproductall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
    ]
