# Generated by Django 5.0.6 on 2024-05-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_groupproduct_options'),
        ('supplier', '0010_alter_suppliercategoryproductall_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercategoryproductall',
            options={'verbose_name': 'Категории товара у поставщиков', 'verbose_name_plural': 'Категории товаров у поставщиков'},
        ),
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='category_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct'),
        ),
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='group_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.groupproduct'),
        ),
    ]
