# Generated by Django 5.0.6 on 2024-05-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vat_options_rename_code_vat_name'),
        ('product', '0006_alter_categoryproduct_name_alter_groupproduct_name'),
        ('supplier', '0011_alter_suppliercategoryproductall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vat_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vat', verbose_name='Ндс в каталоге'),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='category_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct', verbose_name='Категория каталога'),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='group_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.groupproduct', verbose_name='Группа каталога'),
        ),
    ]
