# Generated by Django 5.0.6 on 2024-05-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_categoryproduct_name_alter_groupproduct_name'),
        ('supplier', '0012_vendor_vat_catalog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='category_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categoryproduct', verbose_name='Категория каталога'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='group_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.groupproduct', verbose_name='Группа каталога'),
        ),
    ]
