# Generated by Django 5.0.6 on 2024-05-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0014_alter_discount_category_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Вендор'),
        ),
    ]
