# Generated by Django 5.0.6 on 2024-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0015_suppliercategoryproductall_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='article_name',
            field=models.CharField(max_length=55, verbose_name='Артикул категории'),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название категории'),
        ),
    ]
