# Generated by Django 5.0.6 on 2024-05-17 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0016_alter_suppliercategoryproductall_article_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercategoryproductall',
            options={'verbose_name': 'Приходящая категории товара от поставщиков', 'verbose_name_plural': 'Приходящие категории товаров от поставщиков'},
        ),
        migrations.RemoveField(
            model_name='suppliercategoryproduct',
            name='article_name',
        ),
        migrations.RemoveField(
            model_name='suppliercategoryproduct',
            name='category_catalog',
        ),
        migrations.RemoveField(
            model_name='suppliergroupproduct',
            name='group_catalog',
        ),
        migrations.AlterField(
            model_name='suppliercategoryproduct',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='category_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercategoryproduct', verbose_name='Категория каталога поставщика'),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='group_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliergroupproduct', verbose_name='Группа каталога поставщика'),
        ),
        migrations.AlterField(
            model_name='suppliergroupproduct',
            name='category_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliercategoryproduct', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='suppliergroupproduct',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название группы'),
        ),
    ]
