# Generated by Django 5.0.6 on 2024-05-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_productimage_file_and_more'),
        ('supplier', '0017_alter_suppliercategoryproductall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='category_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercategoryproduct', verbose_name='Категория каталога поставщика'),
        ),
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='group_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliergroupproduct', verbose_name='Группа каталога поставщика'),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='category_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproduct', verbose_name='Категория каталога мотрум'),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='group_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.groupproduct', verbose_name='Группа каталога мотрум'),
        ),
    ]
