# Generated by Django 5.0.6 on 2024-05-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0018_suppliercategoryproductall_category_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliergroupproduct',
            name='article_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул группы'),
        ),
    ]
