# Generated by Django 5.0.6 on 2024-05-17 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0019_alter_suppliergroupproduct_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='category_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercategoryproduct', verbose_name='Категория каталога поставщика'),
        ),
        migrations.AddField(
            model_name='discount',
            name='group_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliergroupproduct', verbose_name='Группа каталога поставщика'),
        ),
    ]
