# Generated by Django 5.0.6 on 2024-05-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0020_discount_category_supplier_discount_group_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category_catalog',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='group_catalog',
        ),
        migrations.AddField(
            model_name='discount',
            name='category_supplier_all',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliercategoryproductall', verbose_name='Приходящая категории товара от поставщиков'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.FloatField(verbose_name='процент скидки'),
        ),
    ]
