# Generated by Django 5.0.6 on 2024-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0021_remove_discount_category_catalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPAstCategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('article_name', models.CharField(max_length=25, verbose_name='Артикул категории')),
            ],
            options={
                'verbose_name': 'Категория товара у поставщика',
                'verbose_name_plural': 'Категории товаров у поставщика',
            },
        ),
        migrations.AlterField(
            model_name='suppliercategoryproductall',
            name='article_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Артикул категории'),
        ),
    ]
