# Generated by Django 5.0.6 on 2024-05-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0022_supplierpastcategoryproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Производитель'),
        ),
    ]
