# Generated by Django 5.0.6 on 2024-05-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0023_alter_discount_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierPAstCategoryProduct',
        ),
        migrations.AddField(
            model_name='suppliercategoryproduct',
            name='article_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул категории'),
        ),
        migrations.AddField(
            model_name='suppliercategoryproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='suppliercategoryproduct',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Вендор'),
        ),
        migrations.AddField(
            model_name='suppliergroupproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='suppliergroupproduct',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Вендор'),
        ),
    ]
