# Generated by Django 5.0.6 on 2024-06-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0024_delete_supplierpastcategoryproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='слаг'),
        ),
        migrations.AddField(
            model_name='suppliergroupproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='слаг'),
        ),
    ]
