# Generated by Django 5.0.6 on 2024-07-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_alter_price_sale_alter_productproperty_product'),
        ('supplier', '0025_suppliercategoryproductall_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercategoryproductall',
            options={'verbose_name': 'Подгруппы поставщиков', 'verbose_name_plural': 'Подгруппы поставщиков'},
        ),
        migrations.AddField(
            model_name='suppliercategoryproduct',
            name='category_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproduct', verbose_name='Категория каталога мотрум'),
        ),
        migrations.AddField(
            model_name='suppliergroupproduct',
            name='group_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.groupproduct', verbose_name='Группа каталога мотрум'),
        ),
    ]
