# Generated by Django 5.0.6 on 2024-07-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0026_alter_suppliercategoryproductall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproduct',
            name='autosave_tag',
            field=models.BooleanField(default=True, verbose_name='автоматическая загрузка'),
        ),
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='autosave_tag',
            field=models.BooleanField(default=True, verbose_name='автоматическая загрузка'),
        ),
        migrations.AddField(
            model_name='suppliergroupproduct',
            name='autosave_tag',
            field=models.BooleanField(default=True, verbose_name='автоматическая загрузка'),
        ),
    ]
