# Generated by Django 5.0.6 on 2024-07-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_alter_price_sale_alter_productproperty_product'),
        ('supplier', '0027_suppliercategoryproduct_autosave_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliergroupproduct',
            name='category_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproduct', verbose_name='Категория каталога мотрум'),
        ),
    ]
