# Generated by Django 5.0.6 on 2024-07-02 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_alter_price_sale_alter_productproperty_product'),
        ('supplier', '0028_suppliergroupproduct_category_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproduct',
            name='group_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.groupproduct', verbose_name='Группа каталога мотрум'),
        ),
    ]
