# Generated by Django 5.0.6 on 2024-07-09 05:34

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0029_suppliercategoryproduct_group_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=apps.core.utils.get_file_price_path_add, verbose_name='Архив с прайсами'),
        ),
    ]
