# Generated by Django 5.0.6 on 2024-07-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0030_supplier_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='слаг'),
        ),
    ]
