# Generated by Django 5.0.7 on 2024-07-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0032_alter_supplier_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_tag_pre_sale',
            field=models.BooleanField(default=False, verbose_name='Скидка действует по предоплате'),
        ),
        migrations.AddField(
            model_name='discount',
            name='pre_sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент скидки по предоплате'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.FloatField(verbose_name='Процент скидки'),
        ),
    ]
