# Generated by Django 5.0.7 on 2024-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0033_discount_is_tag_pre_sale_discount_pre_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='pre_sale',
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент скидки'),
        ),
    ]
