# Generated by Django 5.0.7 on 2024-07-26 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0034_remove_discount_pre_sale_alter_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproduct',
            name='autosave_tag',
            field=models.BooleanField(default=True, verbose_name='Автоматическая загрузка'),
        ),
        migrations.AlterField(
            model_name='suppliercategoryproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='suppliergroupproduct',
            name='autosave_tag',
            field=models.BooleanField(default=True, verbose_name='Автоматическая загрузка'),
        ),
        migrations.AlterField(
            model_name='suppliergroupproduct',
            name='category_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliercategoryproduct', verbose_name='Категория поставщика'),
        ),
        migrations.AlterField(
            model_name='suppliergroupproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
    ]
