# Generated by Django 5.1.2 on 2024-11-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0035_alter_supplier_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик`'),
        ),
    ]
