# Generated by Django 5.1.2 on 2024-11-29 05:21

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0036_alter_vendor_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='img',
            field=models.ImageField(null=True, upload_to=apps.core.utils_web.get_file_path_catalog_web, verbose_name='Изображение'),
        ),
    ]
