# Generated by Django 5.1.2 on 2024-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0037_vendor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_view_index_web',
            field=models.BooleanField(default=False, verbose_name='Отображение на главной сайта'),
        ),
    ]
