# Generated by Django 5.1.4 on 2024-12-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0038_vendor_is_view_index_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
