# Generated by Django 5.1.4 on 2024-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0039_vendor_article_alter_vendor_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name_web',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название на сайте'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название производителя'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
