# Generated by Django 5.1.4 on 2024-12-09 06:56

import apps.core.utils_web
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0040_vendor_name_web_alter_vendor_name_alter_vendor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils_web.get_file_path_catalog_web, validators=[apps.core.validators.validate_file_extension_image], verbose_name='Изображение'),
        ),
    ]
