# Generated by Django 5.1.5 on 2025-01-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0041_alter_vendor_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='supplier',
        ),
    ]
