# Generated by Django 5.1.5 on 2025-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0042_remove_vendor_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='is_correct',
            field=models.BooleanField(default=True, verbose_name='Группа есть в каталоге'),
        ),
    ]
