# Generated by Django 5.1.5 on 2025-02-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0043_suppliercategoryproductall_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='is_need',
            field=models.BooleanField(default=True, verbose_name='Неоюходима для загрузки в окт'),
        ),
    ]
