# Generated by Django 5.1.5 on 2025-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0044_suppliercategoryproductall_is_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPromoGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название промогруппы')),
            ],
        ),
    ]
