# Generated by Django 5.1.5 on 2025-05-27 10:22

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0044_suppliercategoryproductall_is_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=apps.core.utils.get_file_price_path_add, verbose_name='Архив с прайсами'),
        ),
    ]
