# Generated by Django 5.1.5 on 2025-06-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0045_supplierpromogroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpromogroupe',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
