# Generated by Django 5.1.5 on 2025-06-18 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0046_supplierpromogroupe_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='promo_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplierpromogroupe', verbose_name='Промо группа'),
        ),
    ]
