# Generated by Django 5.1.5 on 2025-06-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0047_discount_promo_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpromogroupe',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='supplierpromogroupe',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название промо группы'),
        ),
    ]
