# Generated by Django 5.1.5 on 2025-06-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0048_supplierpromogroupe_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpromogroupe',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.vendor', verbose_name='Производитель'),
        ),
    ]
