# Generated by Django 5.1.5 on 2025-06-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0049_alter_supplierpromogroupe_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierpromogroupe',
            options={'verbose_name': 'Промо группы', 'verbose_name_plural': 'Промо группы'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
    ]
