# Generated by Django 5.1.5 on 2025-07-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0045_alter_supplier_file'),
        ('supplier', '0050_alter_supplierpromogroupe_options_and_more'),
    ]

    operations = [
    ]
