# Generated by Django 5.1.5 on 2025-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0050_alter_supplierpromogroupe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='article_filter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность в фильтре'),
        ),
    ]
