# Generated by Django 5.1.5 on 2025-07-28 12:15

import apps.core.utils_web
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0051_vendor_article_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='promo_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст промо'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils_web.get_file_path_catalog_web, validators=[apps.core.validators.validate_file_extension_image], verbose_name='Изображение для промо блока'),
        ),
    ]
