# Generated by Django 5.1.5 on 2025-07-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0051_merge_20250701_1019'),
        ('supplier', '0051_vendor_article_filter'),
    ]

    operations = [
    ]
