# Generated by Django 5.1.5 on 2025-07-28 12:23

import apps.core.utils_web
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0052_vendor_promo_text_alter_vendor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='img_promo',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils_web.get_file_path_catalog_web, validators=[apps.core.validators.validate_file_extension_image], verbose_name='Изображение для промо блока'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils_web.get_file_path_catalog_web, validators=[apps.core.validators.validate_file_extension_image], verbose_name='Изображение'),
        ),
    ]
