# Generated by Django 5.1.5 on 2025-07-28 12:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0053_vendor_img_promo_alter_vendor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='promo_text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Общее описание'),
        ),
    ]
