# Generated by Django 5.1.5 on 2025-07-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0052_merge_20250724_1343'),
        ('supplier', '0054_alter_vendor_promo_text'),
    ]

    operations = [
    ]
