# Generated by Django 5.1.5 on 2025-08-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0055_merge_20250730_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategoryproduct',
            name='is_view_website',
            field=models.BooleanField(default=True, verbose_name='Видимость на сайте товаров раздела'),
        ),
        migrations.AddField(
            model_name='suppliercategoryproductall',
            name='is_view_website',
            field=models.BooleanField(default=True, verbose_name='Видимость на сайте товаров раздела'),
        ),
        migrations.AddField(
            model_name='suppliergroupproduct',
            name='is_view_website',
            field=models.BooleanField(default=True, verbose_name='Видимость на сайте товаров раздела'),
        ),
    ]
