# Generated by Django 5.0.5 on 2024-05-08 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_initial'),
        ('user', '0002_alter_adminuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsProductChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название производителя')),
                ('type_logs', models.CharField(choices=[('changed', 'Изменил'), ('null', 'Нет значения'), ('error', 'Ошибка при загрузке')], default='null', max_length=7)),
                ('name_field', models.CharField(max_length=30, verbose_name='поле в модели в которой произошло событие лога')),
                ('old_value', models.CharField(max_length=130, verbose_name='старое значение')),
                ('new_value', models.CharField(max_length=130, verbose_name='новое значение')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.adminuser', verbose_name='администратор')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
