# Generated by Django 5.0.6 on 2024-05-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logserror'),
    ]

    operations = [
        migrations.AddField(
            model_name='logserror',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='инфо о ошибку'),
        ),
        migrations.AddField(
            model_name='logserror',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='место ошибки'),
        ),
    ]
