# Generated by Django 5.0.6 on 2024-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_logserror_info_logserror_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logserror',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='инфо о ошибкe'),
        ),
        migrations.AlterField(
            model_name='logserror',
            name='type_error',
            field=models.CharField(choices=[('file_structure_error', 'фаил не соответствует нужной структуре'), ('file_api_error', 'фаил не соответствует нужной структуре'), ('error', 'Ошибка')], default='error', max_length=20),
        ),
    ]
