# Generated by Django 5.0.6 on 2024-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_logserror_info_alter_logserror_type_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logserror',
            name='info',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='инфо о ошибкe'),
        ),
        migrations.AlterField(
            model_name='logserror',
            name='type_error',
            field=models.CharField(choices=[('file_structure_error', 'фаил не соответствует нужной структуре'), ('file_api_error', 'ошибка при загрузке с api'), ('error', 'Ошибка')], default='error', max_length=20),
        ),
    ]
