# Generated by Django 5.0.7 on 2024-07-24 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_logserror_info_alter_logserror_type_error'),
        ('product', '0100_remove_historicalproduct_check_document_upgrade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logserror',
            name='info',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Инфо о ошибке'),
        ),
        migrations.AlterField(
            model_name='logserror',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место ошибки'),
        ),
        migrations.AlterField(
            model_name='logsproductchange',
            name='name_field',
            field=models.CharField(max_length=30, verbose_name='Поле в модели в которой произошло событие лога'),
        ),
        migrations.AlterField(
            model_name='logsproductchange',
            name='new_value',
            field=models.CharField(max_length=130, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='logsproductchange',
            name='old_value',
            field=models.CharField(max_length=130, verbose_name='Старое значение'),
        ),
        migrations.AlterField(
            model_name='logsproductchange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='logsproductchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
    ]
