# Generated by Django 5.0.7 on 2024-07-31 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_logserror_info_alter_logserror_location_and_more'),
        ('user', '0006_alter_adminuser_admin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsproductchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.adminuser', verbose_name='Администратор'),
        ),
    ]
