# Generated by Django 5.1.1 on 2024-10-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_logsproductchange_user'),
        ('product', '0121_alter_historicalstock_data_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsAddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата добавления')),
                ('info', models.CharField(blank=True, max_length=400, null=True, verbose_name='Инфо')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Лог добавления товара',
                'verbose_name_plural': 'Логи добавления товара',
            },
        ),
    ]
