# Generated by Django 5.1.4 on 2025-01-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_logsinfoerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logserror',
            name='info',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Инфо о ошибке'),
        ),
    ]
