# Generated by Django 5.1.5 on 2025-03-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_logsaddproduct_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsinfoerror',
            name='info',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Инфо о ошибке'),
        ),
        migrations.AlterField(
            model_name='logsordererror',
            name='info',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Инфо о ошибке'),
        ),
    ]
