# Generated by Django 5.1.5 on 2025-04-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_alter_logsinfoerror_info_alter_logsordererror_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsaddproduct',
            name='info',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Инфо'),
        ),
        migrations.AlterField(
            model_name='logsinfoerror',
            name='info',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Инфо о ошибке'),
        ),
        migrations.AlterField(
            model_name='logsordererror',
            name='info',
            field=models.CharField(blank=True, max_length=200000, null=True, verbose_name='Инфо о ошибке'),
        ),
    ]
