from django.test import TestCase

# Create your tests here.
{
    "id": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "ID",
        "upperName": "ID",
    },
    "title": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Название",
        "upperName": "TITLE",
    },
    "xmlId": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Внешний код",
        "upperName": "XML_ID",
    },
    "createdTime": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Когда создан",
        "upperName": "CREATED_TIME",
    },
    "updatedTime": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Когда обновлён",
        "upperName": "UPDATED_TIME",
    },
    "createdBy": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Кем создан",
        "upperName": "CREATED_BY",
    },
    "updatedBy": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Кем обновлён",
        "upperName": "UPDATED_BY",
    },
    "assignedById": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Ответственный",
        "upperName": "ASSIGNED_BY_ID",
    },
    "opened": {
        "type": "boolean",
        "isRequired": True,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Доступно для всех",
        "upperName": "OPENED",
    },
    "webformId": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Создано CRM-формой",
        "upperName": "WEBFORM_ID",
    },
    "begindate": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата выставления",
        "upperName": "BEGINDATE",
    },
    "closedate": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Срок оплаты",
        "settings": {"isSetCurrentDateOnCompletionEnabled": False},
        "upperName": "CLOSEDATE",
    },
    "companyId": {
        "type": "crm_company",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Компания",
        "settings": {"parentEntityTypeId": 4},
        "upperName": "COMPANY_ID",
    },
    "contactId": {
        "type": "crm_contact",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "isDeprecated": True,
        "title": "Контакт",
        "upperName": "CONTACT_ID",
    },
    "contactIds": {
        "type": "crm_contact",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": False,
        "title": "CONTACT_IDS",
        "upperName": "CONTACT_IDS",
    },
    "contacts": {
        "type": "crm_contact",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": False,
        "title": "CONTACTS",
        "upperName": "CONTACTS",
    },
    "observers": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": False,
        "title": "Наблюдатели",
        "upperName": "OBSERVERS",
    },
    "categoryId": {
        "type": "crm_category",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Воронка",
        "upperName": "CATEGORY_ID",
    },
    "movedTime": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Когда передвинут",
        "upperName": "MOVED_TIME",
    },
    "movedBy": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Кем передвинут",
        "upperName": "MOVED_BY",
    },
    "stageId": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "SMART_INVOICE_STAGE_2",
        "title": "Стадия",
        "upperName": "STAGE_ID",
    },
    "previousStageId": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "SMART_INVOICE_STAGE_2",
        "title": "Предыдущая стадия",
        "upperName": "PREVIOUS_STAGE_ID",
    },
    "sourceId": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "SOURCE",
        "title": "Источник",
        "upperName": "SOURCE_ID",
    },
    "sourceDescription": {
        "type": "text",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дополнительно об источнике",
        "upperName": "SOURCE_DESCRIPTION",
    },
    "currencyId": {
        "type": "crm_currency",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Валюта",
        "upperName": "CURRENCY_ID",
    },
    "isManualOpportunity": {
        "type": "boolean",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Режим расчёта суммы",
        "upperName": "IS_MANUAL_OPPORTUNITY",
    },
    "opportunity": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Сумма",
        "upperName": "OPPORTUNITY",
    },
    "taxValue": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Сумма налога",
        "upperName": "TAX_VALUE",
    },
    "mycompanyId": {
        "type": "crm_company",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Реквизиты вашей компании",
        "settings": {
            "isMyCompany": True,
            "parentEntityTypeId": 4,
            "isEmbeddedEditorEnabled": True,
        },
        "upperName": "MYCOMPANY_ID",
    },
    "lastActivityBy": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Кем осуществлена последняя активность в таймлайне",
        "upperName": "LAST_ACTIVITY_BY",
    },
    "lastActivityTime": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Последняя активность",
        "upperName": "LAST_ACTIVITY_TIME",
    },
    "comments": {
        "type": "text",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Комментарий",
        "settings": {"isFlexibleContentType": True},
        "upperName": "COMMENTS",
    },
    "accountNumber": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Номер счёта",
        "settings": {
            "numeratorType": "CRM_SMART_INVOICE",
            "numeratorIdSettings": "ID",
            "tableClassName": "\\crm_items_2Table",
        },
        "upperName": "ACCOUNT_NUMBER",
    },
    "locationId": {
        "type": "location",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Местоположение",
        "upperName": "LOCATION_ID",
    },
    "parentId2": {
        "type": "crm_entity",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Сделка",
        "settings": {"parentEntityTypeId": 2},
        "upperName": "PARENT_ID_2",
    },
    "parentId7": {
        "type": "crm_entity",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Предложение",
        "settings": {"parentEntityTypeId": 7},
        "upperName": "PARENT_ID_7",
    },
    "ufCrm_SMART_INVOICE_1733823834223": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "СПецифцикация",
        "listLabel": "СПецифцикация",
        "formLabel": "СПецифцикация",
        "filterLabel": "СПецифцикация",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
        "upperName": "UF_CRM_SMART_INVOICE_1733823834223",
    },
    "ufCrm_SMART_INVOICE_1733824789005": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "Новый файл",
        "listLabel": "Новый файл",
        "formLabel": "Новый файл",
        "filterLabel": "Новый файл",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
        "upperName": "UF_CRM_SMART_INVOICE_1733824789005",
    },
    "ufCrm_SMART_INVOICE_1733833332156": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "Новая сумма",
        "listLabel": "Новая сумма",
        "formLabel": "Новая сумма",
        "filterLabel": "Новая сумма",
        "settings": {"DEFAULT_VALUE": ""},
        "upperName": "UF_CRM_SMART_INVOICE_1733833332156",
    },
    "ufCrm_SMART_INVOICE_1733894845996": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "Фаил счета",
        "listLabel": "Фаил счета",
        "formLabel": "Фаил счета",
        "filterLabel": "Фаил счета",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
        "upperName": "UF_CRM_SMART_INVOICE_1733894845996",
    },
    "ufCrm_6762C06D41042": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "Счет",
        "listLabel": "Счет",
        "formLabel": "Счет",
        "filterLabel": "Счет",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
        "upperName": "UF_CRM_6762C06D41042",
    },
    "ufCrm_6762C06E05A6B": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "Счет без печати",
        "listLabel": "Счет без печати",
        "formLabel": "Счет без печати",
        "filterLabel": "Счет без печати",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
        "upperName": "UF_CRM_6762C06E05A6B",
    },
    "ufCrm_6762C06EAB29C": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "Новая строка",
        "listLabel": "Новая строка",
        "formLabel": "Новая строка",
        "filterLabel": "Новая строка",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
        "upperName": "UF_CRM_6762C06EAB29C",
    },
    "ufCrm_6762C06F4F0E3": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "Спецификация",
        "listLabel": "Спецификация",
        "formLabel": "Спецификация",
        "filterLabel": "Спецификация",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
        "upperName": "UF_CRM_6762C06F4F0E3",
    },
    "ufCrm_6762C06F5A823": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "Оплачено",
        "listLabel": "Оплачено",
        "formLabel": "Оплачено",
        "filterLabel": "Оплачено",
        "settings": {"DEFAULT_VALUE": ""},
        "upperName": "UF_CRM_6762C06F5A823",
    },
    "ufCrm_6762C0705C3E8": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "Отгрузка",
        "listLabel": "Отгрузка",
        "formLabel": "Отгрузка",
        "filterLabel": "Отгрузка",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
        "upperName": "UF_CRM_6762C0705C3E8",
    },
    "ufCrm_6762C070EF6C3": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "Новая сумма",
        "listLabel": "Новая сумма",
        "formLabel": "Новая сумма",
        "filterLabel": "Новая сумма",
        "settings": {"DEFAULT_VALUE": ""},
        "upperName": "UF_CRM_6762C070EF6C3",
    },
    "ufCrm_6762C071072AB": {
        "type": "url",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "Новое поле",
        "listLabel": "Новое поле",
        "formLabel": "Новое поле",
        "filterLabel": "Новое поле",
        "settings": {
            "POPUP": "Y",
            "SIZE": 20,
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
            "ROWS": 1,
        },
        "upperName": "UF_CRM_6762C071072AB",
    },
    "ufCrm_6762C07111CC5": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "Задолженность",
        "listLabel": "Задолженность",
        "formLabel": "Задолженность",
        "filterLabel": "Задолженность",
        "settings": {"DEFAULT_VALUE": ""},
        "upperName": "UF_CRM_6762C07111CC5",
    },
    "ufCrm_6762C07DB8B76": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "Оплачено ",
        "listLabel": "Оплачено ",
        "formLabel": "Оплачено ",
        "filterLabel": "Оплачено ",
        "settings": {"DEFAULT_VALUE": ""},
        "upperName": "UF_CRM_6762C07DB8B76",
    },
}




















{
    "ID": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "ID",
    },
    "TITLE": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Название",
    },
    "TYPE_ID": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "DEAL_TYPE",
        "title": "Тип",
    },
    "CATEGORY_ID": {
        "type": "crm_category",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": True,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Воронка",
    },
    "STAGE_ID": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "DEAL_STAGE",
        "title": "Стадия сделки",
    },
    "STAGE_SEMANTIC_ID": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Группа стадии",
    },
    "IS_NEW": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Новая сделка",
    },
    "IS_RECURRING": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Регулярная сделка",
    },
    "IS_RETURN_CUSTOMER": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Повторная сделка",
    },
    "IS_REPEATED_APPROACH": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Повторное обращение",
    },
    "PROBABILITY": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Вероятность",
    },
    "CURRENCY_ID": {
        "type": "crm_currency",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Валюта",
    },
    "OPPORTUNITY": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Сумма",
    },
    "IS_MANUAL_OPPORTUNITY": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "IS_MANUAL_OPPORTUNITY",
    },
    "TAX_VALUE": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Ставка налога",
    },
    "COMPANY_ID": {
        "type": "crm_company",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Компания",
        "settings": {"parentEntityTypeId": 4},
    },
    "CONTACT_ID": {
        "type": "crm_contact",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "isDeprecated": True,
        "title": "Контакт",
    },
    "CONTACT_IDS": {
        "type": "crm_contact",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": False,
        "title": "Контакты",
    },
    "QUOTE_ID": {
        "type": "crm_quote",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Предложение",
        "settings": {"parentEntityTypeId": 7},
    },
    "BEGINDATE": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата начала",
    },
    "CLOSEDATE": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата завершения",
    },
    "OPENED": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Доступна для всех",
    },
    "CLOSED": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Закрыта",
    },
    "COMMENTS": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Комментарий",
    },
    "ASSIGNED_BY_ID": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Ответственный",
    },
    "CREATED_BY_ID": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Кем создана",
    },
    "MODIFY_BY_ID": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Кем изменена",
    },
    "MOVED_BY_ID": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "MOVED_BY_ID",
    },
    "DATE_CREATE": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата создания",
    },
    "DATE_MODIFY": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата изменения",
    },
    "MOVED_TIME": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "MOVED_TIME",
    },
    "SOURCE_ID": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "SOURCE",
        "title": "Источник",
    },
    "SOURCE_DESCRIPTION": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дополнительно об источнике",
    },
    "LEAD_ID": {
        "type": "crm_lead",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Лид",
        "settings": {"parentEntityTypeId": 1},
    },
    "ADDITIONAL_INFO": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дополнительная информация",
    },
    "LOCATION_ID": {
        "type": "location",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Местоположение",
    },
    "ORIGINATOR_ID": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Внешний источник",
    },
    "ORIGIN_ID": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Идентификатор элемента во внешнем источнике",
    },
    "UTM_SOURCE": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Рекламная система",
    },
    "UTM_MEDIUM": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Тип трафика",
    },
    "UTM_CAMPAIGN": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Обозначение рекламной кампании",
    },
    "UTM_CONTENT": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Содержание кампании",
    },
    "UTM_TERM": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Условие поиска кампании",
    },
    "LAST_ACTIVITY_TIME": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "LAST_ACTIVITY_TIME",
    },
    "LAST_ACTIVITY_BY": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "LAST_ACTIVITY_BY",
    },
    "UF_CRM_1734090309747": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734090309747",
        "listLabel": "Счет",
        "formLabel": "Счет",
        "filterLabel": "Счет",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734092945325": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734092945325",
        "listLabel": "Счет без печати",
        "formLabel": "Счет без печати",
        "filterLabel": "Счет без печати",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734092979832": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734092979832",
        "listLabel": "Новая строка",
        "formLabel": "Новая строка",
        "filterLabel": "Новая строка",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_1734093516769": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734093516769",
        "listLabel": "Спецификация",
        "formLabel": "Спецификация",
        "filterLabel": "Спецификация",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734333862277": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734333862277",
        "listLabel": "Оплачено",
        "formLabel": "Оплачено",
        "filterLabel": "Оплачено",
        "settings": {"DEFAULT_VALUE": ""},
    },
    "UF_CRM_1734415812339": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734415812339",
        "listLabel": "Счет",
        "formLabel": "Счет",
        "filterLabel": "Счет",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734415838099": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734415838099",
        "listLabel": "Счет без печати",
        "formLabel": "Счет без печати",
        "filterLabel": "Счет без печати",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734415853669": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734415853669",
        "listLabel": "Спецификация",
        "formLabel": "Спецификация",
        "filterLabel": "Спецификация",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734415894538": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734415894538",
        "listLabel": "Отгрузка",
        "formLabel": "Отгрузка",
        "filterLabel": "Отгрузка",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734415955549": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734415955549",
        "listLabel": "Новая сумма",
        "formLabel": "Новая сумма",
        "filterLabel": "Новая сумма",
        "settings": {"DEFAULT_VALUE": ""},
    },
    "UF_CRM_1734516080010": {
        "type": "url",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734516080010",
        "listLabel": "Новое поле",
        "formLabel": "Новое поле",
        "filterLabel": "Новое поле",
        "settings": {
            "POPUP": "Y",
            "SIZE": 20,
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
            "ROWS": 1,
        },
    },
    "UF_CRM_1734523467813": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734523467813",
        "listLabel": "Оплачено ",
        "formLabel": "Оплачено ",
        "filterLabel": "Оплачено ",
        "settings": {"DEFAULT_VALUE": ""},
    },
    "UF_CRM_1734523482619": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734523482619",
        "listLabel": "Задолженность",
        "formLabel": "Задолженность",
        "filterLabel": "Задолженность",
        "settings": {"DEFAULT_VALUE": ""},
    },
}
{
  "id_bitrix": 22,
  "admin_creator_id": "25",
  "products": [
    {
      "product_id": 72018,
      "quantity": 1,
      "price_exclusive": 0,
      "price_one": 4074,
      "product_specif_id": "None",
      "extra_discount": "",
      "date_delivery": "2025-03-03",
      "text_delivery": "2 недели",
      "product_name_new": "",
      "product_new_article": "",
      "comment": null,
      "sale_motrum": "50,0",
      "vendor": null,
      "id_cart": "827"
    }
  ],
  "id_specification": null,
  "id_cart": 325,
  "comment": "",
  "date_delivery": "2 недели",
  "motrum_requisites": 1,
  "client_requisites": 15,
  "type_delivery": "1",
  "type_save": "bill",
  "post_update": false
}