# [
#     {
#         "ID": "1",
#         "ENTITY_ID": "STATUS",
#         "STATUS_ID": "NEW",
#         "NAME": "Не обработан",
#         "NAME_INIT": "Не обработан",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": "#39A8EF",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#39A8EF"},
#     },
#     {
#         "ID": "3",
#         "ENTITY_ID": "STATUS",
#         "STATUS_ID": "IN_PROCESS",
#         "NAME": "В работе",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": "#2FC6F6",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#2FC6F6"},
#     },
#     {
#         "ID": "5",
#         "ENTITY_ID": "STATUS",
#         "STATUS_ID": "PROCESSED",
#         "NAME": "Обработан",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": "#55D0E0",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#55D0E0"},
#     },
#     {
#         "ID": "7",
#         "ENTITY_ID": "STATUS",
#         "STATUS_ID": "CONVERTED",
#         "NAME": "Качественный лид",
#         "NAME_INIT": "Качественный лид",
#         "SORT": "40",
#         "SYSTEM": "Y",
#         "COLOR": "#7BD500",
#         "SEMANTICS": "S",
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "success", "COLOR": "#7BD500"},
#     },
#     {
#         "ID": "9",
#         "ENTITY_ID": "STATUS",
#         "STATUS_ID": "JUNK",
#         "NAME": "Некачественный лид",
#         "NAME_INIT": "Некачественный лид",
#         "SORT": "50",
#         "SYSTEM": "Y",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "failure", "COLOR": "#FF5752"},
#     },
#     {
#         "ID": "11",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "CALL",
#         "NAME": "Звонок",
#         "NAME_INIT": "Звонок",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "13",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "EMAIL",
#         "NAME": "Электронная почта",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "15",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "WEB",
#         "NAME": "Веб-сайт",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "17",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "ADVERTISING",
#         "NAME": "Реклама",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "19",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "PARTNER",
#         "NAME": "Существующий клиент",
#         "NAME_INIT": "",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "21",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "RECOMMENDATION",
#         "NAME": "По рекомендации",
#         "NAME_INIT": "",
#         "SORT": "60",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "23",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "TRADE_SHOW",
#         "NAME": "Выставка",
#         "NAME_INIT": "",
#         "SORT": "70",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "25",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "WEBFORM",
#         "NAME": "CRM-форма",
#         "NAME_INIT": "CRM-форма",
#         "SORT": "75",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "27",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "CALLBACK",
#         "NAME": "Обратный звонок",
#         "NAME_INIT": "Обратный звонок",
#         "SORT": "77",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "29",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "RC_GENERATOR",
#         "NAME": "Генератор продаж",
#         "NAME_INIT": "Генератор продаж",
#         "SORT": "78",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "31",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "STORE",
#         "NAME": "Интернет-магазин",
#         "NAME_INIT": "Интернет-магазин",
#         "SORT": "79",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "33",
#         "ENTITY_ID": "SOURCE",
#         "STATUS_ID": "OTHER",
#         "NAME": "Другое",
#         "NAME_INIT": "",
#         "SORT": "80",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "35",
#         "ENTITY_ID": "CONTACT_TYPE",
#         "STATUS_ID": "CLIENT",
#         "NAME": "Клиенты",
#         "NAME_INIT": "",
#         "SORT": "10",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "37",
#         "ENTITY_ID": "CONTACT_TYPE",
#         "STATUS_ID": "SUPPLIER",
#         "NAME": "Поставщики",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "39",
#         "ENTITY_ID": "CONTACT_TYPE",
#         "STATUS_ID": "PARTNER",
#         "NAME": "Партнеры",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "41",
#         "ENTITY_ID": "CONTACT_TYPE",
#         "STATUS_ID": "OTHER",
#         "NAME": "Другое",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "43",
#         "ENTITY_ID": "COMPANY_TYPE",
#         "STATUS_ID": "CUSTOMER",
#         "NAME": "Клиент",
#         "NAME_INIT": "",
#         "SORT": "10",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "45",
#         "ENTITY_ID": "COMPANY_TYPE",
#         "STATUS_ID": "SUPPLIER",
#         "NAME": "Поставщик",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "47",
#         "ENTITY_ID": "COMPANY_TYPE",
#         "STATUS_ID": "COMPETITOR",
#         "NAME": "Конкурент",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "49",
#         "ENTITY_ID": "COMPANY_TYPE",
#         "STATUS_ID": "PARTNER",
#         "NAME": "Партнер",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "51",
#         "ENTITY_ID": "COMPANY_TYPE",
#         "STATUS_ID": "OTHER",
#         "NAME": "Другое",
#         "NAME_INIT": "",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "53",
#         "ENTITY_ID": "EMPLOYEES",
#         "STATUS_ID": "EMPLOYEES_1",
#         "NAME": "менее 50",
#         "NAME_INIT": "менее 50",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "55",
#         "ENTITY_ID": "EMPLOYEES",
#         "STATUS_ID": "EMPLOYEES_2",
#         "NAME": "50-250",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "57",
#         "ENTITY_ID": "EMPLOYEES",
#         "STATUS_ID": "EMPLOYEES_3",
#         "NAME": "250-500",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "59",
#         "ENTITY_ID": "EMPLOYEES",
#         "STATUS_ID": "EMPLOYEES_4",
#         "NAME": "более 500",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "61",
#         "ENTITY_ID": "CALL_LIST",
#         "STATUS_ID": "IN_WORK",
#         "NAME": "В работе",
#         "NAME_INIT": "В работе",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "63",
#         "ENTITY_ID": "CALL_LIST",
#         "STATUS_ID": "SUCCESS",
#         "NAME": "Успешно",
#         "NAME_INIT": "Успешно",
#         "SORT": "20",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "65",
#         "ENTITY_ID": "CALL_LIST",
#         "STATUS_ID": "WRONG_NUMBER",
#         "NAME": "Неверный номер",
#         "NAME_INIT": "Неверный номер",
#         "SORT": "30",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "67",
#         "ENTITY_ID": "CALL_LIST",
#         "STATUS_ID": "STOP_CALLING",
#         "NAME": "Больше не звонить",
#         "NAME_INIT": "Больше не звонить",
#         "SORT": "40",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "69",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "IT",
#         "NAME": "Информационные технологии",
#         "NAME_INIT": "",
#         "SORT": "10",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "71",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "TELECOM",
#         "NAME": "Телекоммуникации и связь",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "73",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "MANUFACTURING",
#         "NAME": "Производство",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "75",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "BANKING",
#         "NAME": "Банковские услуги",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "77",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "CONSULTING",
#         "NAME": "Консалтинг",
#         "NAME_INIT": "",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "79",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "FINANCE",
#         "NAME": "Финансы",
#         "NAME_INIT": "",
#         "SORT": "60",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "81",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "GOVERNMENT",
#         "NAME": "Правительство",
#         "NAME_INIT": "",
#         "SORT": "70",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "83",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "DELIVERY",
#         "NAME": "Доставка",
#         "NAME_INIT": "",
#         "SORT": "80",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "85",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "ENTERTAINMENT",
#         "NAME": "Развлечения",
#         "NAME_INIT": "",
#         "SORT": "90",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "87",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "NOTPROFIT",
#         "NAME": "Не для получения прибыли",
#         "NAME_INIT": "",
#         "SORT": "100",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "89",
#         "ENTITY_ID": "INDUSTRY",
#         "STATUS_ID": "OTHER",
#         "NAME": "Другое",
#         "NAME_INIT": "Другое",
#         "SORT": "110",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "91",
#         "ENTITY_ID": "DEAL_TYPE",
#         "STATUS_ID": "SALE",
#         "NAME": "Продажа",
#         "NAME_INIT": "Продажа",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "93",
#         "ENTITY_ID": "DEAL_TYPE",
#         "STATUS_ID": "COMPLEX",
#         "NAME": "Комплексная продажа",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "95",
#         "ENTITY_ID": "DEAL_TYPE",
#         "STATUS_ID": "GOODS",
#         "NAME": "Продажа товара",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "97",
#         "ENTITY_ID": "DEAL_TYPE",
#         "STATUS_ID": "SERVICES",
#         "NAME": "Продажа услуги",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "99",
#         "ENTITY_ID": "DEAL_TYPE",
#         "STATUS_ID": "SERVICE",
#         "NAME": "Сервисное обслуживание",
#         "NAME_INIT": "",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "101",
#         "ENTITY_ID": "DEAL_STAGE",
#         "STATUS_ID": "NEW",
#         "NAME": "Новая",
#         "NAME_INIT": "Новая",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": "#39A8EF",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#39A8EF"},
#     },
#     {
#         "ID": "103",
#         "ENTITY_ID": "DEAL_STAGE",
#         "STATUS_ID": "PREPARATION",
#         "NAME": "Подготовка документов",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": "#2FC6F6",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#2FC6F6"},
#     },
#     {
#         "ID": "105",
#         "ENTITY_ID": "DEAL_STAGE",
#         "STATUS_ID": "PREPAYMENT_INVOICE",
#         "NAME": "Cчёт на предоплату",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": "#55D0E0",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#55D0E0"},
#     },
#     {
#         "ID": "107",
#         "ENTITY_ID": "DEAL_STAGE",
#         "STATUS_ID": "EXECUTING",
#         "NAME": "В работе",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": "#47E4C2",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#47E4C2"},
#     },
#     {
#         "ID": "109",
#         "ENTITY_ID": "DEAL_STAGE",
#         "STATUS_ID": "FINAL_INVOICE",
#         "NAME": "Финальный счёт",
#         "NAME_INIT": "",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": "#FFA900",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#FFA900"},
#     },
#     {
#         "ID": "111",
#         "ENTITY_ID": "DEAL_STAGE",
#         "STATUS_ID": "WON",
#         "NAME": "Сделка успешна",
#         "NAME_INIT": "Сделка успешна",
#         "SORT": "60",
#         "SYSTEM": "Y",
#         "COLOR": "#7BD500",
#         "SEMANTICS": "S",
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "success", "COLOR": "#7BD500"},
#     },
#     {
#         "ID": "113",
#         "ENTITY_ID": "DEAL_STAGE",
#         "STATUS_ID": "LOSE",
#         "NAME": "Сделка провалена",
#         "NAME_INIT": "Сделка провалена",
#         "SORT": "70",
#         "SYSTEM": "Y",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "failure", "COLOR": "#FF5752"},
#     },
#     {
#         "ID": "115",
#         "ENTITY_ID": "DEAL_STAGE",
#         "STATUS_ID": "APOLOGY",
#         "NAME": "Анализ причины провала",
#         "NAME_INIT": "",
#         "SORT": "80",
#         "SYSTEM": "N",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "apology", "COLOR": "#FF5752"},
#     },
#     {
#         "ID": "117",
#         "ENTITY_ID": "DEAL_STATE",
#         "STATUS_ID": "PLANNED",
#         "NAME": "В планах",
#         "NAME_INIT": "",
#         "SORT": "10",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "119",
#         "ENTITY_ID": "DEAL_STATE",
#         "STATUS_ID": "PROCESS",
#         "NAME": "В работе",
#         "NAME_INIT": "В работе",
#         "SORT": "20",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "121",
#         "ENTITY_ID": "DEAL_STATE",
#         "STATUS_ID": "COMPLETE",
#         "NAME": "Выполнена",
#         "NAME_INIT": "Выполнена",
#         "SORT": "30",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "123",
#         "ENTITY_ID": "DEAL_STATE",
#         "STATUS_ID": "CANCELED",
#         "NAME": "Отменена",
#         "NAME_INIT": "Отменена",
#         "SORT": "40",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "125",
#         "ENTITY_ID": "EVENT_TYPE",
#         "STATUS_ID": "INFO",
#         "NAME": "Информация",
#         "NAME_INIT": "Информация",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "127",
#         "ENTITY_ID": "EVENT_TYPE",
#         "STATUS_ID": "PHONE",
#         "NAME": "Телефонный звонок",
#         "NAME_INIT": "Телефонный звонок",
#         "SORT": "20",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "129",
#         "ENTITY_ID": "EVENT_TYPE",
#         "STATUS_ID": "MESSAGE",
#         "NAME": "Отправлен email",
#         "NAME_INIT": "Отправлен email",
#         "SORT": "30",
#         "SYSTEM": "Y",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "131",
#         "ENTITY_ID": "QUOTE_STATUS",
#         "STATUS_ID": "DRAFT",
#         "NAME": "Новое",
#         "NAME_INIT": "Новое",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": "#39A8EF",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#39A8EF"},
#     },
#     {
#         "ID": "133",
#         "ENTITY_ID": "QUOTE_STATUS",
#         "STATUS_ID": "SENT",
#         "NAME": "Отправлено клиенту",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": "#2FC6F6",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#2FC6F6"},
#     },
#     {
#         "ID": "135",
#         "ENTITY_ID": "QUOTE_STATUS",
#         "STATUS_ID": "APPROVED",
#         "NAME": "Принято",
#         "NAME_INIT": "Принято",
#         "SORT": "30",
#         "SYSTEM": "Y",
#         "COLOR": "#7BD500",
#         "SEMANTICS": "S",
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "success", "COLOR": "#7BD500"},
#     },
#     {
#         "ID": "137",
#         "ENTITY_ID": "QUOTE_STATUS",
#         "STATUS_ID": "DECLAINED",
#         "NAME": "Отклонено",
#         "NAME_INIT": "Отклонено",
#         "SORT": "40",
#         "SYSTEM": "Y",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "failure", "COLOR": "#FF5752"},
#     },
#     {
#         "ID": "139",
#         "ENTITY_ID": "QUOTE_STATUS",
#         "STATUS_ID": "APOLOGY",
#         "NAME": "Анализ причины отклонения",
#         "NAME_INIT": "",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "0",
#         "EXTRA": {"SEMANTICS": "apology", "COLOR": "#FF5752"},
#     },
#     {
#         "ID": "141",
#         "ENTITY_ID": "INVOICE_STATUS",
#         "STATUS_ID": "N",
#         "NAME": "Новый",
#         "NAME_INIT": "Новый",
#         "SORT": "100",
#         "SYSTEM": "Y",
#         "COLOR": "#39A8EF",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "143",
#         "ENTITY_ID": "INVOICE_STATUS",
#         "STATUS_ID": "S",
#         "NAME": "Отправлен клиенту",
#         "NAME_INIT": "",
#         "SORT": "110",
#         "SYSTEM": "N",
#         "COLOR": "#2FC6F6",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "145",
#         "ENTITY_ID": "INVOICE_STATUS",
#         "STATUS_ID": "P",
#         "NAME": "Оплачен",
#         "NAME_INIT": "Оплачен",
#         "SORT": "120",
#         "SYSTEM": "Y",
#         "COLOR": "#7BD500",
#         "SEMANTICS": "S",
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "147",
#         "ENTITY_ID": "INVOICE_STATUS",
#         "STATUS_ID": "D",
#         "NAME": "Не оплачен",
#         "NAME_INIT": "Не оплачен",
#         "SORT": "130",
#         "SYSTEM": "Y",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "149",
#         "ENTITY_ID": "HONORIFIC",
#         "STATUS_ID": "HNR_RU_1",
#         "NAME": "г-н",
#         "NAME_INIT": "",
#         "SORT": "10",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "151",
#         "ENTITY_ID": "HONORIFIC",
#         "STATUS_ID": "HNR_RU_2",
#         "NAME": "г-жа",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": None,
#         "SEMANTICS": None,
#         "CATEGORY_ID": "0",
#     },
#     {
#         "ID": "153",
#         "ENTITY_ID": "SMART_INVOICE_STAGE_3",
#         "STATUS_ID": "DT31_3:N",
#         "NAME": "Новый",
#         "NAME_INIT": "Новый",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": "#39A8EF",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "3",
#     },
#     {
#         "ID": "155",
#         "ENTITY_ID": "SMART_INVOICE_STAGE_3",
#         "STATUS_ID": "DT31_3:S",
#         "NAME": "Отправлен клиенту",
#         "NAME_INIT": "Отправлен клиенту",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": "#2FC6F6",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "3",
#     },
#     {
#         "ID": "157",
#         "ENTITY_ID": "SMART_INVOICE_STAGE_3",
#         "STATUS_ID": "DT31_3:P",
#         "NAME": "Оплачен",
#         "NAME_INIT": "Оплачен",
#         "SORT": "30",
#         "SYSTEM": "Y",
#         "COLOR": "#7BD500",
#         "SEMANTICS": "S",
#         "CATEGORY_ID": "3",
#     },
#     {
#         "ID": "159",
#         "ENTITY_ID": "SMART_INVOICE_STAGE_3",
#         "STATUS_ID": "DT31_3:D",
#         "NAME": "Не оплачен",
#         "NAME_INIT": "Не оплачен",
#         "SORT": "40",
#         "SYSTEM": "Y",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "3",
#     },
#     {
#         "ID": "161",
#         "ENTITY_ID": "SMART_DOCUMENT_STAGE_5",
#         "STATUS_ID": "DT36_5:DRAFT",
#         "NAME": "Черновик",
#         "NAME_INIT": "Черновик",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": "#00A9F4",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "5",
#     },
#     {
#         "ID": "163",
#         "ENTITY_ID": "SMART_DOCUMENT_STAGE_5",
#         "STATUS_ID": "DT36_5:PROCESSING",
#         "NAME": "На согласовании",
#         "NAME_INIT": "На согласовании",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": "#00C9FA",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "5",
#     },
#     {
#         "ID": "165",
#         "ENTITY_ID": "SMART_DOCUMENT_STAGE_5",
#         "STATUS_ID": "DT36_5:SENT",
#         "NAME": "Отправлен",
#         "NAME_INIT": "Отправлен",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": "#00D3E2",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "5",
#     },
#     {
#         "ID": "167",
#         "ENTITY_ID": "SMART_DOCUMENT_STAGE_5",
#         "STATUS_ID": "DT36_5:SEMISIGNED",
#         "NAME": "Частично подписан",
#         "NAME_INIT": "Частично подписан",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": "#FEA300",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "5",
#     },
#     {
#         "ID": "169",
#         "ENTITY_ID": "SMART_DOCUMENT_STAGE_5",
#         "STATUS_ID": "DT36_5:SIGNED",
#         "NAME": "Полностью подписан",
#         "NAME_INIT": "Полностью подписан",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": "#47E4C2",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "5",
#     },
#     {
#         "ID": "171",
#         "ENTITY_ID": "SMART_DOCUMENT_STAGE_5",
#         "STATUS_ID": "DT36_5:ARCHIVE",
#         "NAME": "В архив",
#         "NAME_INIT": "В архив",
#         "SORT": "60",
#         "SYSTEM": "N",
#         "COLOR": "#7BD500",
#         "SEMANTICS": "S",
#         "CATEGORY_ID": "5",
#     },
#     {
#         "ID": "173",
#         "ENTITY_ID": "SMART_DOCUMENT_STAGE_5",
#         "STATUS_ID": "DT36_5:NOTSIGNED",
#         "NAME": "Не подписано",
#         "NAME_INIT": "Не подписано",
#         "SORT": "70",
#         "SYSTEM": "Y",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "5",
#     },
#     {
#         "ID": "175",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:NEW",
#         "NAME": "Новая",
#         "NAME_INIT": "Новая",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": "#39A8EF",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#39A8EF"},
#     },
#     {
#         "ID": "177",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:PREPARATION",
#         "NAME": "МОТРУМ",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": "#2fc6f6",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#2fc6f6"},
#     },
#     {
#         "ID": "179",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:PREPAYMENT_INVOICE",
#         "NAME": "Cчёт на предоплату",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": "#55D0E0",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#55D0E0"},
#     },
#     {
#         "ID": "181",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:EXECUTING",
#         "NAME": "В работе",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": "#47E4C2",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#47E4C2"},
#     },
#     {
#         "ID": "183",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:FINAL_INVOICE",
#         "NAME": "Финальный счёт",
#         "NAME_INIT": "",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": "#FFA900",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#FFA900"},
#     },
#     {
#         "ID": "185",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:WON",
#         "NAME": "Сделка успешна",
#         "NAME_INIT": "Сделка успешна",
#         "SORT": "60",
#         "SYSTEM": "Y",
#         "COLOR": "#7BD500",
#         "SEMANTICS": "S",
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "success", "COLOR": "#7BD500"},
#     },
#     {
#         "ID": "187",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:LOSE",
#         "NAME": "Сделка провалена",
#         "NAME_INIT": "Сделка провалена",
#         "SORT": "70",
#         "SYSTEM": "Y",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "failure", "COLOR": "#FF5752"},
#     },
#     {
#         "ID": "189",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:APOLOGY",
#         "NAME": "Анализ причины провала",
#         "NAME_INIT": "",
#         "SORT": "80",
#         "SYSTEM": "N",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "apology", "COLOR": "#FF5752"},
#     },
#     {
#         "ID": "191",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:NEW",
#         "NAME": "Новая",
#         "NAME_INIT": "Новая",
#         "SORT": "10",
#         "SYSTEM": "Y",
#         "COLOR": "#39A8EF",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#39A8EF"},
#     },
#     {
#         "ID": "193",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:PREPARATION",
#         "NAME": "Подготовка документов",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": "#2FC6F6",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#2FC6F6"},
#     },
#     {
#         "ID": "195",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:PREPAYMENT_INVOICE",
#         "NAME": "МОТРУМ 2",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": "#55d0e0",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#55d0e0"},
#     },
#     {
#         "ID": "197",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:EXECUTING",
#         "NAME": "В работе",
#         "NAME_INIT": "",
#         "SORT": "40",
#         "SYSTEM": "N",
#         "COLOR": "#47E4C2",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#47E4C2"},
#     },
#     {
#         "ID": "199",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:FINAL_INVOICE",
#         "NAME": "Финальный счёт",
#         "NAME_INIT": "",
#         "SORT": "50",
#         "SYSTEM": "N",
#         "COLOR": "#FFA900",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#FFA900"},
#     },
#     {
#         "ID": "201",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:WON",
#         "NAME": "Сделка успешна",
#         "NAME_INIT": "Сделка успешна",
#         "SORT": "60",
#         "SYSTEM": "Y",
#         "COLOR": "#7BD500",
#         "SEMANTICS": "S",
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "success", "COLOR": "#7BD500"},
#     },
#     {
#         "ID": "203",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:LOSE",
#         "NAME": "Сделка провалена",
#         "NAME_INIT": "Сделка провалена",
#         "SORT": "70",
#         "SYSTEM": "Y",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "failure", "COLOR": "#FF5752"},
#     },
#     {
#         "ID": "205",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:APOLOGY",
#         "NAME": "Анализ причины провала",
#         "NAME_INIT": "",
#         "SORT": "80",
#         "SYSTEM": "N",
#         "COLOR": "#FF5752",
#         "SEMANTICS": "F",
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "apology", "COLOR": "#FF5752"},
#     },
# ]




# {
#         "ID": "177",
#         "ENTITY_ID": "DEAL_STAGE_1",
#         "STATUS_ID": "C1:PREPARATION",
#         "NAME": "МОТРУМ",
#         "NAME_INIT": "",
#         "SORT": "20",
#         "SYSTEM": "N",
#         "COLOR": "#2fc6f6",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "1",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#2fc6f6"},
#     },
#     {
#         "ID": "195",
#         "ENTITY_ID": "DEAL_STAGE_3",
#         "STATUS_ID": "C3:PREPAYMENT_INVOICE",
#         "NAME": "МОТРУМ 2",
#         "NAME_INIT": "",
#         "SORT": "30",
#         "SYSTEM": "N",
#         "COLOR": "#55d0e0",
#         "SEMANTICS": None,
#         "CATEGORY_ID": "3",
#         "EXTRA": {"SEMANTICS": "process", "COLOR": "#55d0e0"},
#     },
    
    
#     [{'ID': '175', 'ENTITY_ID': 'DEAL_STAGE_1', 'STATUS_ID': 'C1:NEW', 'NAME': 'Новая', 'NAME_INIT': 'Новая', 'SORT': '10', 'SYSTEM': 'Y', 'COLOR': '#39A8EF', 'SEMANTICS': None, 'CATEGORY_ID': '1', 'EXTRA': {'SEMANTICS': 'process', 'COLOR': '#39A8EF'}}, {'ID': '177', 'ENTITY_ID': 'DEAL_STAGE_1', 'STATUS_ID': 'C1:PREPARATION', 'NAME': 'МОТРУМ', 'NAME_INIT': '', 'SORT': '20', 'SYSTEM': 'N', 'COLOR': '#2fc6f6', 'SEMANTICS': None, 'CATEGORY_ID': '1', 'EXTRA': {'SEMANTICS': 'process', 'COLOR': '#2fc6f6'}}, {'ID': '179', 'ENTITY_ID': 'DEAL_STAGE_1', 'STATUS_ID': 'C1:PREPAYMENT_INVOICE', 'NAME': 'Cчёт на предоплату', 'NAME_INIT': '', 'SORT': '30', 'SYSTEM': 'N', 'COLOR': '#55D0E0', 'SEMANTICS': None, 'CATEGORY_ID': '1', 'EXTRA': {'SEMANTICS': 'process', 'COLOR': '#55D0E0'}}, {'ID': '181', 'ENTITY_ID': 'DEAL_STAGE_1', 'STATUS_ID': 'C1:EXECUTING', 'NAME': 'В работе', 'NAME_INIT': '', 'SORT': '40', 'SYSTEM': 'N', 'COLOR': '#47E4C2', 'SEMANTICS': None, 'CATEGORY_ID': '1', 'EXTRA': {'SEMANTICS': 'process', 'COLOR': '#47E4C2'}}, {'ID': '183', 'ENTITY_ID': 'DEAL_STAGE_1', 'STATUS_ID': 'C1:FINAL_INVOICE', 'NAME': 'Финальный счёт', 'NAME_INIT': '', 'SORT': '50', 'SYSTEM': 'N', 'COLOR': '#FFA900', 'SEMANTICS': None, 'CATEGORY_ID': '1', 'EXTRA': {'SEMANTICS': 'process', 'COLOR': '#FFA900'}}, {'ID': '185', 'ENTITY_ID': 'DEAL_STAGE_1', 'STATUS_ID': 'C1:WON', 'NAME': 'Сделка успешна', 'NAME_INIT': 'Сделка успешна', 'SORT': '60', 'SYSTEM': 'Y', 'COLOR': '#7BD500', 'SEMANTICS': 'S', 'CATEGORY_ID': '1', 'EXTRA': {'SEMANTICS': 'success', 'COLOR': '#7BD500'}}, {'ID': '187', 'ENTITY_ID': 'DEAL_STAGE_1', 'STATUS_ID': 'C1:LOSE', 'NAME': 'Сделка провалена', 'NAME_INIT': 'Сделка провалена', 'SORT': '70', 'SYSTEM': 'Y', 'COLOR': '#FF5752', 'SEMANTICS': 'F', 'CATEGORY_ID': '1', 'EXTRA': {'SEMANTICS': 'failure', 'COLOR': '#FF5752'}}, {'ID': '189', 'ENTITY_ID': 'DEAL_STAGE_1', 'STATUS_ID': 'C1:APOLOGY', 'NAME': 'Анализ причины провала', 'NAME_INIT': '', 'SORT': '80', 'SYSTEM': 'N', 'COLOR': '#FF5752', 'SEMANTICS': 'F', 'CATEGORY_ID': '1', 'EXTRA': {'SEMANTICS': 'apology', 'COLOR': '#FF5752'}}]