y = {
    "ID": "10568",
    "TITLE": "Тест сделка (НЕ ИСПОЛЬЗОВАТЬ)",
    "TYPE_ID": "SALE",
    "STAGE_ID": "C8:PREPARATION",
    "PROBABILITY": None,
    "CURRENCY_ID": "RUB",
    "OPPORTUNITY": "0.00",
    "IS_MANUAL_OPPORTUNITY": "N",
    "TAX_VALUE": "0.00",
    "LEAD_ID": None,
    "COMPANY_ID": "17682",
    "CONTACT_ID": None,
    "QUOTE_ID": None,
    "BEGINDATE": "2025-01-13T03:00:00+03:00",
    "CLOSEDATE": "2025-01-20T03:00:00+03:00",
    "ASSIGNED_BY_ID": "174",
    "CREATED_BY_ID": "174",
    "MODIFY_BY_ID": "0",
    "DATE_CREATE": "2025-01-13T09:13:43+03:00",
    "DATE_MODIFY": "2025-01-13T11:55:04+03:00",
    "OPENED": "Y",
    "CLOSED": "N",
    "COMMENTS": "",
    "ADDITIONAL_INFO": None,
    "LOCATION_ID": None,
    "CATEGORY_ID": "8",
    "STAGE_SEMANTIC_ID": "P",
    "IS_NEW": "N",
    "IS_RECURRING": "N",
    "IS_RETURN_CUSTOMER": "N",
    "IS_REPEATED_APPROACH": "N",
    "SOURCE_ID": "PARTNER",
    "SOURCE_DESCRIPTION": "",
    "ORIGINATOR_ID": None,
    "ORIGIN_ID": None,
    "MOVED_BY_ID": "174",
    "MOVED_TIME": "2025-01-13T10:58:36+03:00",
    "LAST_ACTIVITY_TIME": "2025-01-13T09:13:43+03:00",
    "UTM_SOURCE": None,
    "UTM_MEDIUM": None,
    "UTM_CAMPAIGN": None,
    "UTM_CONTENT": None,
    "UTM_TERM": None,
    "LAST_ACTIVITY_BY": "174",
    "UF_CRM_64DF51F58B5E6": "",
    "UF_CRM_65A757F01C1AF": "",
    "UF_CRM_1707370172020": "",
    "UF_CRM_1707370267190": "",
    "UF_CRM_1715001709654": "",
    "UF_CRM_1715001835565": "",
    "UF_CRM_1715001842582": "",
    "UF_CRM_1715001901852": "",
    "UF_CRM_1715001942471": "870",
    "UF_CRM_1715001968071": "",
    "UF_CRM_1715001976297": "2025-01-17T03:00:00+03:00",
    "UF_CRM_1715002007990": "878",
    "UF_CRM_1715002030562": "",
    "UF_CRM_1715002242287": "",
    "UF_CRM_1715002257633": [],
    "UF_CRM_1715002266121": "",
    "UF_CRM_1715002274449": "",
    "UF_CRM_1715002316": "",
    "UF_CRM_1715002375997": "",
    "UF_CRM_1715002396068": "",
    "UF_CRM_1715002427980": "",
    "UF_CRM_1715002449": "",
    "UF_CRM_1715002497107": "",
    "UF_CRM_1715002502730": "",
    "UF_CRM_1715002530901": "",
    "UF_CRM_1715002551": "",
    "UF_CRM_1715002572278": "",
    "UF_CRM_1715002579974": "",
    "UF_CRM_1715003632": "10568",
    "UF_CRM_1715171327856": "",
    "UF_CRM_1715616037876": "1358",
    "UF_CRM_1715704478969": "",
    "UF_CRM_1715704786788": "",
    "UF_CRM_1718022241494": "",
    "UF_CRM_1718022266092": "",
    "UF_CRM_666BEA3902BFA": "",
    "UF_CRM_1734772155723": "",
    "UF_CRM_1734772173389": "0|RUB",
    "UF_CRM_1734772516954": [],
    "UF_CRM_1734772537613": [],
    "UF_CRM_1734772575764": [],
    "UF_CRM_1734772618817": "",
}


t = {
    "ID": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "ID",
    },
    "TITLE": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Название",
    },
    "TYPE_ID": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "DEAL_TYPE",
        "title": "Тип",
    },
    "CATEGORY_ID": {
        "type": "crm_category",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": True,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Воронка",
    },
    "STAGE_ID": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "DEAL_STAGE",
        "title": "Стадия сделки",
    },
    "STAGE_SEMANTIC_ID": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Группа стадии",
    },
    "IS_NEW": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Новая сделка",
    },
    "IS_RECURRING": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Регулярная сделка",
    },
    "IS_RETURN_CUSTOMER": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Повторная сделка",
    },
    "IS_REPEATED_APPROACH": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Повторное обращение",
    },
    "PROBABILITY": {
        "type": "integer",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Вероятность",
    },
    "CURRENCY_ID": {
        "type": "crm_currency",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Валюта",
    },
    "OPPORTUNITY": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Сумма",
    },
    "IS_MANUAL_OPPORTUNITY": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "IS_MANUAL_OPPORTUNITY",
    },
    "TAX_VALUE": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Ставка налога",
    },
    "COMPANY_ID": {
        "type": "crm_company",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Компания",
        "settings": {"parentEntityTypeId": 4},
    },
    "CONTACT_ID": {
        "type": "crm_contact",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "isDeprecated": True,
        "title": "Контакт",
    },
    "CONTACT_IDS": {
        "type": "crm_contact",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": False,
        "title": "Контакты",
    },
    "QUOTE_ID": {
        "type": "crm_quote",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Предложение",
        "settings": {"parentEntityTypeId": 7},
    },
    "BEGINDATE": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата начала",
    },
    "CLOSEDATE": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата завершения",
    },
    "OPENED": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Доступна для всех",
    },
    "CLOSED": {
        "type": "char",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Закрыта",
    },
    "COMMENTS": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Комментарий",
    },
    "ASSIGNED_BY_ID": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Ответственный",
    },
    "CREATED_BY_ID": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Кем создана",
    },
    "MODIFY_BY_ID": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Кем изменена",
    },
    "MOVED_BY_ID": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "MOVED_BY_ID",
    },
    "DATE_CREATE": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата создания",
    },
    "DATE_MODIFY": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дата изменения",
    },
    "MOVED_TIME": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "MOVED_TIME",
    },
    "SOURCE_ID": {
        "type": "crm_status",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "statusType": "SOURCE",
        "title": "Источник",
    },
    "SOURCE_DESCRIPTION": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дополнительно об источнике",
    },
    "LEAD_ID": {
        "type": "crm_lead",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Лид",
        "settings": {"parentEntityTypeId": 1},
    },
    "ADDITIONAL_INFO": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Дополнительная информация",
    },
    "LOCATION_ID": {
        "type": "location",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Местоположение",
    },
    "ORIGINATOR_ID": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Внешний источник",
    },
    "ORIGIN_ID": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Идентификатор элемента во внешнем источнике",
    },
    "UTM_SOURCE": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Рекламная система",
    },
    "UTM_MEDIUM": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Тип трафика",
    },
    "UTM_CAMPAIGN": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Обозначение рекламной кампании",
    },
    "UTM_CONTENT": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Содержание кампании",
    },
    "UTM_TERM": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "Условие поиска кампании",
    },
    "LAST_ACTIVITY_TIME": {
        "type": "datetime",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "LAST_ACTIVITY_TIME",
    },
    "LAST_ACTIVITY_BY": {
        "type": "user",
        "isRequired": False,
        "isReadOnly": True,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": False,
        "title": "LAST_ACTIVITY_BY",
    },
    "UF_CRM_1691665383746": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1691665383746",
        "listLabel": "Новый файл",
        "formLabel": "Новый файл",
        "filterLabel": "Новый файл",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_64DF51F58B5E6": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "630", "VALUE": "Интернет (сайт)"},
            {"ID": "632", "VALUE": "Рекомендации"},
            {"ID": "634", "VALUE": "Рассылка"},
        ],
        "title": "UF_CRM_64DF51F58B5E6",
        "listLabel": "Новый список",
        "formLabel": "Новый список",
        "filterLabel": "Новый список",
        "settings": {
            "DISPLAY": "UI",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1692707034159": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1692707034159",
        "listLabel": "Новый файл",
        "formLabel": "Новый файл",
        "filterLabel": "Новый файл",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1692707062368": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1692707062368",
        "listLabel": "Новый файл",
        "formLabel": "Новый файл",
        "filterLabel": "Новый файл",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1693568214904": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1693568214904",
        "listLabel": "Новый файл",
        "formLabel": "Новый файл",
        "filterLabel": "Новый файл",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1701161033943": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1701161033943",
        "listLabel": "Новый файл",
        "formLabel": "Новый файл",
        "filterLabel": "Новый файл",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_65A757F01C1AF": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_65A757F01C1AF",
        "listLabel": "Способ привлечения (рассылка, чат и т.п.)",
        "formLabel": "Способ привлечения (рассылка, чат и т.п.)",
        "filterLabel": "Способ привлечения (рассылка, чат и т.п.)",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_1707370172020": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1707370172020",
        "listLabel": "Сумма закупки, руб.",
        "formLabel": "Сумма закупки, руб.",
        "filterLabel": "Сумма закупки, руб.",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_1707370267190": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1707370267190",
        "listLabel": "Маржинальность товара, руб. ",
        "formLabel": "Маржинальность товара, руб. ",
        "filterLabel": "Маржинальность товара, руб. ",
        "settings": {
            "PRECISION": 2,
            "SIZE": 20,
            "MIN_VALUE": 0,
            "MAX_VALUE": 0,
            "DEFAULT_VALUE": None,
        },
    },
    "UF_CRM_1715001709654": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "846", "VALUE": "Проектная продажа"},
            {"ID": "848", "VALUE": "ЗИП"},
            {"ID": "850", "VALUE": "Тендер"},
        ],
        "title": "UF_CRM_1715001709654",
        "listLabel": "Тип сделки Дистрибьюция",
        "formLabel": "Тип сделки Дистрибьюция",
        "filterLabel": "Тип сделки Дистрибьюция",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715001835565": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "852", "VALUE": "Роботы"},
            {"ID": "854", "VALUE": "Маркировка"},
            {"ID": "856", "VALUE": "Шкафы"},
            {"ID": "858", "VALUE": "Автоматизация"},
        ],
        "title": "UF_CRM_1715001835565",
        "listLabel": "Тип сделки Проекты",
        "formLabel": "Тип сделки Проекты",
        "filterLabel": "Тип сделки Проекты",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715001842582": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [{"ID": "860", "VALUE": "Да"}, {"ID": "862", "VALUE": "Нет"}],
        "title": "UF_CRM_1715001842582",
        "listLabel": "Коботы",
        "formLabel": "Коботы",
        "filterLabel": "Коботы",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715001901852": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "864", "VALUE": "Небольшой объем"},
            {"ID": "866", "VALUE": "Сложные условия работы с заказчиком"},
            {"ID": "868", "VALUE": "Нет времени для обработки заявки"},
            {"ID": "1376", "VALUE": "Не успели из-за крайне сжатых сроков"},
            {"ID": "1378", "VALUE": "Отменено заказчиком (вообще не пойдет в работу)"},
            {"ID": "1380", "VALUE": "Принятие решение отложено (на след год)"},
            {"ID": "1382", "VALUE": "Финансы (нет бюджета)"},
            {"ID": "1384", "VALUE": "Стратегическое решение - использовать конкурента"},
            {"ID": "1386", "VALUE": "Не решает проблему заказчика"},
            {"ID": "1388", "VALUE": "Партнерская политика"},
            {"ID": "1390", "VALUE": "Прочее (форс-мажор)"},
        ],
        "title": "UF_CRM_1715001901852",
        "listLabel": "Причины отказа квалификации",
        "formLabel": "Причины отказа квалификации",
        "filterLabel": "Причины отказа квалификации",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715001942471": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "870", "VALUE": "Подготовка предложения"},
            {"ID": "872", "VALUE": "КП отправлено"},
            {"ID": "874", "VALUE": "Счёт отправлен"},
            {"ID": "876", "VALUE": "Поставка оборудования"},
        ],
        "title": "UF_CRM_1715001942471",
        "listLabel": "Сделка побывала на стадии (тех)",
        "formLabel": "Сделка побывала на стадии (тех)",
        "filterLabel": "Сделка побывала на стадии (тех)",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715001959646": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715001959646",
        "listLabel": "Спецификация",
        "formLabel": "Спецификация",
        "filterLabel": "Спецификация",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1715001968071": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715001968071",
        "listLabel": "Дата перезвона",
        "formLabel": "Дата перезвона",
        "filterLabel": "Дата перезвона",
        "settings": {"DEFAULT_VALUE": {"TYPE": "NONE", "VALUE": ""}},
    },
    "UF_CRM_1715001976297": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715001976297",
        "listLabel": "Время подготовки",
        "formLabel": "Время подготовки",
        "filterLabel": "Время подготовки",
        "settings": {"DEFAULT_VALUE": {"TYPE": "NONE", "VALUE": ""}},
    },
    "UF_CRM_1715002007990": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "878", "VALUE": "100% предоплата"},
            {"ID": "880", "VALUE": "Частичная оплата"},
            {"ID": "882", "VALUE": "100% постоплата"},
        ],
        "title": "UF_CRM_1715002007990",
        "listLabel": "Условия оплаты",
        "formLabel": "Условия оплаты",
        "filterLabel": "Условия оплаты",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715002022163": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002022163",
        "listLabel": "Файл счёта (удалить)",
        "formLabel": "Файл счёта (удалить)",
        "filterLabel": "Файл счёта (удалить)",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1715002030562": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002030562",
        "listLabel": "Поставка оборудования",
        "formLabel": "Поставка оборудования",
        "filterLabel": "Поставка оборудования",
        "settings": {"DEFAULT_VALUE": {"TYPE": "NONE", "VALUE": ""}},
    },
    "UF_CRM_1715002242287": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "884", "VALUE": "Маржинальность"},
            {"ID": "886", "VALUE": "Небольшой объем"},
            {"ID": "888", "VALUE": "Сложные условия работы с заказчиком"},
            {"ID": "890", "VALUE": "Нет времени для обработки заявки"},
            {"ID": "892", "VALUE": "Не успели из-за крайне сжатых сроков"},
            {"ID": "894", "VALUE": "Не устроили договорные условия"},
            {"ID": "896", "VALUE": "Ошибка в подборе оборудования"},
            {"ID": "898", "VALUE": "Отменено заказчиком (не пойдет в работу)"},
            {"ID": "902", "VALUE": "Финансы (нет бюджета)"},
            {"ID": "906", "VALUE": "Стратегическое решение - использовать конкурента"},
            {
                "ID": "908",
                "VALUE": "Конкурент обладает преимущественными условиями (Отсрочка склад), подписанный договор.",
            },
            {"ID": "910", "VALUE": "Не решает проблему заказчика"},
            {
                "ID": "912",
                "VALUE": "Разница в цене с продуктом конкурента (по технике все ок)",
            },
            {
                "ID": "914",
                "VALUE": "Спецификация заказчика фиксирована и не пошел на изменения",
            },
            {"ID": "916", "VALUE": "Доставка (есть у ЭТМ и она бесплатна)"},
            {"ID": "918", "VALUE": "Срок доставки не устраивает"},
            {"ID": "920", "VALUE": "=Характеристики продукта (производительность)"},
            {
                "ID": "922",
                "VALUE": "Совместимость/Удобство интеграции продуктов в экосистему/Функционал (например Контроллеры и серво одного производителя)",
            },
            {"ID": "924", "VALUE": "Ошибка в расчете"},
            {
                "ID": "926",
                "VALUE": "Нет обратной связи, не актуально (Отказ без причины)",
            },
            {"ID": "928", "VALUE": "Возврат"},
            {"ID": "930", "VALUE": "Брак"},
            {
                "ID": "932",
                "VALUE": "Качество продукции (была выпущена партия с браком)",
            },
            {"ID": "934", "VALUE": "Партнерская политика"},
            {"ID": "936", "VALUE": "Изменение сроков поставки в процессе работы"},
            {"ID": "938", "VALUE": "Прочее (форс-мажор)"},
        ],
        "title": "UF_CRM_1715002242287",
        "listLabel": "Причины отказа дистрибьюции",
        "formLabel": "Причины отказа дистрибьюции",
        "filterLabel": "Причины отказа дистрибьюции",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715002257633": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1715002257633",
        "listLabel": "Получение документов",
        "formLabel": "Получение документов",
        "filterLabel": "Получение документов",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1715002266121": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002266121",
        "listLabel": "Дата поступления на склад поставщика",
        "formLabel": "Дата поступления на склад поставщика",
        "filterLabel": "Дата поступления на склад поставщика",
        "settings": {"DEFAULT_VALUE": {"TYPE": "NONE", "VALUE": ""}},
    },
    "UF_CRM_1715002274449": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002274449",
        "listLabel": "Дата прихода на склад Мотрум",
        "formLabel": "Дата прихода на склад Мотрум",
        "filterLabel": "Дата прихода на склад Мотрум",
        "settings": {"DEFAULT_VALUE": {"TYPE": "NONE", "VALUE": ""}},
    },
    "UF_CRM_1715002316": {
        "type": "crm",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002316",
        "listLabel": "Поставщик",
        "formLabel": "Поставщик",
        "filterLabel": "Поставщик",
        "settings": {"COMPANY": "Y", "LEAD": None},
    },
    "UF_CRM_1715002375997": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "940", "VALUE": "Клиент"},
            {"ID": "942", "VALUE": "Мотрум"},
            {"ID": "944", "VALUE": "ПМН Мотрум"},
        ],
        "title": "UF_CRM_1715002375997",
        "listLabel": "За чей счёт отправка",
        "formLabel": "За чей счёт отправка",
        "filterLabel": "За чей счёт отправка",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715002396068": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "946", "VALUE": "1"},
            {"ID": "948", "VALUE": "2"},
            {"ID": "950", "VALUE": "3"},
            {"ID": "952", "VALUE": "4"},
            {"ID": "954", "VALUE": "5"},
        ],
        "title": "UF_CRM_1715002396068",
        "listLabel": "Причины отказа проектов",
        "formLabel": "Причины отказа проектов",
        "filterLabel": "Причины отказа проектов",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715002427980": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "956", "VALUE": "Мотрум"},
            {"ID": "958", "VALUE": "ПМН Мотрум"},
        ],
        "title": "UF_CRM_1715002427980",
        "listLabel": "Грузоотправитель",
        "formLabel": "Грузоотправитель",
        "filterLabel": "Грузоотправитель",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715002449": {
        "type": "crm",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002449",
        "listLabel": "Грузополучатель",
        "formLabel": "Грузополучатель",
        "filterLabel": "Грузополучатель",
        "settings": {"COMPANY": "Y", "LEAD": None},
    },
    "UF_CRM_1715002497107": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002497107",
        "listLabel": "Номер счёта",
        "formLabel": "Номер счёта",
        "filterLabel": "Номер счёта",
        "settings": {
            "PRECISION": 2,
            "SIZE": 20,
            "MIN_VALUE": 0,
            "MAX_VALUE": 0,
            "DEFAULT_VALUE": None,
        },
    },
    "UF_CRM_1715002502730": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002502730",
        "listLabel": "Дата счёта",
        "formLabel": "Дата счёта",
        "filterLabel": "Дата счёта",
        "settings": {"DEFAULT_VALUE": {"TYPE": "NONE", "VALUE": ""}},
    },
    "UF_CRM_1715002530901": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [
            {"ID": "960", "VALUE": "Деловые линии"},
            {"ID": "962", "VALUE": "СДЭК"},
            {"ID": "964", "VALUE": "Самовывоз"},
        ],
        "title": "UF_CRM_1715002530901",
        "listLabel": "Доставка",
        "formLabel": "Доставка",
        "filterLabel": "Доставка",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715002551": {
        "type": "crm",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002551",
        "listLabel": "Контактное лицо",
        "formLabel": "Контактное лицо",
        "filterLabel": "Контактное лицо",
        "settings": {"CONTACT": "Y", "LEAD": None},
    },
    "UF_CRM_1715002572278": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002572278",
        "listLabel": "Трек номер Деловые линии №1",
        "formLabel": "Трек номер Деловые линии №1",
        "filterLabel": "Трек номер Деловые линии №1",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_1715002579974": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715002579974",
        "listLabel": "Трек номер СДЭК №1",
        "formLabel": "Трек номер СДЭК №1",
        "filterLabel": "Трек номер СДЭК №1",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_1715003632": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715003632",
        "listLabel": "id сделки (тех)",
        "formLabel": "id сделки (тех)",
        "filterLabel": "id сделки (тех)",
        "settings": {
            "PRECISION": 2,
            "SIZE": 20,
            "MIN_VALUE": 0,
            "MAX_VALUE": 0,
            "DEFAULT_VALUE": None,
        },
    },
    "UF_CRM_1715171327856": {
        "type": "double",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715171327856",
        "listLabel": "КПП Грузополучателя",
        "formLabel": "КПП Грузополучателя",
        "filterLabel": "КПП Грузополучателя",
        "settings": {
            "PRECISION": 2,
            "SIZE": 20,
            "MIN_VALUE": 0,
            "MAX_VALUE": 0,
            "DEFAULT_VALUE": None,
        },
    },
    "UF_CRM_1715616037876": {
        "type": "enumeration",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "items": [{"ID": "1356", "VALUE": "Да"}, {"ID": "1358", "VALUE": "Нет"}],
        "title": "UF_CRM_1715616037876",
        "listLabel": "Шаблон сообщения на 1 стадии",
        "formLabel": "Шаблон сообщения на 1 стадии",
        "filterLabel": "Шаблон сообщения на 1 стадии",
        "settings": {
            "DISPLAY": "LIST",
            "LIST_HEIGHT": 1,
            "CAPTION_NO_VALUE": "",
            "SHOW_NO_VALUE": "Y",
        },
    },
    "UF_CRM_1715704478969": {
        "type": "date",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715704478969",
        "listLabel": "Дата получения документов",
        "formLabel": "Дата получения документов",
        "filterLabel": "Дата получения документов",
        "settings": {"DEFAULT_VALUE": {"TYPE": "NONE", "VALUE": ""}},
    },
    "UF_CRM_1715704786788": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1715704786788",
        "listLabel": "Адрес доставки",
        "formLabel": "Адрес доставки",
        "filterLabel": "Адрес доставки",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_1718022241494": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1718022241494",
        "listLabel": "Трек номер Деловые линии №2",
        "formLabel": "Трек номер Деловые линии №2",
        "filterLabel": "Трек номер Деловые линии №2",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_1718022266092": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1718022266092",
        "listLabel": "Трек номер СДЭК №2",
        "formLabel": "Трек номер СДЭК №2",
        "filterLabel": "Трек номер СДЭК №2",
        "settings": {
            "SIZE": 20,
            "ROWS": 1,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_666BEA3902BFA": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_666BEA3902BFA",
        "listLabel": "Источник посещения сайта",
        "formLabel": "Источник посещения сайта",
        "filterLabel": "Источник посещения сайта",
        "settings": {
            "SIZE": 20,
            "ROWS": 50,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
    "UF_CRM_1734772155723": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734772155723",
        "listLabel": "Оплачено",
        "formLabel": "Оплачено",
        "filterLabel": "Оплачено",
        "settings": {"DEFAULT_VALUE": ""},
    },
    "UF_CRM_1734772173389": {
        "type": "money",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734772173389",
        "listLabel": "Задолженность",
        "formLabel": "Задолженность",
        "filterLabel": "Задолженность",
        "settings": {"DEFAULT_VALUE": ""},
    },
    "UF_CRM_1734772516954": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734772516954",
        "listLabel": "Счёт",
        "formLabel": "Счёт",
        "filterLabel": "Счёт",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734772537613": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734772537613",
        "listLabel": "Счёт без печати",
        "formLabel": "Счёт без печати",
        "filterLabel": "Счёт без печати",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734772575764": {
        "type": "file",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": True,
        "isDynamic": True,
        "title": "UF_CRM_1734772575764",
        "listLabel": "Отгрузка",
        "formLabel": "Отгрузка",
        "filterLabel": "Отгрузка",
        "settings": {
            "SIZE": 20,
            "LIST_WIDTH": 0,
            "LIST_HEIGHT": 0,
            "MAX_SHOW_SIZE": 0,
            "MAX_ALLOWED_SIZE": 0,
            "EXTENSIONS": [],
            "TARGET_BLANK": "Y",
        },
    },
    "UF_CRM_1734772618817": {
        "type": "string",
        "isRequired": False,
        "isReadOnly": False,
        "isImmutable": False,
        "isMultiple": False,
        "isDynamic": True,
        "title": "UF_CRM_1734772618817",
        "listLabel": "Изменение цен OKT",
        "formLabel": "Изменение цен OKT",
        "filterLabel": "Изменение цен OKT",
        "settings": {
            "SIZE": 20,
            "ROWS": 5,
            "REGEXP": "",
            "MIN_LENGTH": 0,
            "MAX_LENGTH": 0,
            "DEFAULT_VALUE": "",
        },
    },
}


































{
    "ID": "17682",
    "COMPANY_TYPE": "CUSTOMER",
    "TITLE": "ТЕСТ КОМПАНИЯ (НЕ ИСПОЛЬЗОВАТЬ)",
    "LOGO": None,
    "LEAD_ID": None,
    "HAS_PHONE": "Y",
    "HAS_EMAIL": "N",
    "HAS_IMOL": "N",
    "ASSIGNED_BY_ID": "174",
    "CREATED_BY_ID": "174",
    "MODIFY_BY_ID": "174",
    "BANKING_DETAILS": None,
    "INDUSTRY": "OTHER",
    "REVENUE": "0",
    "CURRENCY_ID": "RUB",
    "EMPLOYEES": "EMPLOYEES_1",
    "COMMENTS": "",
    "DATE_CREATE": "2025-01-13T09:09:56+03:00",
    "DATE_MODIFY": "2025-01-14T14:47:27+03:00",
    "OPENED": "Y",
    "IS_MY_COMPANY": "N",
    "ORIGINATOR_ID": None,
    "ORIGIN_ID": None,
    "ORIGIN_VERSION": None,
    "LAST_ACTIVITY_TIME": "2025-01-13T09:09:56+03:00",
    "ADDRESS": "улица Алексея Толстого, 75",
    "ADDRESS_2": "21",
    "ADDRESS_CITY": "Самара",
    "ADDRESS_POSTAL_CODE": "443099",
    "ADDRESS_REGION": "городской округ Самара",
    "ADDRESS_PROVINCE": "Самарская область",
    "ADDRESS_COUNTRY": "Россия",
    "ADDRESS_COUNTRY_CODE": None,
    "ADDRESS_LOC_ADDR_ID": "11744",
    "ADDRESS_LEGAL": "МИЧУРИНА УЛ., Д.80",
    "REG_ADDRESS": "МИЧУРИНА УЛ., Д.80",
    "REG_ADDRESS_2": "ОФИС 1",
    "REG_ADDRESS_CITY": "САМАРА",
    "REG_ADDRESS_POSTAL_CODE": "443110",
    "REG_ADDRESS_REGION": None,
    "REG_ADDRESS_PROVINCE": "Самарская область",
    "REG_ADDRESS_COUNTRY": "Россия",
    "REG_ADDRESS_COUNTRY_CODE": None,
    "REG_ADDRESS_LOC_ADDR_ID": "11746",
    "UTM_SOURCE": None,
    "UTM_MEDIUM": None,
    "UTM_CAMPAIGN": None,
    "UTM_CONTENT": None,
    "UTM_TERM": None,
    "PARENT_ID_1038": None,
    "PARENT_ID_1042": None,
    "LAST_ACTIVITY_BY": "174",
    "UF_CRM_1558613176": "",
    "UF_CRM_1558613212": "",
    "UF_CRM_1558613254": "52",
    "UF_CRM_1558613582": "",
    "UF_CRM_1558613635": "",
    "UF_CRM_1558613708": "",
    "UF_CRM_1558613726": "",
    "UF_CRM_1558616744": "",
    "UF_CRM_1558616802": "",
    "UF_CRM_1558616826": "",
    "UF_CRM_1558616840": "",
    "UF_CRM_1558616931": "",
    "UF_CRM_1558617084": "44",
    "UF_CRM_1558623245": "",
    "UF_CRM_1563789139": "",
    "UF_CRM_1566214141": "",
    "UF_CRM_1566214266": "",
    "UF_CRM_1588918931594": "",
    "UF_CRM_1657688354898": "62",
    "UF_CRM_1657704194333": "",
    "UF_CRM_1657707392301": "",
    "UF_CRM_1688447705748": "",
    "UF_CRM_1688447766610": "",
    "UF_CRM_1688447793802": "",
    "UF_CRM_1688455216177": "",
    "UF_CRM_1688455299704": "",
    "UF_CRM_1688456588081": False,
    "UF_CRM_1688462292610": "",
    "UF_CRM_1701248964812": "",
    "UF_CRM_1701323584900": "",
    "UF_CRM_1713128519": "",
    "UF_CRM_1713347166445": "",
    "UF_CRM_1713347474446": "",
    "UF_CRM_1715666350407": False,
    "UF_CRM_1715666396114": "",
    "UF_CRM_1715666451082": "",
    "UF_CRM_1716738861264": "",
    "UF_CRM_1716738888187": "",
    "UF_CRM_1716739123682": "",
    "UF_CRM_1716739142475": "",
    "UF_CRM_1717680480": "",
    "UF_CRM_1717680608645": "",
    "UF_CRM_1717680638123": "",
    "UF_CRM_1717680704388": "",
    "UF_CRM_1717680747": "",
    "UF_CRM_1724223404": "1918",
    "UF_CRM_1729227546367": "",
    "UF_CRM_1729507828698": "",
    "UF_CRM_1732453421336": ["2025-01-01T03:00:00+03:00"],
    "UF_CRM_1732453513946": False,
    "UF_CRM_1732453586840": False,
    "UF_CRM_1732521891305": "123",
    "UF_CRM_1734773759421": "",
    "UF_CRM_1734773779593": "",
    "UF_CRM_1734773790171": "",
    "UF_CRM_1734773813228": "",
    "UF_CRM_1734773831303": "",
    "UF_CRM_1734773855347": "",
    "UF_CRM_1734773932047": "",
    "UF_CRM_1734773953432": "",
    "UF_CRM_1734773967506": "",
    "UF_CRM_1734773992815": "",
    "UF_CRM_1734774004222": "",
    "UF_CRM_1734774017217": "",
    "UF_CRM_1734774041551": "",
    "UF_CRM_1734774115032": "",
    "PHONE": [
        {
            "ID": "95998",
            "VALUE_TYPE": "WORK",
            "VALUE": "+79276892240",
            "TYPE_ID": "PHONE",
        }
    ],
}
