# Generated by Django 5.1 on 2024-08-13 08:36

import apps.core.utils
import apps.core.utils_web
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название решений')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to=apps.core.utils_web.get_file_path_catalog_web, verbose_name='Изображение решений')),
                ('article', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Вид решения',
                'verbose_name_plural': 'Виды решений',
            },
        ),
        migrations.CreateModel(
            name='ClientCategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отрасли')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to=apps.core.utils_web.get_file_path_catalog_web, verbose_name='Изображение категории')),
                ('article', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Отрасль клиента',
                'verbose_name_plural': 'Отрасли клиентов',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('short_text', models.CharField(max_length=500, verbose_name='Короткий текст вступление')),
                ('text', models.TextField(verbose_name='Большой текст')),
                ('image_main', models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add, verbose_name='Главное изображение')),
                ('is_view_home_web', models.BooleanField(default=False, verbose_name='Отображение на главной сайта')),
                ('category_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_web.categoryproject', verbose_name='Категории товара от поставщиков')),
                ('client_category_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects_web.clientcategoryproject', verbose_name='Категория Мотрум')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=apps.core.utils.get_file_path_add, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.project')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проекта',
            },
        ),
    ]
