# Generated by Django 5.1 on 2024-08-13 09:12

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='product',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='photo',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='categoryproject',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Изображение решений'),
        ),
    ]
