# Generated by Django 5.1 on 2024-08-13 10:33

import apps.core.utils_web
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0002_rename_product_projectimage_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproject',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Изображение решений'),
        ),
        migrations.AlterField(
            model_name='clientcategoryproject',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_web.categoryproject', verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_category_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects_web.clientcategoryproject', verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_main',
            field=models.ImageField(max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Изображение'),
        ),
    ]
