# Generated by Django 5.1 on 2024-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0003_alter_categoryproject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_view_home_web',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной сайта'),
        ),
    ]
