# Generated by Django 5.1.2 on 2024-12-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0004_alter_project_is_view_home_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок абзаца')),
                ('short_text', models.CharField(max_length=500, verbose_name='Короткий текст вступление')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.project')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проекта',
            },
        ),
    ]
