# Generated by Django 5.1.2 on 2024-12-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0005_projecttextblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcategoryproject',
            name='image',
        ),
        migrations.AddField(
            model_name='projecttextblock',
            name='text',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Текст основной'),
        ),
        migrations.AlterField(
            model_name='projecttextblock',
            name='short_text',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Короткий текст вступление'),
        ),
        migrations.AlterField(
            model_name='projecttextblock',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заголовок абзаца'),
        ),
        migrations.CreateModel(
            name='ProjectClientCategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.categoryproject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.project')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли ',
            },
        ),
    ]
