# Generated by Django 5.1.2 on 2024-12-04 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0006_remove_clientcategoryproject_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategoryProjectMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название маркировки')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('article', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Маркировка',
                'verbose_name_plural': 'Маркировка',
            },
        ),
        migrations.AlterModelOptions(
            name='projectclientcategoryproject',
            options={'verbose_name': 'Отрасль', 'verbose_name_plural': 'Отрасли'},
        ),
        migrations.AlterModelOptions(
            name='projecttextblock',
            options={'verbose_name': 'Абзацы проекта', 'verbose_name_plural': 'Абзацы проекта'},
        ),
        migrations.AddField(
            model_name='project',
            name='data_create',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='project',
            name='data_project',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата реализации проекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='place_object',
            field=models.CharField(default=1, max_length=500, verbose_name='Место реализации'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectClientCategoryProjectMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_category_marking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.clientcategoryprojectmarking')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.project')),
            ],
            options={
                'verbose_name': 'Маркировка',
                'verbose_name_plural': 'Маркировка ',
            },
        ),
    ]
