# Generated by Django 5.1.2 on 2024-12-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0007_clientcategoryprojectmarking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='place_object',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место реализации'),
        ),
        migrations.AlterField(
            model_name='projecttextblock',
            name='short_text',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий текст вступление'),
        ),
        migrations.AlterField(
            model_name='projecttextblock',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст основной'),
        ),
        migrations.AlterField(
            model_name='projecttextblock',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок абзаца'),
        ),
    ]
