# Generated by Django 5.1.2 on 2024-12-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0008_alter_project_place_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='short_text',
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(verbose_name='Текст открывающий'),
        ),
    ]
