# Generated by Django 5.1.2 on 2024-12-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0009_remove_project_short_text_alter_project_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttextblock',
            name='short_text',
        ),
        migrations.AlterField(
            model_name='projecttextblock',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст абзаца'),
        ),
        migrations.AlterField(
            model_name='projecttextblock',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заголовок абзаца'),
        ),
    ]
