# Generated by Django 5.1.2 on 2024-12-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0010_remove_projecttextblock_short_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectclientcategoryprojectmarking',
            options={'verbose_name': 'Маркировка', 'verbose_name_plural': 'Маркировка'},
        ),
        migrations.AlterField(
            model_name='projectclientcategoryproject',
            name='client_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.clientcategoryproject'),
        ),
    ]
