# Generated by Django 5.1.4 on 2024-12-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0012_alter_projecttextblock_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_category_project',
        ),
    ]
