# Generated by Django 5.1.4 on 2024-12-05 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0013_remove_project_client_category_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproject',
            name='short_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Короткое название решений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcategoryproject',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Короткое название '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcategoryprojectmarking',
            name='short_name',
            field=models.CharField(default='sdfds', max_length=100, verbose_name='Короткое название решений'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryproject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название решений'),
        ),
        migrations.AlterField(
            model_name='clientcategoryproject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название отрасли'),
        ),
        migrations.AlterField(
            model_name='clientcategoryprojectmarking',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название маркировки'),
        ),
    ]
