# Generated by Django 5.1.4 on 2024-12-06 05:25

import apps.core.utils_web
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0014_categoryproject_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclientcategoryproject',
            name='client_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.clientcategoryproject', verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='projectclientcategoryprojectmarking',
            name='client_category_marking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.clientcategoryprojectmarking', verbose_name='Маркировка'),
        ),
        migrations.CreateModel(
            name='VideoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(max_length=255, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Видео')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_web.project')),
            ],
            options={
                'verbose_name': 'Видео проекта',
                'verbose_name_plural': 'Видео проекта',
            },
        ),
    ]
