# Generated by Django 5.1.4 on 2024-12-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0015_alter_projectclientcategoryproject_client_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoImage',
            new_name='ProjectVideo',
        ),
    ]
