# Generated by Django 5.1.4 on 2024-12-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0016_rename_videoimage_projectvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст открывающий'),
        ),
    ]
