# Generated by Django 5.1.4 on 2024-12-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0017_alter_project_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproject',
            name='image',
        ),
        migrations.AlterField(
            model_name='categoryproject',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название решений'),
        ),
        migrations.AlterField(
            model_name='clientcategoryproject',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название '),
        ),
        migrations.AlterField(
            model_name='clientcategoryprojectmarking',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое название решений'),
        ),
    ]
