# Generated by Django 5.1.5 on 2025-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0018_remove_categoryproject_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания(не отображается на сайте)'),
        ),
    ]
