# Generated by Django 5.1.5 on 2025-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0019_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_project',
            field=models.DateField(blank=True, null=True, verbose_name='Дата реализации проекта'),
        ),
    ]
