# Generated by Django 5.1.5 on 2025-05-27 10:22

import apps.core.utils_web
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_web', '0020_alter_project_data_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_main',
            field=models.ImageField(max_length=1000, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(max_length=1000, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.FileField(max_length=1000, null=True, upload_to=apps.core.utils_web.get_file_path_project_web, verbose_name='Видео'),
        ),
    ]
