# Generated by Django 5.1.1 on 2024-09-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("DOCUMENT_SPECIFICATION", "документ спецификации"),
                    ("DOCUMENT_BILL", "документ счета"),
                    ("DOCUMENT_ACT", "документ акта"),
                    ("STATUS_ORDERING", "статус заказа"),
                ],
                default="STATUS_ORDERING",
                max_length=100,
            ),
        ),
    ]
