# Generated by Django 5.1.5 on 2025-03-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='file',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
