# Generated by Django 5.1.5 on 2025-03-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
